<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompensationApplicableIndustrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_compensation_applicable_industry')->insert([
            [
                'industry_classification'   => '林業',
                'industry_type_no'  => '02',
                'industry_type'  => '林業',
                'detail_alphabet'  => 'Ａ',
                'detail_summary'  => '木材伐出業',
                'detail_no'  => '0201',
                'detail_content1'  => '伐木、造材、集材若しくは運材の事業又はこれらに付随する事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '林業',
                'industry_type_no'  => '03',
                'industry_type'  => '林業',
                'detail_alphabet'  => 'Ｂ ',
                'detail_summary'  => 'その他の林業',
                'detail_no'  => '0301',
                'detail_content1'  => '植林若しくは造林の事業又はこれらに付随する事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '林業',
                'industry_type_no'  => '03',
                'industry_type'  => '林業',
                'detail_alphabet'  => 'Ｂ ',
                'detail_summary'  => 'その他の林業',
                'detail_no'  => '0302',
                'detail_content1'  => '竹の伐出業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '林業',
                'industry_type_no'  => '03',
                'industry_type'  => '林業',
                'detail_alphabet'  => 'Ｂ ',
                'detail_summary'  => 'その他の林業',
                'detail_no'  => '0304',
                'detail_content1'  => '薪の切出製造若しくは木炭の製造又はこれらに付随する搬出の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '林業',
                'industry_type_no'  => '03',
                'industry_type'  => '林業',
                'detail_alphabet'  => 'Ｂ ',
                'detail_summary'  => 'その他の林業',
                'detail_no'  => '0303',
                'detail_content1'  => 'その他の各種林業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '漁業',
                'industry_type_no'  => '11',
                'industry_type'  => '海面漁業((12)定置網漁業又は海面魚類養殖業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '1101',
                'detail_content1'  => '海面において行う水産動物(貝類を除く。）の採捕の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '漁業',
                'industry_type_no'  => '12',
                'industry_type'  => '定置網漁業又は海面魚類養殖業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '1201',
                'detail_content1'  => '海面において定置網を用いて行う漁業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '漁業',
                'industry_type_no'  => '12',
                'industry_type'  => '定置網漁業又は海面魚類養殖業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '1202',
                'detail_content1'  => '海面において行う魚類の養殖の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '21',
                'industry_type'  => '金属鉱業、非金属鉱業((23)石灰石鉱業又はドロマイト 鉱 業 を 除く 。） 又は石炭鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2101',
                'detail_content1'  => '金属鉱業',
                'detail_kana'  => null,
                'detail_content2'  => '金鉱、銀鉱、銅鉱、鉛鉱、蒼鉛鉱、すず鉱、アンチモニー鉱、水銀鉱、亜鉛鉱、鉄鉱、硫化鉄鉱、クローム鉄鉱、マンガン鉱、タングステン鉱、モリブデン鉱、砒鉱、ニツケル鉱、コバルト鉱、ウラン鉱又はトリウム鉱の鉱業',
                'remarks'  => '(2601)砂鉱業、(2602)石炭遥別業及び(2603)亜炭鉱業( 亜 炭 遥別業を含む 。） を除く。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '21',
                'industry_type'  => '金属鉱業、非金属鉱業((23)石灰石鉱業又はドロマイト 鉱 業 を 除く 。） 又は石炭鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2102',
                'detail_content1'  => '非金属鉱業',
                'detail_kana'  => null,
                'detail_content2'  => 'りん鉱、黒鉛、アスフアルト、硫黄、石膏、重晶石、明ばん石、ほたる石、石綿、けい石、長石、ろう石、滑石又は耐火粘土の鉱業',
                'remarks'  => '(2601)砂鉱業、(2602)石炭遥別業及び(2603)亜炭鉱業( 亜 炭 遥別業を含む 。） を除く。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '21',
                'industry_type'  => '金属鉱業、非金属鉱業((23)石灰石鉱業又はドロマイト 鉱 業 を 除く 。） 又は石炭鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2103',
                'detail_content1'  => '無煙炭鉱業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(2601)砂鉱業、(2602)石炭遥別業及び(2603)亜炭鉱業( 亜 炭 遥別業を含む 。） を除く。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '21',
                'industry_type'  => '金属鉱業、非金属鉱業((23)石灰石鉱業又はドロマイト 鉱 業 を 除く 。） 又は石炭鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2104',
                'detail_content1'  => 'れき青炭鉱業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(2601)砂鉱業、(2602)石炭遥別業及び(2603)亜炭鉱業( 亜 炭 遥別業を含む 。） を除く。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '21',
                'industry_type'  => '金属鉱業、非金属鉱業((23)石灰石鉱業又はドロマイト 鉱 業 を 除く 。） 又は石炭鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2105',
                'detail_content1'  => 'その他の石炭鉱業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(2601)砂鉱業、(2602)石炭遥別業及び(2603)亜炭鉱業( 亜 炭 遥別業を含む 。） を除く。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '23',
                'industry_type'  => '石灰石鉱業又 はドロマイト鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2301',
                'detail_content1'  => '石灰石鉱業又はドロマイト鉱業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(2601)砂鉱業、(2602)石炭遥別業及び(2603)亜炭鉱業( 亜 炭 遥別業を含む 。） を除く。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '24',
                'industry_type'  => '原油又は天然 ガス鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2401',
                'detail_content1'  => '原油鉱業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(2601)砂鉱業、(2602)石炭遥別業及び(2603)亜炭鉱業( 亜 炭 遥別業を含む 。） を除く。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '24',
                'industry_type'  => '原油又は天然 ガス鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2402',
                'detail_content1'  => '天然ガス鉱業又は圧縮天然ガス生産業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(2601)砂鉱業、(2602)石炭遥別業及び(2603)亜炭鉱業( 亜 炭 遥別業を含む 。） を除く。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '25',
                'industry_type'  => '採石業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2501',
                'detail_content1'  => '花こう岩、せん緑岩、斑糲岩、かんらん岩、斑岩、玢岩、輝緑岩、粗面岩、安山岩、玄武岩、礫岩、砂岩、頁岩、粘板岩、ぎよう灰岩、片麻岩、蛇紋岩、結晶片岩、ベントナイト、郿性白土、けいそう土、陶石、雲母又はひる石の採取業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(2604)砂利、砂等の採取業を除き、一貫して行う岩石又は粘土( 耐 火 粘土 を 除く 。） の破砕等の(4901)その他の窯業又は土石製品製造業を含む。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '25',
                'industry_type'  => '採石業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2502',
                'detail_content1'  => 'その他の岩石又は粘土(耐火粘土を除く。）等の採取業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(2604)砂利、砂等の採取業を除き、一貫して行う岩石又は粘土( 耐 火 粘土 を 除く 。） の破砕等の(4901)その他の窯業又は土石製品製造業を含む。',
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '26',
                'industry_type'  => 'その他の鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2601',
                'detail_content1'  => '砂鉱業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '26',
                'industry_type'  => 'その他の鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2602',
                'detail_content1'  => '石炭遥別業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '26',
                'industry_type'  => 'その他の鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2603',
                'detail_content1'  => '亜炭鉱業(亜炭遥別業を含む。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '鉱業',
                'industry_type_no'  => '26',
                'industry_type'  => 'その他の鉱業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '2604',
                'detail_content1'  => '砂利、砂等の採取業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '31',
                'industry_type'  => '水力発電施設、隧道等新設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3101',
                'detail_content1'  => '水力発電施設新設事業',
                'detail_kana'  => null,
                'detail_content2'  => '水力発電施設の新設に関する建設事業及びこれに附帯して当該事業現場内において行われる事業(発電所又は変電所の家屋の建築事業、水力発電施設新設事業現場に至るまでの工事用資材の運送のための道路、鉄道又は軌道の建設事業、建設工事用機械以外の機械若しくは鉄管の組立て又はすえ付けの事業、送電線路の建設事業及び水力発電施設新設事業現場外における索道の建設事業を除く。）',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '31',
                'industry_type'  => '水力発電施設、隧道等新設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3102',
                'detail_content1'  => '高えん堤新設事業',
                'detail_kana'  => null,
                'detail_content2'  => '基礎地盤から堤頂までの高さ20メートル以上のえん堤（フイルダムを除く。）の新設に関する建設事業及びこれに附帯して当該事業現場内において行われる事業（高えん堤新設事業現場に至るまでの工事用資材の運送のための道路、鉄道又は軌道の建設事業、建設工事用機械以外の機械の組立て又はすえ付けの事業及び高えん堤新設事業現場外における索道の建設事業を除く。）',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '31',
                'industry_type'  => '水力発電施設、隧道等新設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3103',
                'detail_content1'  => '隧道新設事業',
                'detail_kana'  => null,
                'detail_content2'  => '隧道の新設に関する建設事業、隧道の内面巻替えの事業及びこれらに附帯して当該事業現場内において行われる事業（隧道新設事業の態様をもつて行われる道路、鉄道、軌道、水路、煙道、建築物等の建設事業（推逭工治による管の埋設の事業を除く。）を含み、内面巻立て後の隧道内において路面ほ装、砂利散布又は軌条の敷設を行う事業及び内面巻立て後の隧道内における建築物の建設事業を除く。）',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '32',
                'industry_type'  => '道路新設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3201',
                'detail_content1'  => '道路の新設に関する建設事業及びこれに附帯して行われる事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(3103)隧道新設事業 及 び(35)建築事業を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '33',
                'industry_type'  => 'ほ装工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3301',
                'detail_content1'  => '道路、広場、プラツトホーム等のほ装事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '33',
                'industry_type'  => 'ほ装工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3302',
                'detail_content1'  => '砂利散布の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '33',
                'industry_type'  => 'ほ装工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3303',
                'detail_content1'  => '広場の展圧又は芝張りの事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '34',
                'industry_type'  => '鉄道又は軌道新設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3401',
                'detail_content1'  => '開さく式地下鉄道の新設に関する建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(3103)隧道新設事業 及 び(35)建築事業を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '34',
                'industry_type'  => '鉄道又は軌道新設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3402',
                'detail_content1'  => 'その他の鉄道又は軌道の新設に関する建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(3103)隧道新設事業 及 び(35)建築事業を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3501',
                'detail_content1'  => '鉄骨造り又は鉄骨鉄筋若しくは鉄筋コンクリート造りの家屋の建設事業((3103）隧道新設事業の態様をもつて行われるものを除く。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3502',
                'detail_content1'  => '木造、れんが造り、石造り、ブロツク造り等の家屋の建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3503',
                'detail_content1'  => '橋りよう建設事業',
                'detail_kana'  => 'イ',
                'detail_content2'  => '一般橋りようの建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3503',
                'detail_content1'  => '橋りよう建設事業',
                'detail_kana'  => 'ロ',
                'detail_content2'  => '道路又は鉄道の鉄骨鉄筋若しくは鉄筋コンクリート造りの高架橋の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3503',
                'detail_content1'  => '橋りよう建設事業',
                'detail_kana'  => 'ハ',
                'detail_content2'  => '跨線道路橋の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3503',
                'detail_content1'  => '橋りよう建設事業',
                'detail_kana'  => 'ニ',
                'detail_content2'  => 'さん橋の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3504',
                'detail_content1'  => '建築物の新設に伴う設備工事業（（3507)建築物の新設に伴う電気の設備工事業及び（3715）さく井事業を除く。）',
                'detail_kana'  => 'イ',
                'detail_content2'  => '電話の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3504',
                'detail_content1'  => '建築物の新設に伴う設備工事業（（3507)建築物の新設に伴う電気の設備工事業及び（3715）さく井事業を除く。）',
                'detail_kana'  => 'ロ',
                'detail_content2'  => '給水、給湯等の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3504',
                'detail_content1'  => '建築物の新設に伴う設備工事業（（3507)建築物の新設に伴う電気の設備工事業及び（3715）さく井事業を除く。）',
                'detail_kana'  => 'ハ',
                'detail_content2'  => '衛生、消火等の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3504',
                'detail_content1'  => '建築物の新設に伴う設備工事業（（3507)建築物の新設に伴う電気の設備工事業及び（3715）さく井事業を除く。）',
                'detail_kana'  => 'ニ',
                'detail_content2'  => '暖房、冷房、換気、乾燥、温湿度調整等の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3504',
                'detail_content1'  => '建築物の新設に伴う設備工事業（（3507)建築物の新設に伴う電気の設備工事業及び（3715）さく井事業を除く。）',
                'detail_kana'  => 'ホ',
                'detail_content2'  => '工作物の塗装工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3504',
                'detail_content1'  => '建築物の新設に伴う設備工事業（（3507)建築物の新設に伴う電気の設備工事業及び（3715）さく井事業を除く。）',
                'detail_kana'  => 'ヘ',
                'detail_content2'  => 'その他の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3507',
                'detail_content1'  => '建築物の新設に伴う電気の設備工事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3508',
                'detail_content1'  => '送電線路又は郤電線路の建設（埋設を除く。）の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3505',
                'detail_content1'  => '工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再度使用することを前提に解体するものに限る。）、移動、取りはずし又は撤去の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'イ',
                'detail_content2'  => '野球場、競技場等の鉄骨造り又は鉄骨鉄筋若しくは鉄筋コンクリート造りのスタンドの建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'ロ',
                'detail_content2'  => 'たい雪覆い、雪止め柵、落石覆い、落石防止柵等の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'ハ',
                'detail_content2'  => '鉄塔又は跨線橋(跨線道路橋を除く。）の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'ニ',
                'detail_content2'  => '煙突、煙道、風泦等の建設事業((3103)隧道新設事業の態様をもつて行われるものを除く。）',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'ホ',
                'detail_content2'  => 'やぐら、鳥居、広告塔、タンク等の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'へ',
                'detail_content2'  => '門、塀、柵、庭園等の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'ト',
                'detail_content2'  => '炉の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'チ',
                'detail_content2'  => '通信線路又は鉄管の建設(埋設を除く。）の事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'リ',
                'detail_content2'  => '信号機の建設事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '35',
                'industry_type'  => '建 築 事 業((38）既設建築物設備工事業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3506',
                'detail_content1'  => 'その他の建築事業',
                'detail_kana'  => 'ヌ',
                'detail_content2'  => 'その他の各種建築事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '38',
                'industry_type'  => '既設建築物設備工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3801',
                'detail_content1'  => '既設建築物の内部において主として行われる次に掲げる事業及びこれに附帯して行われる事業（建設工事用機械以外の機械の組立て又はすえ付けの事業、(3802)既設建築物の内部において主として行われる電気の設備工事業及び(3715)さく井事業を除く。）',
                'detail_kana'  => 'イ',
                'detail_content2'  => '電話の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '38',
                'industry_type'  => '既設建築物設備工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3801',
                'detail_content1'  => '既設建築物の内部において主として行われる次に掲げる事業及びこれに附帯して行われる事業（建設工事用機械以外の機械の組立て又はすえ付けの事業、(3802)既設建築物の内部において主として行われる電気の設備工事業及び(3715)さく井事業を除く。）',
                'detail_kana'  => 'ロ',
                'detail_content2'  => '給水、給湯等の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '38',
                'industry_type'  => '既設建築物設備工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3801',
                'detail_content1'  => '既設建築物の内部において主として行われる次に掲げる事業及びこれに附帯して行われる事業（建設工事用機械以外の機械の組立て又はすえ付けの事業、(3802)既設建築物の内部において主として行われる電気の設備工事業及び(3715)さく井事業を除く。）',
                'detail_kana'  => 'ハ',
                'detail_content2'  => '衛生、消火等の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '38',
                'industry_type'  => '既設建築物設備工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3801',
                'detail_content1'  => '既設建築物の内部において主として行われる次に掲げる事業及びこれに附帯して行われる事業（建設工事用機械以外の機械の組立て又はすえ付けの事業、(3802)既設建築物の内部において主として行われる電気の設備工事業及び(3715)さく井事業を除く。）',
                'detail_kana'  => 'ニ',
                'detail_content2'  => '暖房、冷房、換気、乾燥、温湿度調整等の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '38',
                'industry_type'  => '既設建築物設備工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3801',
                'detail_content1'  => '既設建築物の内部において主として行われる次に掲げる事業及びこれに附帯して行われる事業（建設工事用機械以外の機械の組立て又はすえ付けの事業、(3802)既設建築物の内部において主として行われる電気の設備工事業及び(3715)さく井事業を除く。）',
                'detail_kana'  => 'ホ',
                'detail_content2'  => '工作物の塗装工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '38',
                'industry_type'  => '既設建築物設備工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3801',
                'detail_content1'  => '既設建築物の内部において主として行われる次に掲げる事業及びこれに附帯して行われる事業（建設工事用機械以外の機械の組立て又はすえ付けの事業、(3802)既設建築物の内部において主として行われる電気の設備工事業及び(3715)さく井事業を除く。）',
                'detail_kana'  => 'へ',
                'detail_content2'  => 'その他の設備工事業',
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '38',
                'industry_type'  => '既設建築物設備工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3802',
                'detail_content1'  => '既設建築物の内部において主として行われる電気の設備工事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '38',
                'industry_type'  => '既設建築物設備工事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3803',
                'detail_content1'  => '既設建築物における建具の取付け、床張りその他の内装工事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '36',
                'industry_type'  => '機械装置の組立て又はすえ付けの事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3601',
                'detail_content1'  => '各種機械装置の組立て又はすえ付けの事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '36',
                'industry_type'  => '機械装置の組立て又はすえ付けの事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3602',
                'detail_content1'  => '索道建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3701',
                'detail_content1'  => 'えん堤の建設事業((3102)高えん堤新設事業を除く。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3702',
                'detail_content1'  => '隧道の改修、復旧若しくは維持の事業又は推逭工治による管の埋設の事業((3103)内面巻替えの事業を除く。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3703',
                'detail_content1'  => '道路の改修、復旧又は維持の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3704',
                'detail_content1'  => '鉄道又は軌道の改修、復旧又は維持の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3705',
                'detail_content1'  => '河川又はその附属物の改修、復旧又は維持の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3706',
                'detail_content1'  => '運沢若しくは水路又はこれらの附属物の建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3707',
                'detail_content1'  => '貯水池、鉱毒沈澱池、プール等の建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3708',
                'detail_content1'  => '水門、樋門等の建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3709',
                'detail_content1'  => '砂防設備(植林のみによるものを除く。）の建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3710',
                'detail_content1'  => '海岸又は港湾における防波堤、岸壁、船だまり場等の建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3711',
                'detail_content1'  => '湖沼、河川又は海面の浚渫、干拓又は埋立ての事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3712',
                'detail_content1'  => '開墾、耕地整理又は敷地若しくは広場の造成の事業（一貫して行う(3719)造園の事業を含む。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3719',
                'detail_content1'  => '造園の事業
',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3713',
                'detail_content1'  => '地下に構築する各種タンクの建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3714',
                'detail_content1'  => '鉄管、コンクリート管、ケーブル、鋼材等の埋設の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3715',
                'detail_content1'  => 'さく井事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3716',
                'detail_content1'  => '工作物の解体事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3717',
                'detail_content1'  => '沈没物の引揚げ事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '建設事業',
                'industry_type_no'  => '37',
                'industry_type'  => 'その他の建設事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '3718',
                'detail_content1'  => 'その他の各種建設事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(33)ほ装工事業及び(3505)工作物の解体（一部分を解体するもの又は当該工作物に使用されている資材の大部分を再 度使用することを 前提に解 体するも のに限る。）、移動、 取りはず し又は撤 去の事業 を除く。',
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '41',
                'industry_type'  => '食料品製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4101',
                'detail_content1'  => '食料品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '41',
                'industry_type'  => '食料品製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4112',
                'detail_content1'  => 'たばこ等製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '42',
                'industry_type'  => '繊維工業又は 繊維製品製造 業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4201',
                'detail_content1'  => '繊維工業又は繊維製品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '44',
                'industry_type'  => '木材又は木製品製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4401',
                'detail_content1'  => '木材又は木製品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '( 6 1 0 8 )竹、籐又はきりゆう製品製造業を除く。',
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '45',
                'industry_type'  => 'パルプ又は紙 製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4501',
                'detail_content1'  => 'パルプ又は紙製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '46',
                'industry_type'  => '印刷又は製本 業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4601',
                'detail_content1'  => '印刷又は製本業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '47',
                'industry_type'  => '化学工業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4701',
                'detail_content1'  => '化学工業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '(42)繊維 工業又は繊維製品製造業及び(6110)くずゴム製品製造業 を 除く。',
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '48',
                'industry_type'  => 'ガラス又はセ メント製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4801',
                'detail_content1'  => 'ガラス又はセメント製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '66',
                'industry_type'  => 'コンクリート製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6601',
                'detail_content1'  => 'コンクリート製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '62',
                'industry_type'  => '陶磁器製品製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6201',
                'detail_content1'  => '陶磁器製品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '49',
                'industry_type'  => 'その他の窯業 又は土石製品 製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '4901',
                'detail_content1'  => 'その他の窯業又は土石製品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '50',
                'industry_type'  => '金属精錬業((51)非鉄金属精錬業を除く。)',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5001',
                'detail_content1'  => '金属精錬業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '一貫して行う(52)金属材料品製造業を含む。',
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '51',
                'industry_type'  => '非鉄金属精錬業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5101',
                'detail_content1'  => '非鉄金属精錬業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '一貫して行う（52）金属材料品製造業を含む。',
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '52',
                'industry_type'  => '金属材料品製造業((53)鋳物業を除く。)',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5201',
                'detail_content1'  => '金属材料品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '一貫して(50)金属精錬業又は(51)非鉄金属精錬業を行うものを除く。',
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '53',
                'industry_type'  => '鋳物業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5301',
                'detail_content1'  => '鋳物業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '54',
                'industry_type'  => '金属製品製造 業又は金属加 工業((63)泛 食器、刃物、 手工具又は一 般金物製造業 及び(55)めつ き業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5401',
                'detail_content1'  => '金属製品製造業又は金属加工業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '63',
                'industry_type'  => '泛食器、刃物、 手工具又は一 般金物製造業 ((55)めつき 業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6301',
                'detail_content1'  => '泛食器、刃物、手工具又は一般金物製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '55',
                'industry_type'  => 'めつき業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5501',
                'detail_content1'  => 'めつき業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '56',
                'industry_type'  => '機械器具製造 業((57)電気 機械器具製造 業、(58)輸送 用機械器具製 造業、(59)船 舶製造又は修 理業及び（60) 計量器、光学 機械、時計等 製 造 業 を 除 く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5601',
                'detail_content1'  => '機械器具製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '57',
                'industry_type'  => '電気機械器具 製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5701',
                'detail_content1'  => '電気機械器具製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '58',
                'industry_type'  => '輸 送 用 機 械 器 具 製 造 業((59)船舶製造又は修理業 を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5801',
                'detail_content1'  => '輸送用機械器具製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '59',
                'industry_type'  => '船舶製造又は 修理業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '5901',
                'detail_content1'  => '船舶製造又は修理業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '60',
                'industry_type'  => '計量器、光学 機械、時計等 製造業((57) 電気機械器具 製 造 業 を 除 く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6001',
                'detail_content1'  => '計量器、光学機械、時計等製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '64',
                'industry_type'  => '貴金属製品、 装身具、皮革 製品等製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6401',
                'detail_content1'  => '貴金属製品、装身具、皮革製品等製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6102',
                'detail_content1'  => 'ペン、ペンシルその他の事務用品又は絵画用品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6104',
                'detail_content1'  => '可塑物製品製造業(購入材料によるものに限る。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6105',
                'detail_content1'  => '漆器製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6107',
                'detail_content1'  => '加工紙、紙製品、紙製容器又は紙加工品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6108',
                'detail_content1'  => '竹、籐又はきりゆう製品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6109',
                'detail_content1'  => 'わら類製品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6110',
                'detail_content1'  => 'くずゴム製品製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6115',
                'detail_content1'  => '塗装業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '製造業',
                'industry_type_no'  => '61',
                'industry_type'  => 'その他の製造業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '6116',
                'detail_content1'  => 'その他の各種製造業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '71',
                'industry_type'  => '交通運輸事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7101',
                'detail_content1'  => '鉄道、軌道又は索道による旅客又は貨物の運送事業((7202)貨物の積みおろし又は集郤を伴う貨物の運送事業を除く。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '71',
                'industry_type'  => '交通運輸事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7102',
                'detail_content1'  => '自動車又は軽車両による旅客の運送事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '71',
                'industry_type'  => '交通運輸事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7104',
                'detail_content1'  => '航空機による旅客又は貨物の運送事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '71',
                'industry_type'  => '交通運輸事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7105',
                'detail_content1'  => '船舶による旅客の運送事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '71',
                'industry_type'  => '交通運輸事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7103',
                'detail_content1'  => '自動車、航空機等を使用して宣伝、広告、測量等を行なう事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '71',
                'industry_type'  => '交通運輸事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7106',
                'detail_content1'  => 'その他の交通運輸事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '72',
                'industry_type'  => '貨物取扱事業((73)港湾貨物取扱事業及び(74)港湾荷役業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7201',
                'detail_content1'  => '停車場、倉庫、工場、道路等における貨物取扱いの事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '72',
                'industry_type'  => '貨物取扱事業((73)港湾貨物取扱事業及び(74)港湾荷役業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7202',
                'detail_content1'  => '貨物の積みおろし又は集郤を伴う鉄道軌道又は索道による貨物の運送事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '72',
                'industry_type'  => '貨物取扱事業((73)港湾貨物取扱事業及び(74)港湾荷役業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7203',
                'detail_content1'  => '自動車又は軽車両による貨物の運送事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '72',
                'industry_type'  => '貨物取扱事業((73)港湾貨物取扱事業及び(74)港湾荷役業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7206',
                'detail_content1'  => '船舶による貨物の運送事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '72',
                'industry_type'  => '貨物取扱事業((73)港湾貨物取扱事業及び(74)港湾荷役業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7204',
                'detail_content1'  => '貨物の荷造り又はこん包の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '72',
                'industry_type'  => '貨物取扱事業((73)港湾貨物取扱事業及び(74)港湾荷役業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7205',
                'detail_content1'  => '自動車により砂利その他の土石を運搬して販売する事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '73',
                'industry_type'  => '港湾貨物取扱事業((74)港湾荷役業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7301',
                'detail_content1'  => '港湾の上屋、倉庫等における貨物取扱いの事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '一貫して(74)港湾荷役業を行うものを除く。',
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '73',
                'industry_type'  => '港湾貨物取扱事業((74)港湾荷役業を除く。）',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7302',
                'detail_content1'  => 'はしけ又は引船による貨物の運送事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '一貫して(74)港湾荷役業を行うものを除く。',
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '74',
                'industry_type'  => '港湾荷役業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7401',
                'detail_content1'  => '沫岸において船舶に荷を積み又は船舶から荷をおろすために貨物を取り扱う事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '一貫して行う(73)港湾貨物取扱事業を含む。',
            ],
            [
                'industry_classification'   => '運輸業',
                'industry_type_no'  => '74',
                'industry_type'  => '港湾荷役業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '7402',
                'detail_content1'  => '船舶内において船舶に荷を積み又は船舶から荷をおろすために貨物を取り扱う事業（一貫して行う(7401)沫岸において船舶に荷を積み又は船舶から荷をおろすために貨物を取り扱う事業を含む。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => '一貫して行う(73)港湾貨物取扱事業を含む。',
            ],
            [
                'industry_classification'   => '電気、ガス、水道又は熱供給の事業',
                'industry_type_no'  => '81',
                'industry_type'  => '電気、ガス、水道又は熱供給の事業',
                'detail_alphabet'  => 'Ａ',
                'detail_summary'  => '電気業',
                'detail_no'  => '8101',
                'detail_content1'  => '発電、送電、変電又は郤電の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '電気、ガス、水道又は熱供給の事業',
                'industry_type_no'  => '81',
                'industry_type'  => '電気、ガス、水道又は熱供給の事業',
                'detail_alphabet'  => 'Ｂ',
                'detail_summary'  => 'ガス業',
                'detail_no'  => '8102',
                'detail_content1'  => '天然ガスの採取供給又はガスの製造供給の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '電気、ガス、水道又は熱供給の事業',
                'industry_type_no'  => '81',
                'industry_type'  => '電気、ガス、水道又は熱供給の事業',
                'detail_alphabet'  => 'Ｂ',
                'detail_summary'  => 'ガス業',
                'detail_no'  => '8103',
                'detail_content1'  => '天然ガス又はガスの供給の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '電気、ガス、水道又は熱供給の事業',
                'industry_type_no'  => '81',
                'industry_type'  => '電気、ガス、水道又は熱供給の事業',
                'detail_alphabet'  => 'Ｃ',
                'detail_summary'  => '水道業',
                'detail_no'  => '8104',
                'detail_content1'  => '上水道業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '電気、ガス、水道又は熱供給の事業',
                'industry_type_no'  => '81',
                'industry_type'  => '電気、ガス、水道又は熱供給の事業',
                'detail_alphabet'  => 'Ｃ',
                'detail_summary'  => '水道業',
                'detail_no'  => '8105',
                'detail_content1'  => '下水道業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => '電気、ガス、水道又は熱供給の事業',
                'industry_type_no'  => '81',
                'industry_type'  => '電気、ガス、水道又は熱供給の事業',
                'detail_alphabet'  => 'Ｄ',
                'detail_summary'  => '熱供給業',
                'detail_no'  => '8106',
                'detail_content1'  => '熱供給業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '95',
                'industry_type'  => '農業又は海面漁業以外の漁業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9501',
                'detail_content1'  => '土地の耕作又は植物の栽植、栽培若しくは採取の事業その他の農業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '95',
                'industry_type'  => '農業又は海面漁業以外の漁業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9502',
                'detail_content1'  => '動物の飼育若しくは畜産の事業又は養蚕の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '95',
                'industry_type'  => '農業又は海面漁業以外の漁業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9503',
                'detail_content1'  => '水産動植物の採捕又は養殖の事業((11)海面漁業及び(12)定置網漁業又は海面魚類養殖業を除く。）',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '91',
                'industry_type'  => '浴掃、火葬又はと畜の事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9101',
                'detail_content1'  => '浴掃業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '91',
                'industry_type'  => '浴掃、火葬又はと畜の事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9102',
                'detail_content1'  => '火葬業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '91',
                'industry_type'  => '浴掃、火葬又はと畜の事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9103',
                'detail_content1'  => 'と畜業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '93',
                'industry_type'  => 'ビルメンテナ ンス業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9301',
                'detail_content1'  => 'ビルの総合的な管理等の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '96',
                'industry_type'  => '倉庫業、警備業、消毒又は害虫駆除の事業又はゴルフ場の事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9601',
                'detail_content1'  => '倉庫業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '96',
                'industry_type'  => '倉庫業、警備業、消毒又は害虫駆除の事業又はゴルフ場の事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9602',
                'detail_content1'  => '警備業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '96',
                'industry_type'  => '倉庫業、警備業、消毒又は害虫駆除の事業又はゴルフ場の事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9603',
                'detail_content1'  => '消毒又は害虫駆除の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '96',
                'industry_type'  => '倉庫業、警備業、消毒又は害虫駆除の事業又はゴルフ場の事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9606',
                'detail_content1'  => 'ゴルフ場の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '97',
                'industry_type'  => '通信業、放送業、新聞業又は出版業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9701',
                'detail_content1'  => '通信業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '97',
                'industry_type'  => '通信業、放送業、新聞業又は出版業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9702',
                'detail_content1'  => '放送業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '97',
                'industry_type'  => '通信業、放送業、新聞業又は出版業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9703',
                'detail_content1'  => '新聞業又は出版業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '98',
                'industry_type'  => '卸売業・小売業、飲食店又は宿沲業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9801',
                'detail_content1'  => '卸売業・小売業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '98',
                'industry_type'  => '卸売業・小売業、飲食店又は宿沲業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9802',
                'detail_content1'  => '飲食店',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '98',
                'industry_type'  => '卸売業・小売業、飲食店又は宿沲業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9803',
                'detail_content1'  => '宿沲業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '99',
                'industry_type'  => '金融業、保険業又は不動産業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9901',
                'detail_content1'  => '金融業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '99',
                'industry_type'  => '金融業、保険業又は不動産業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9902',
                'detail_content1'  => '保険業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '99',
                'industry_type'  => '金融業、保険業又は不動産業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9903',
                'detail_content1'  => '不動産業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9411',
                'detail_content1'  => '広告、興信、紹介又は案内の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9412',
                'detail_content1'  => '速記、筆耕、謄写印刷又は青写真業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9418',
                'detail_content1'  => '映画の製作、演劇等の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9419',
                'detail_content1'  => '劇場、逿戯場その他の娯楽の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9420',
                'detail_content1'  => '波たく、波張又は染物の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9421',
                'detail_content1'  => '理容、美容又は洗場の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9422',
                'detail_content1'  => '物品賃貸業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9423',
                'detail_content1'  => '写真、物品預り等の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9425',
                'detail_content1'  => '教育業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9426',
                'detail_content1'  => '研究又は調査の事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9431',
                'detail_content1'  => '医療業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9432',
                'detail_content1'  => '社会福祉又は介護事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9433',
                'detail_content1'  => '幼稚園',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9434',
                'detail_content1'  => '保育所',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9435',
                'detail_content1'  => '認定こども園',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9436',
                'detail_content1'  => '情報サービス業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
            [
                'industry_classification'   => 'その他の事業',
                'industry_type_no'  => '94',
                'industry_type'  => 'その他の各種事業',
                'detail_alphabet'  => null,
                'detail_summary'  => null,
                'detail_no'  => '9416',
                'detail_content1'  => '前各項に該当しない事業',
                'detail_kana'  => null,
                'detail_content2'  => null,
                'remarks'  => null,
            ],
        ]);
    }
}
