<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_country')->truncate();
        DB::table('m_country')->insert([
            [
                'country_code'   => 'IS',
                'country_name'  => 'アイスランド',
                'country_name_en'  => 'Republic of Iceland',
                'setting_value'  => '352',
            ],
            [
                'country_code'   => 'IE',
                'country_name'  => 'アイルランド',
                'country_name_en'  => 'Ireland',
                'setting_value'  => '372',
            ],
            [
                'country_code'   => 'AZ',
                'country_name'  => 'アゼルバイジャン',
                'country_name_en'  => 'Republic of Azerbaijan',
                'setting_value'  => '031',
            ],
            [
                'country_code'   => 'AF',
                'country_name'  => 'アフガニスタン',
                'country_name_en'  => 'Islamic Republic of Afghanistan',
                'setting_value'  => '004',
            ],
            [
                'country_code'   => 'US',
                'country_name'  => 'アメリカ合衆国',
                'country_name_en'  => 'United States of America',
                'setting_value'  => '840',
            ],
            [
                'country_code'   => 'AE',
                'country_name'  => 'アラブ首長国連邦',
                'country_name_en'  => 'United Arab Emirates',
                'setting_value'  => '784',
            ],
            [
                'country_code'   => 'DZ',
                'country_name'  => 'アルジェリア',
                'country_name_en'  => 'People\'s Democratic Republic of Algeria',
                'setting_value'  => '012',
            ],
            [
                'country_code'   => 'AR',
                'country_name'  => 'アルゼンチン',
                'country_name_en'  => 'Argentine Republic',
                'setting_value'  => '032',
            ],
            [
                'country_code'   => 'AW',
                'country_name'  => 'アルバ',
                'country_name_en'  => 'Aruba',
                'setting_value'  => '533',
            ],
            [
                'country_code'   => 'AL',
                'country_name'  => 'アルバニア',
                'country_name_en'  => 'Republic of Albania',
                'setting_value'  => '008',
            ],
            [
                'country_code'   => 'AM',
                'country_name'  => 'アルメニア',
                'country_name_en'  => 'Republic of Armenia',
                'setting_value'  => '051',
            ],
            [
                'country_code'   => 'AI',
                'country_name'  => 'アンギラ',
                'country_name_en'  => 'Anguilla',
                'setting_value'  => '660',
            ],
            [
                'country_code'   => 'AO',
                'country_name'  => 'アンゴラ',
                'country_name_en'  => 'Republic of Angola',
                'setting_value'  => '024',
            ],
            [
                'country_code'   => 'AG',
                'country_name'  => 'アンティグア・バーブーダ',
                'country_name_en'  => 'Antigua and Barbuda',
                'setting_value'  => '028',
            ],
            [
                'country_code'   => 'AD',
                'country_name'  => 'アンドラ',
                'country_name_en'  => 'Principality of Andorra',
                'setting_value'  => '020',
            ],
            [
                'country_code'   => 'YE',
                'country_name'  => 'イエメン',
                'country_name_en'  => 'Republic of Yemen',
                'setting_value'  => '887',
            ],
            [
                'country_code'   => 'GB',
                'country_name'  => 'イギリス',
                'country_name_en'  => 'United Kingdom of Great Britain and Northern Ireland',
                'setting_value'  => '826',
            ],
            [
                'country_code'   => 'IL',
                'country_name'  => 'イスラエル',
                'country_name_en'  => 'State of Israel',
                'setting_value'  => '376',
            ],
            [
                'country_code'   => 'IT',
                'country_name'  => 'イタリア',
                'country_name_en'  => 'Italian Republic',
                'setting_value'  => '380',
            ],
            [
                'country_code'   => 'IQ',
                'country_name'  => 'イラク',
                'country_name_en'  => 'Republic of Iraq',
                'setting_value'  => '368',
            ],
            [
                'country_code'   => 'IR',
                'country_name'  => 'イラン・イスラム共和国',
                'country_name_en'  => 'Islamic Republic of Iran',
                'setting_value'  => '364',
            ],
            [
                'country_code'   => 'IN',
                'country_name'  => 'インド',
                'country_name_en'  => 'India',
                'setting_value'  => '356',
            ],
            [
                'country_code'   => 'ID',
                'country_name'  => 'インドネシア',
                'country_name_en'  => 'Republic of Indonesia',
                'setting_value'  => '360',
            ],
            [
                'country_code'   => 'UG',
                'country_name'  => 'ウガンダ',
                'country_name_en'  => 'Republic of Uganda',
                'setting_value'  => '800',
            ],
            [
                'country_code'   => 'UA',
                'country_name'  => 'ウクライナ',
                'country_name_en'  => 'Ukraine',
                'setting_value'  => '804',
            ],
            [
                'country_code'   => 'UZ',
                'country_name'  => 'ウズベキスタン',
                'country_name_en'  => 'Republic of Uzbekistan',
                'setting_value'  => '860',
            ],
            [
                'country_code'   => 'UY',
                'country_name'  => 'ウルグアイ',
                'country_name_en'  => 'Oriental Republic of Uruguay',
                'setting_value'  => '858',
            ],
            [
                'country_code'   => 'EC',
                'country_name'  => 'エクアドル',
                'country_name_en'  => 'Republic of Ecuador',
                'setting_value'  => '218',
            ],
            [
                'country_code'   => 'EG',
                'country_name'  => 'エジプト',
                'country_name_en'  => 'Arab Republic of Egypt',
                'setting_value'  => '818',
            ],
            [
                'country_code'   => 'EE',
                'country_name'  => 'エストニア',
                'country_name_en'  => 'Republic of Estonia',
                'setting_value'  => '233',
            ],
            [
                'country_code'   => 'ET',
                'country_name'  => 'エチオピア',
                'country_name_en'  => 'Federal Democratic Republic of Ethiopia',
                'setting_value'  => '231',
            ],
            [
                'country_code'   => 'ER',
                'country_name'  => 'エリトリア',
                'country_name_en'  => 'State of Eritrea',
                'setting_value'  => '232',
            ],
            [
                'country_code'   => 'SV',
                'country_name'  => 'エルサルバドル',
                'country_name_en'  => 'Republic of El Salvador',
                'setting_value'  => '222',
            ],
            [
                'country_code'   => 'AU',
                'country_name'  => 'オーストラリア',
                'country_name_en'  => 'Australia',
                'setting_value'  => '036',
            ],
            [
                'country_code'   => 'AT',
                'country_name'  => 'オーストリア',
                'country_name_en'  => 'Republic of Austria',
                'setting_value'  => '040',
            ],
            [
                'country_code'   => 'OM',
                'country_name'  => 'オマーン',
                'country_name_en'  => 'Sultanate of Oman',
                'setting_value'  => '512',
            ],
            [
                'country_code'   => 'NL',
                'country_name'  => 'オランダ',
                'country_name_en'  => 'Kingdom of the Netherlands',
                'setting_value'  => '528',
            ],
            [
                'country_code'   => 'GH',
                'country_name'  => 'ガーナ',
                'country_name_en'  => 'Republic of Ghana',
                'setting_value'  => '288',
            ],
            [
                'country_code'   => 'CV',
                'country_name'  => 'カーボベルデ',
                'country_name_en'  => 'Republic of Cabo Verde',
                'setting_value'  => '132',
            ],
            [
                'country_code'   => 'GG',
                'country_name'  => 'ガーンジー',
                'country_name_en'  => 'Guernsey',
                'setting_value'  => '831',
            ],
            [
                'country_code'   => 'GY',
                'country_name'  => 'ガイアナ',
                'country_name_en'  => 'Republic of Guyana',
                'setting_value'  => '328',
            ],
            [
                'country_code'   => 'KZ',
                'country_name'  => 'カザフスタン',
                'country_name_en'  => 'Republic of Kazakhstan',
                'setting_value'  => '398',
            ],
            [
                'country_code'   => 'QA',
                'country_name'  => 'カタール',
                'country_name_en'  => 'State of Qatar',
                'setting_value'  => '634',
            ],
            [
                'country_code'   => 'CA',
                'country_name'  => 'カナダ',
                'country_name_en'  => 'Canada',
                'setting_value'  => '124',
            ],
            [
                'country_code'   => 'GA',
                'country_name'  => 'ガボン',
                'country_name_en'  => 'Gabonese Republic',
                'setting_value'  => '266',
            ],
            [
                'country_code'   => 'CM',
                'country_name'  => 'カメルーン',
                'country_name_en'  => 'Republic of Cameroon',
                'setting_value'  => '120',
            ],
            [
                'country_code'   => 'GM',
                'country_name'  => 'ガンビア',
                'country_name_en'  => 'Republic of The Gambia',
                'setting_value'  => '270',
            ],
            [
                'country_code'   => 'KH',
                'country_name'  => 'カンボジア',
                'country_name_en'  => 'Kingdom of Cambodia',
                'setting_value'  => '116',
            ],
            [
                'country_code'   => 'GN',
                'country_name'  => 'ギニア',
                'country_name_en'  => 'Republic of Guinea',
                'setting_value'  => '324',
            ],
            [
                'country_code'   => 'GW',
                'country_name'  => 'ギニアビサウ',
                'country_name_en'  => 'Republic of Guinea-Bissau',
                'setting_value'  => '624',
            ],
            [
                'country_code'   => 'CY',
                'country_name'  => 'キプロス',
                'country_name_en'  => 'Republic of Cyprus',
                'setting_value'  => '196',
            ],
            [
                'country_code'   => 'CU',
                'country_name'  => 'キューバ',
                'country_name_en'  => 'Republic of Cuba',
                'setting_value'  => '192',
            ],
            [
                'country_code'   => 'GR',
                'country_name'  => 'ギリシャ',
                'country_name_en'  => 'Hellenic Republic',
                'setting_value'  => '300',
            ],
            [
                'country_code'   => 'KI',
                'country_name'  => 'キリバス',
                'country_name_en'  => 'Republic of Kiribati',
                'setting_value'  => '296',
            ],
            [
                'country_code'   => 'KG',
                'country_name'  => 'キルギス',
                'country_name_en'  => 'Kyrgyz Republic',
                'setting_value'  => '417',
            ],
            [
                'country_code'   => 'GT',
                'country_name'  => 'グアテマラ',
                'country_name_en'  => 'Republic of Guatemala',
                'setting_value'  => '320',
            ],
            [
                'country_code'   => 'KW',
                'country_name'  => 'クウェート',
                'country_name_en'  => 'State of Kuwait',
                'setting_value'  => '414',
            ],
            [
                'country_code'   => 'CK',
                'country_name'  => 'クック諸島',
                'country_name_en'  => 'Cook Islands',
                'setting_value'  => '184',
            ],
            [
                'country_code'   => 'GD',
                'country_name'  => 'グレナダ',
                'country_name_en'  => 'Grenada',
                'setting_value'  => '308',
            ],
            [
                'country_code'   => 'HR',
                'country_name'  => 'クロアチア',
                'country_name_en'  => 'Republic of Croatia',
                'setting_value'  => '191',
            ],
            [
                'country_code'   => 'KE',
                'country_name'  => 'ケニア',
                'country_name_en'  => 'Republic of Kenya',
                'setting_value'  => '404',
            ],
            [
                'country_code'   => 'CI',
                'country_name'  => 'コートジボワール',
                'country_name_en'  => 'Republic of Cote d\'Ivoire',
                'setting_value'  => '384',
            ],
            [
                'country_code'   => 'CR',
                'country_name'  => 'コスタリカ',
                'country_name_en'  => 'Republic of Costa Rica',
                'setting_value'  => '188',
            ],
            [
                'country_code'   => 'KM',
                'country_name'  => 'コモロ',
                'country_name_en'  => 'Union of Comoros',
                'setting_value'  => '174',
            ],
            [
                'country_code'   => 'CO',
                'country_name'  => 'コロンビア',
                'country_name_en'  => 'Republic of Colombia',
                'setting_value'  => '170',
            ],
            [
                'country_code'   => 'CG',
                'country_name'  => 'コンゴ共和国',
                'country_name_en'  => 'Republic of Congo',
                'setting_value'  => '178',
            ],
            [
                'country_code'   => 'CD',
                'country_name'  => 'コンゴ民主共和国',
                'country_name_en'  => 'Democratic Republic of the Congo',
                'setting_value'  => '180',
            ],
            [
                'country_code'   => 'SA',
                'country_name'  => 'サウジアラビア',
                'country_name_en'  => 'Kingdom of Saudi Arabia',
                'setting_value'  => '682',
            ],
            [
                'country_code'   => 'WS',
                'country_name'  => 'サモア',
                'country_name_en'  => 'Independent State of Samoa',
                'setting_value'  => '882',
            ],
            [
                'country_code'   => 'ST',
                'country_name'  => 'サントメ・プリンシペ',
                'country_name_en'  => 'Democratic Republic of Sao Tome and Principe',
                'setting_value'  => '678',
            ],
            [
                'country_code'   => 'ZM',
                'country_name'  => 'ザンビア',
                'country_name_en'  => 'Republic of Zambia',
                'setting_value'  => '894',
            ],
            [
                'country_code'   => 'SM',
                'country_name'  => 'サンマリノ',
                'country_name_en'  => 'Republic of San Marino',
                'setting_value'  => '674',
            ],
            [
                'country_code'   => 'SL',
                'country_name'  => 'シエラレオネ',
                'country_name_en'  => 'Republic of Sierra Leone',
                'setting_value'  => '694',
            ],
            [
                'country_code'   => 'DJ',
                'country_name'  => 'ジブチ',
                'country_name_en'  => 'Republic of Djibouti',
                'setting_value'  => '262',
            ],
            [
                'country_code'   => 'JE',
                'country_name'  => 'ジャージー',
                'country_name_en'  => 'Jersey',
                'setting_value'  => '832',
            ],
            [
                'country_code'   => 'JM',
                'country_name'  => 'ジャマイカ',
                'country_name_en'  => 'Jamaica',
                'setting_value'  => '388',
            ],
            [
                'country_code'   => 'GE',
                'country_name'  => 'ジョージア',
                'country_name_en'  => 'Georgia',
                'setting_value'  => '268',
            ],
            [
                'country_code'   => 'SY',
                'country_name'  => 'シリア・アラブ共和国',
                'country_name_en'  => 'Syrian Arab Republic',
                'setting_value'  => '760',
            ],
            [
                'country_code'   => 'SG',
                'country_name'  => 'シンガポール',
                'country_name_en'  => 'Republic of Singapore',
                'setting_value'  => '702',
            ],
            [
                'country_code'   => 'ZW',
                'country_name'  => 'ジンバブエ',
                'country_name_en'  => 'Republic of Zimbabwe',
                'setting_value'  => '716',
            ],
            [
                'country_code'   => 'CH',
                'country_name'  => 'スイス',
                'country_name_en'  => 'Swiss Confederation',
                'setting_value'  => '756',
            ],
            [
                'country_code'   => 'SE',
                'country_name'  => 'スウェーデン',
                'country_name_en'  => 'Kingdom of Sweden',
                'setting_value'  => '752',
            ],
            [
                'country_code'   => 'SD',
                'country_name'  => 'スーダン',
                'country_name_en'  => 'The Republic of the Sudan',
                'setting_value'  => '729',
            ],
            [
                'country_code'   => 'ES',
                'country_name'  => 'スペイン',
                'country_name_en'  => 'Kingdom of Spain',
                'setting_value'  => '724',
            ],
            [
                'country_code'   => 'SR',
                'country_name'  => 'スリナム',
                'country_name_en'  => 'Republic of Suriname',
                'setting_value'  => '740',
            ],
            [
                'country_code'   => 'LK',
                'country_name'  => 'スリランカ',
                'country_name_en'  => 'Democratic Socialist Republic of Sri Lanka',
                'setting_value'  => '144',
            ],
            [
                'country_code'   => 'SK',
                'country_name'  => 'スロバキア',
                'country_name_en'  => 'Slovak Republic',
                'setting_value'  => '703',
            ],
            [
                'country_code'   => 'SI',
                'country_name'  => 'スロベニア',
                'country_name_en'  => 'Republic of Slovenia',
                'setting_value'  => '705',
            ],
            [
                'country_code'   => 'SZ',
                'country_name'  => 'スワジランド',
                'country_name_en'  => 'Swaziland',
                'setting_value'  => '748',
            ],
            [
                'country_code'   => 'SC',
                'country_name'  => 'セーシェル',
                'country_name_en'  => 'Republic of Seychelles',
                'setting_value'  => '690',
            ],
            [
                'country_code'   => 'GQ',
                'country_name'  => '赤道ギニア',
                'country_name_en'  => 'Republic of Equatorial Guinea',
                'setting_value'  => '226',
            ],
            [
                'country_code'   => 'SN',
                'country_name'  => 'セネガル',
                'country_name_en'  => 'Republic of Senegal',
                'setting_value'  => '686',
            ],
            [
                'country_code'   => 'RS',
                'country_name'  => 'セルビア',
                'country_name_en'  => 'Republic of Serbia',
                'setting_value'  => '688',
            ],
            [
                'country_code'   => 'KN',
                'country_name'  => 'セントクリストファー・ネービス',
                'country_name_en'  => 'Saint Christopher and Nevis',
                'setting_value'  => '659',
            ],
            [
                'country_code'   => 'VC',
                'country_name'  => 'セントビンセントおよびグレナディーン諸島',
                'country_name_en'  => 'Saint Vincent and the Grenadines',
                'setting_value'  => '670',
            ],
            [
                'country_code'   => 'LC',
                'country_name'  => 'セントルシア',
                'country_name_en'  => 'Saint Lucia',
                'setting_value'  => '662',
            ],
            [
                'country_code'   => 'SO',
                'country_name'  => 'ソマリア',
                'country_name_en'  => 'Federal Republic of Somalia',
                'setting_value'  => '706',
            ],
            [
                'country_code'   => 'SB',
                'country_name'  => 'ソロモン諸島',
                'country_name_en'  => 'Solomon Islands',
                'setting_value'  => '090',
            ],
            [
                'country_code'   => 'TH',
                'country_name'  => 'タイ',
                'country_name_en'  => 'Kingdom of Thailand',
                'setting_value'  => '764',
            ],
            [
                'country_code'   => 'KR',
                'country_name'  => '大韓民国',
                'country_name_en'  => 'Republic of Korea',
                'setting_value'  => '410',
            ],
            [
                'country_code'   => 'TW',
                'country_name'  => '台湾（台湾省/中華民国）',
                'country_name_en'  => 'Taiwan',
                'setting_value'  => '158',
            ],
            [
                'country_code'   => 'TJ',
                'country_name'  => 'タジキスタン',
                'country_name_en'  => 'Republic of Tajikistan',
                'setting_value'  => '762',
            ],
            [
                'country_code'   => 'TZ',
                'country_name'  => 'タンザニア',
                'country_name_en'  => 'United Republic of Tanzania',
                'setting_value'  => '834',
            ],
            [
                'country_code'   => 'CZ',
                'country_name'  => 'チェコ',
                'country_name_en'  => 'Czech Republic',
                'setting_value'  => '203',
            ],
            [
                'country_code'   => 'TD',
                'country_name'  => 'チャド',
                'country_name_en'  => 'Republic of Chad',
                'setting_value'  => '148',
            ],
            [
                'country_code'   => 'CF',
                'country_name'  => '中央アフリカ共和国',
                'country_name_en'  => 'Central African Republic',
                'setting_value'  => '140',
            ],
            [
                'country_code'   => 'CN',
                'country_name'  => '中華人民共和国',
                'country_name_en'  => 'People\'s Republic of China',
                'setting_value'  => '156',
            ],
            [
                'country_code'   => 'TN',
                'country_name'  => 'チュニジア',
                'country_name_en'  => 'Republic of Tunisia',
                'setting_value'  => '788',
            ],
            [
                'country_code'   => 'KP',
                'country_name'  => '朝鮮民主主義人民共和国',
                'country_name_en'  => 'Democratic People\'s Republic of Korea',
                'setting_value'  => '408',
            ],
            [
                'country_code'   => 'CL',
                'country_name'  => 'チリ',
                'country_name_en'  => 'Republic of Chile',
                'setting_value'  => '152',
            ],
            [
                'country_code'   => 'TV',
                'country_name'  => 'ツバル',
                'country_name_en'  => 'Tuvalu',
                'setting_value'  => '798',
            ],
            [
                'country_code'   => 'DK',
                'country_name'  => 'デンマーク',
                'country_name_en'  => 'Kingdom of Denmark',
                'setting_value'  => '208',
            ],
            [
                'country_code'   => 'DE',
                'country_name'  => 'ドイツ',
                'country_name_en'  => 'Federal Republic of Germany',
                'setting_value'  => '276',
            ],
            [
                'country_code'   => 'TG',
                'country_name'  => 'トーゴ',
                'country_name_en'  => 'Republic of Togo',
                'setting_value'  => '768',
            ],
            [
                'country_code'   => 'DO',
                'country_name'  => 'ドミニカ共和国',
                'country_name_en'  => 'Dominican Republic',
                'setting_value'  => '214',
            ],
            [
                'country_code'   => 'DM',
                'country_name'  => 'ドミニカ国',
                'country_name_en'  => 'Commonwealth of Dominica',
                'setting_value'  => '212',
            ],
            [
                'country_code'   => 'TT',
                'country_name'  => 'トリニダード・トバゴ',
                'country_name_en'  => 'Republic of Trinidad and Tobago',
                'setting_value'  => '780',
            ],
            [
                'country_code'   => 'TM',
                'country_name'  => 'トルクメニスタン',
                'country_name_en'  => 'Turkmenistan',
                'setting_value'  => '795',
            ],
            [
                'country_code'   => 'TR',
                'country_name'  => 'トルコ',
                'country_name_en'  => 'Republic of Turkey',
                'setting_value'  => '792',
            ],
            [
                'country_code'   => 'TO',
                'country_name'  => 'トンガ',
                'country_name_en'  => 'Kingdom of Tonga',
                'setting_value'  => '776',
            ],
            [
                'country_code'   => 'NG',
                'country_name'  => 'ナイジェリア',
                'country_name_en'  => 'Federal Republic of Nigeria',
                'setting_value'  => '566',
            ],
            [
                'country_code'   => 'NR',
                'country_name'  => 'ナウル',
                'country_name_en'  => 'Republic of Nauru',
                'setting_value'  => '520',
            ],
            [
                'country_code'   => 'NA',
                'country_name'  => 'ナミビア',
                'country_name_en'  => 'Republic of Namibia',
                'setting_value'  => '516',
            ],
            [
                'country_code'   => 'NU',
                'country_name'  => 'ニウエ',
                'country_name_en'  => 'Niue',
                'setting_value'  => '570',
            ],
            [
                'country_code'   => 'NI',
                'country_name'  => 'ニカラグア',
                'country_name_en'  => 'Republic of Nicaragua',
                'setting_value'  => '558',
            ],
            [
                'country_code'   => 'NE',
                'country_name'  => 'ニジェール',
                'country_name_en'  => 'Republic of Niger',
                'setting_value'  => '562',
            ],
            [
                'country_code'   => 'EH',
                'country_name'  => '西サハラ',
                'country_name_en'  => 'Western Sahara',
                'setting_value'  => '732',
            ],
            [
                'country_code'   => 'NZ',
                'country_name'  => 'ニュージーランド',
                'country_name_en'  => 'New Zealand',
                'setting_value'  => '554',
            ],
            [
                'country_code'   => 'NP',
                'country_name'  => 'ネパール',
                'country_name_en'  => 'Federal Democratic Republic of Nepal',
                'setting_value'  => '524',
            ],
            [
                'country_code'   => 'NO',
                'country_name'  => 'ノルウェー',
                'country_name_en'  => 'Kingdom of Norway',
                'setting_value'  => '578',
            ],
            [
                'country_code'   => 'BH',
                'country_name'  => 'バーレーン',
                'country_name_en'  => 'Kingdom of Bahrain',
                'setting_value'  => '048',
            ],
            [
                'country_code'   => 'HT',
                'country_name'  => 'ハイチ',
                'country_name_en'  => 'Republic of Haiti',
                'setting_value'  => '332',
            ],
            [
                'country_code'   => 'PK',
                'country_name'  => 'パキスタン',
                'country_name_en'  => 'Islamic Republic of Pakistan',
                'setting_value'  => '586',
            ],
            [
                'country_code'   => 'VA',
                'country_name'  => 'バチカン市国',
                'country_name_en'  => 'Vatican',
                'setting_value'  => '336',
            ],
            [
                'country_code'   => 'PA',
                'country_name'  => 'パナマ',
                'country_name_en'  => 'Republic of Panama',
                'setting_value'  => '591',
            ],
            [
                'country_code'   => 'VU',
                'country_name'  => 'バヌアツ',
                'country_name_en'  => 'Republic of Vanuatu',
                'setting_value'  => '548',
            ],
            [
                'country_code'   => 'BS',
                'country_name'  => 'バハマ',
                'country_name_en'  => 'Commonwealth of The Bahamas',
                'setting_value'  => '044',
            ],
            [
                'country_code'   => 'PG',
                'country_name'  => 'パプアニューギニア',
                'country_name_en'  => 'Independent State of Papua New Guinea',
                'setting_value'  => '598',
            ],
            [
                'country_code'   => 'PW',
                'country_name'  => 'パラオ',
                'country_name_en'  => 'Republic of Palau',
                'setting_value'  => '585',
            ],
            [
                'country_code'   => 'PY',
                'country_name'  => 'パラグアイ',
                'country_name_en'  => 'Republic of Paraguay',
                'setting_value'  => '600',
            ],
            [
                'country_code'   => 'BB',
                'country_name'  => 'バルバドス',
                'country_name_en'  => 'Barbados',
                'setting_value'  => '052',
            ],
            [
                'country_code'   => 'PS',
                'country_name'  => 'パレスチナ',
                'country_name_en'  => 'Palestine',
                'setting_value'  => '275',
            ],
            [
                'country_code'   => 'HU',
                'country_name'  => 'ハンガリー',
                'country_name_en'  => 'Hungary',
                'setting_value'  => '348',
            ],
            [
                'country_code'   => 'BD',
                'country_name'  => 'バングラデシュ',
                'country_name_en'  => 'People\'s Republic of Bangladesh',
                'setting_value'  => '050',
            ],
            [
                'country_code'   => 'TL',
                'country_name'  => '東ティモール',
                'country_name_en'  => 'The Democratic Republic of Timor-Leste',
                'setting_value'  => '626',
            ],
            [
                'country_code'   => 'FJ',
                'country_name'  => 'フィジー',
                'country_name_en'  => 'Republic of Fiji',
                'setting_value'  => '242',
            ],
            [
                'country_code'   => 'PH',
                'country_name'  => 'フィリピン',
                'country_name_en'  => 'Republic of the Philippines',
                'setting_value'  => '608',
            ],
            [
                'country_code'   => 'FI',
                'country_name'  => 'フィンランド',
                'country_name_en'  => 'Republic of Finland',
                'setting_value'  => '246',
            ],
            [
                'country_code'   => 'BT',
                'country_name'  => 'ブータン',
                'country_name_en'  => 'Kingdom of Bhutan',
                'setting_value'  => '064',
            ],
            [
                'country_code'   => 'BR',
                'country_name'  => 'ブラジル',
                'country_name_en'  => 'Federative Republic of Brazil',
                'setting_value'  => '076',
            ],
            [
                'country_code'   => 'FR',
                'country_name'  => 'フランス',
                'country_name_en'  => 'French Republic',
                'setting_value'  => '250',
            ],
            [
                'country_code'   => 'BG',
                'country_name'  => 'ブルガリア',
                'country_name_en'  => 'Republic of Bulgaria',
                'setting_value'  => '100',
            ],
            [
                'country_code'   => 'BF',
                'country_name'  => 'ブルキナファソ',
                'country_name_en'  => 'Burkina Faso',
                'setting_value'  => '854',
            ],
            [
                'country_code'   => 'BN',
                'country_name'  => 'ブルネイ・ダルサラーム',
                'country_name_en'  => 'Brunei Darussalam',
                'setting_value'  => '096',
            ],
            [
                'country_code'   => 'BI',
                'country_name'  => 'ブルンジ',
                'country_name_en'  => 'Republic of Burundi',
                'setting_value'  => '108',
            ],
            [
                'country_code'   => 'VN',
                'country_name'  => 'ベトナム',
                'country_name_en'  => 'Socialist Republic of Viet Nam',
                'setting_value'  => '704',
            ],
            [
                'country_code'   => 'BJ',
                'country_name'  => 'ベナン',
                'country_name_en'  => 'Republic of Benin',
                'setting_value'  => '204',
            ],
            [
                'country_code'   => 'VE',
                'country_name'  => 'ベネズエラ・ボリバル共和国',
                'country_name_en'  => 'Bolivarian Republic of Venezuela',
                'setting_value'  => '862',
            ],
            [
                'country_code'   => 'BY',
                'country_name'  => 'ベラルーシ',
                'country_name_en'  => 'Republic of Belarus',
                'setting_value'  => '112',
            ],
            [
                'country_code'   => 'BZ',
                'country_name'  => 'ベリーズ',
                'country_name_en'  => 'Belize',
                'setting_value'  => '084',
            ],
            [
                'country_code'   => 'PE',
                'country_name'  => 'ペルー',
                'country_name_en'  => 'Republic of Peru',
                'setting_value'  => '604',
            ],
            [
                'country_code'   => 'BE',
                'country_name'  => 'ベルギー',
                'country_name_en'  => 'Kingdom of Belgium',
                'setting_value'  => '056',
            ],
            [
                'country_code'   => 'PL',
                'country_name'  => 'ポーランド',
                'country_name_en'  => 'Republic of Poland',
                'setting_value'  => '616',
            ],
            [
                'country_code'   => 'BA',
                'country_name'  => 'ボスニア・ヘルツェゴビナ',
                'country_name_en'  => 'Bosnia and Herzegovina',
                'setting_value'  => '070',
            ],
            [
                'country_code'   => 'BW',
                'country_name'  => 'ボツワナ',
                'country_name_en'  => 'Republic of Botswana',
                'setting_value'  => '072',
            ],
            [
                'country_code'   => 'BO',
                'country_name'  => 'ボリビア多民族国',
                'country_name_en'  => 'Plurinational State of Bolivia',
                'setting_value'  => '068',
            ],
            [
                'country_code'   => 'PT',
                'country_name'  => 'ポルトガル',
                'country_name_en'  => 'Portuguese Republic',
                'setting_value'  => '620',
            ],
            [
                'country_code'   => 'HK',
                'country_name'  => '香港',
                'country_name_en'  => 'Hong Kong',
                'setting_value'  => '344',
            ],
            [
                'country_code'   => 'HN',
                'country_name'  => 'ホンジュラス',
                'country_name_en'  => 'Republic of Honduras',
                'setting_value'  => '340',
            ],
            [
                'country_code'   => 'MH',
                'country_name'  => 'マーシャル諸島',
                'country_name_en'  => 'Republic of the Marshall Islands',
                'setting_value'  => '584',
            ],
            [
                'country_code'   => 'MO',
                'country_name'  => 'マカオ',
                'country_name_en'  => 'Macau',
                'setting_value'  => '446',
            ],
            [
                'country_code'   => 'MK',
                'country_name'  => 'マケドニア旧ユーゴスラビア共和国',
                'country_name_en'  => 'The former Yugoslav Republic of Macedonia',
                'setting_value'  => '807',
            ],
            [
                'country_code'   => 'MG',
                'country_name'  => 'マダガスカル',
                'country_name_en'  => 'Republic of Madagascar',
                'setting_value'  => '450',
            ],
            [
                'country_code'   => 'MW',
                'country_name'  => 'マラウイ',
                'country_name_en'  => 'Republic of Malawi',
                'setting_value'  => '454',
            ],
            [
                'country_code'   => 'ML',
                'country_name'  => 'マリ',
                'country_name_en'  => 'Republic of Mali',
                'setting_value'  => '466',
            ],
            [
                'country_code'   => 'MT',
                'country_name'  => 'マルタ',
                'country_name_en'  => 'Republic of Malta',
                'setting_value'  => '470',
            ],
            [
                'country_code'   => 'MY',
                'country_name'  => 'マレーシア',
                'country_name_en'  => 'Malaysia',
                'setting_value'  => '458',
            ],
            [
                'country_code'   => 'IM',
                'country_name'  => 'マン島',
                'country_name_en'  => 'Isle of Man',
                'setting_value'  => '833',
            ],
            [
                'country_code'   => 'FM',
                'country_name'  => 'ミクロネシア連邦',
                'country_name_en'  => 'Federated States of Micronesia',
                'setting_value'  => '583',
            ],
            [
                'country_code'   => 'ZA',
                'country_name'  => '南アフリカ',
                'country_name_en'  => 'Republic of South Africa',
                'setting_value'  => '710',
            ],
            [
                'country_code'   => 'SS',
                'country_name'  => '南スーダン',
                'country_name_en'  => 'The Republic of South Sudan',
                'setting_value'  => '728',
            ],
            [
                'country_code'   => 'MM',
                'country_name'  => 'ミャンマー',
                'country_name_en'  => 'Republic of the Union of Myanmar',
                'setting_value'  => '104',
            ],
            [
                'country_code'   => 'MX',
                'country_name'  => 'メキシコ',
                'country_name_en'  => 'United Mexican States',
                'setting_value'  => '484',
            ],
            [
                'country_code'   => 'MU',
                'country_name'  => 'モーリシャス',
                'country_name_en'  => 'Republic of Mauritius',
                'setting_value'  => '480',
            ],
            [
                'country_code'   => 'MR',
                'country_name'  => 'モーリタニア',
                'country_name_en'  => 'Islamic Republic of Mauritania',
                'setting_value'  => '478',
            ],
            [
                'country_code'   => 'MZ',
                'country_name'  => 'モザンビーク',
                'country_name_en'  => 'Republic of Mozambique',
                'setting_value'  => '508',
            ],
            [
                'country_code'   => 'MC',
                'country_name'  => 'モナコ',
                'country_name_en'  => 'Principality of Monaco',
                'setting_value'  => '492',
            ],
            [
                'country_code'   => 'MV',
                'country_name'  => 'モルディブ',
                'country_name_en'  => 'Republic of Maldives',
                'setting_value'  => '462',
            ],
            [
                'country_code'   => 'MD',
                'country_name'  => 'モルドバ共和国',
                'country_name_en'  => 'Republic of Moldova',
                'setting_value'  => '498',
            ],
            [
                'country_code'   => 'MA',
                'country_name'  => 'モロッコ',
                'country_name_en'  => 'Kingdom of Morocco',
                'setting_value'  => '504',
            ],
            [
                'country_code'   => 'MN',
                'country_name'  => 'モンゴル',
                'country_name_en'  => 'Mongolia',
                'setting_value'  => '496',
            ],
            [
                'country_code'   => 'ME',
                'country_name'  => 'モンテネグロ',
                'country_name_en'  => 'Montenegro',
                'setting_value'  => '499',
            ],
            [
                'country_code'   => 'JO',
                'country_name'  => 'ヨルダン',
                'country_name_en'  => 'Jordan',
                'setting_value'  => '400',
            ],
            [
                'country_code'   => 'LA',
                'country_name'  => 'ラオス人民民主共和国',
                'country_name_en'  => 'Lao People\'s Democratic Republic',
                'setting_value'  => '418',
            ],
            [
                'country_code'   => 'LV',
                'country_name'  => 'ラトビア',
                'country_name_en'  => 'Republic of Latvia',
                'setting_value'  => '428',
            ],
            [
                'country_code'   => 'LT',
                'country_name'  => 'リトアニア',
                'country_name_en'  => 'Republic of Lithuania',
                'setting_value'  => '440',
            ],
            [
                'country_code'   => 'LY',
                'country_name'  => 'リビア',
                'country_name_en'  => 'Libya',
                'setting_value'  => '434',
            ],
            [
                'country_code'   => 'LI',
                'country_name'  => 'リヒテンシュタイン',
                'country_name_en'  => 'Principality of Liechtenstein',
                'setting_value'  => '438',
            ],
            [
                'country_code'   => 'LR',
                'country_name'  => 'リベリア',
                'country_name_en'  => 'Republic of Liberia',
                'setting_value'  => '430',
            ],
            [
                'country_code'   => 'RO',
                'country_name'  => 'ルーマニア',
                'country_name_en'  => 'Romania',
                'setting_value'  => '642',
            ],
            [
                'country_code'   => 'LU',
                'country_name'  => 'ルクセンブルク',
                'country_name_en'  => 'Grand Duchy of Luxembourg',
                'setting_value'  => '442',
            ],
            [
                'country_code'   => 'RW',
                'country_name'  => 'ルワンダ',
                'country_name_en'  => 'Republic of Rwanda',
                'setting_value'  => '646',
            ],
            [
                'country_code'   => 'LS',
                'country_name'  => 'レソト',
                'country_name_en'  => 'Kingdom of Lesotho',
                'setting_value'  => '426',
            ],
            [
                'country_code'   => 'LB',
                'country_name'  => 'レバノン',
                'country_name_en'  => 'Lebanese Republic',
                'setting_value'  => '422',
            ],
            [
                'country_code'   => 'RU',
                'country_name'  => 'ロシア連邦',
                'country_name_en'  => 'Russian Federation',
                'setting_value'  => '643',
            ],
            [
                'country_code'   => null,
                'country_name'  => '無国籍',
                'country_name_en'  => null,
                'setting_value'  => '998',
            ],
            [
                'country_code'   => null,
                'country_name'  => '不明',
                'country_name_en'  => null,
                'setting_value'  => '999',
            ],
        ]);
    }
}
