<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeColumnsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_employee_columns')->truncate();
        DB::table('m_employee_columns')->insert([
            ['key' => 'employee_no', 'name' => '従業員番号', 'type' => 'label'],
            ['key' => 'branch_name', 'name' => '所属事業所', 'type' => 'label'],
            ['key' => 'managerial_position_name', 'name' => '役職', 'type' => 'label'],
            ['key' => 'last_name', 'name' => '氏', 'type' => 'label'],
            ['key' => 'last_name_kana', 'name' => '氏（カナ）', 'type' => 'label'],
            ['key' => 'last_name_alphabet', 'name' => '氏（アルファベット）', 'type' => 'label'],
            ['key' => 'first_name', 'name' => '名', 'type' => 'label'],
            ['key' => 'first_name_kana', 'name' => '名（カナ）', 'type' => 'label'],
            ['key' => 'first_name_alphabet', 'name' => '名（アルファベット）', 'type' => 'label'],
            ['key' => 'old_last_name', 'name' => '旧氏', 'type' => 'label'],
            ['key' => 'old_last_name_kana', 'name' => '旧氏（カナ）', 'type' => 'label'],
            ['key' => 'old_last_name_alphabet', 'name' => '旧氏（アルファベット）', 'type' => 'label'],
            ['key' => 'old_first_name', 'name' => '旧名', 'type' => 'label'],
            ['key' => 'old_first_name_kana', 'name' => '旧名（カナ）', 'type' => 'label'],
            ['key' => 'old_first_name_alphabet', 'name' => '旧名（アルファベット）', 'type' => 'label'],
            ['key' => 'name_common', 'name' => '通称名', 'type' => 'label'],
            ['key' => 'name_common_kana', 'name' => '通称名（カナ）', 'type' => 'label'],
            ['key' => 'sex', 'name' => '性別', 'type' => 'label'],
            ['key' => 'birthday', 'name' => '生年月日', 'type' => 'label'],
            ['key' => 'post_code', 'name' => '郵便番号', 'type' => 'label'],
            ['key' => 'address_prefecture', 'name' => '住所（都道府県）', 'type' => 'label'],
            ['key' => 'address_city', 'name' => '住所（市区町村）', 'type' => 'label'],
            ['key' => 'address_ward', 'name' => '住所（丁目・番地）', 'type' => 'label'],
            ['key' => 'address_apartment', 'name' => '住所（アパート・マンション名等）', 'type' => 'label'],
            ['key' => 'address_city_kana', 'name' => '住所（市区町村）（カナ）', 'type' => 'label'],
            ['key' => 'address_ward_kana', 'name' => '住所（丁目・番地）（カナ）', 'type' => 'label'],
            ['key' => 'tel_area_code', 'name' => '連絡先電話番号（市外局番）', 'type' => 'label'],
            ['key' => 'tel_city_code', 'name' => '連絡先電話番号（市内局番）', 'type' => 'label'],
            ['key' => 'tel_subscriber_code', 'name' => '連絡先電話番号（加入者番号）', 'type' => 'label'],
            ['key' => 'fax1', 'name' => '連絡先FAX番号（市外局番）', 'type' => 'label'],
            ['key' => 'fax2', 'name' => '連絡先FAX番号（市内局番）', 'type' => 'label'],
            ['key' => 'fax3', 'name' => '連絡先FAX番号（加入者番号）', 'type' => 'label'],
            ['key' => 'mail_address1', 'name' => 'メールアドレス１', 'type' => 'label'],
            ['key' => 'mail_address2', 'name' => 'メールアドレス２', 'type' => 'label'],
            ['key' => 'emergency_post_code1', 'name' => '緊急連絡先郵便番号１', 'type' => 'label'],
            ['key' => 'emergency_contact1', 'name' => '緊急連絡先名１', 'type' => 'label'],
            ['key' => 'emergency_relationship1', 'name' => '緊急連絡先続柄１', 'type' => 'label'],
            ['key' => 'emergency_tel1', 'name' => '緊急連絡先電話番号１', 'type' => 'label'],
            ['key' => 'emergency_address_prefecture1', 'name' => '緊急連絡先住所（都道府県）１', 'type' => 'label'],
            ['key' => 'emergency_address_city1', 'name' => '緊急連絡先住所（市区町村）１', 'type' => 'label'],
            ['key' => 'emergency_address_ward1', 'name' => '緊急連絡先住所（丁目・番地）１', 'type' => 'label'],
            ['key' => 'emergency_address_apartment1', 'name' => '緊急連絡先住所（アパート・マンション名等）１', 'type' => 'label'],
            ['key' => 'emergency_post_code2', 'name' => '緊急連絡先郵便番号２', 'type' => 'label'],
            ['key' => 'emergency_contact2', 'name' => '緊急連絡先名２', 'type' => 'label'],
            ['key' => 'emergency_relationship2', 'name' => '緊急連絡先続柄２', 'type' => 'label'],
            ['key' => 'emergency_tel2', 'name' => '緊急連絡先電話番号２', 'type' => 'label'],
            ['key' => 'emergency_address_prefecture2', 'name' => '緊急連絡先住所（都道府県）２', 'type' => 'label'],
            ['key' => 'emergency_address_city2', 'name' => '緊急連絡先住所（市区町村）２', 'type' => 'label'],
            ['key' => 'emergency_address_ward2', 'name' => '緊急連絡先住所（丁目・番地）２', 'type' => 'label'],
            ['key' => 'emergency_address_apartment2', 'name' => '緊急連絡先住所（アパート・マンション名等）２', 'type' => 'label'],
            ['key' => 'country_id', 'name' => '国籍', 'type' => 'label'],
            ['key' => 'blood_type', 'name' => '血液型', 'type' => 'label'],
            ['key' => 'insured_age_type', 'name' => '取得時被保険者種類', 'type' => 'label'],
            ['key' => 'residence_card_no', 'name' => '在留カード番号', 'type' => 'label'],
            ['key' => 'stay_date_period', 'name' => '在留期間', 'type' => 'label'],
            ['key' => 'residential_status_id', 'name' => '在留資格', 'type' => 'label'],
            ['key' => 'residential_status_unknown_reason', 'name' => '在留資格不明理由', 'type' => 'label'],
            ['key' => 'unauthorized_activities_permission_flg', 'name' => '資格外許可の有無', 'type' => 'label'],
            ['key' => 'mynumber_card_no', 'name' => 'マイナンバーカード番号', 'type' => 'label'],
            ['key' => 'social_insurance_no', 'name' => '社会保険番号', 'type' => 'label'],
            ['key' => 'pension_office_no', 'name' => '事業所番号（厚生年金）', 'type' => 'label'],
            ['key' => 'pension_office_reference_prefecture', 'name' => '事業所整理記号（厚生年金）用の都道府県コード', 'type' => 'label'],
            ['key' => 'pension_office_reference_no_cities', 'name' => '事業所整理記号（厚生年金）郡市区記号', 'type' => 'label'],
            ['key' => 'pension_office_reference_no_office', 'name' => '事業所整理記号（厚生年金）事業所記号', 'type' => 'label'],
            ['key' => 'pension_no', 'name' => '基礎年金番号', 'type' => 'label'],
            ['key' => 'labor_insurance_type', 'name' => '労災保険区分', 'type' => 'label'],
            ['key' => 'employment_insurance_type', 'name' => '雇用保険区分', 'type' => 'label'],
            ['key' => 'insurance_office_no', 'name' => '事業所番号（保険）', 'type' => 'label'],
            ['key' => 'insurance_office_reference_no', 'name' => '事業所整理番号（保険）', 'type' => 'label'],
            ['key' => 'insurer_no', 'name' => '被保険者番号（健保）', 'type' => 'label'],
            ['key' => 'insurer_reference_no', 'name' => '被保険者整理番号', 'type' => 'label'],
            ['key' => 'employment_insurance_office_no', 'name' => '事業所番号（雇用保険）', 'type' => 'label'],
            ['key' => 'employment_insurance_applied_date', 'name' => '雇用保険届出日', 'type' => 'label'],
            ['key' => 'employment_insured_date', 'name' => '雇用保険取得日', 'type' => 'label'],
            ['key' => 'employment_insured_no', 'name' => '被保険者番号（雇用）', 'type' => 'label'],
            ['key' => 'employee_type', 'name' => '社員区分', 'type' => 'label'],
            ['key' => 'employee_status', 'name' => '雇用区分', 'type' => 'label'],
            ['key' => 'grade', 'name' => '等級', 'type' => 'label'],
            ['key' => 'work_category', 'name' => '勤務区分', 'type' => 'label'],
            ['key' => 'enrollment_category', 'name' => '在籍区分', 'type' => 'label'],
            ['key' => 'transfer_date', 'name' => '転勤・出向　年月日', 'type' => 'label'],
            ['key' => 'private_introduction', 'name' => '会社名（就職経路）', 'type' => 'label'],
            ['key' => 'recruitment_category', 'name' => '採用区分', 'type' => 'label'],
            ['key' => 'recruitment_category_detail', 'name' => '採用区分選択', 'type' => 'label'],
            ['key' => 'pay_type', 'name' => '給与区分', 'type' => 'label'],
            ['key' => 'contract_period_flg', 'name' => '雇用契約期間の有無', 'type' => 'label'],
            ['key' => 'contract_start_date', 'name' => '契約開始日', 'type' => 'label'],
            ['key' => 'contract_end_date', 'name' => '契約終了日', 'type' => 'label'],
            ['key' => 'contract_renewal_flg', 'name' => '契約更新条項の有無', 'type' => 'label'],
            ['key' => 'hired_date', 'name' => '入社日', 'type' => 'label'],
            ['key' => 'retirement_date', 'name' => '離職日', 'type' => 'label'],
            ['key' => 'intended_retirement_date', 'name' => '離職予定日', 'type' => 'label'],
            ['key' => 'resignation_letter_request_flg', 'name' => '離職票の交付希望の有無', 'type' => 'label'],
            ['key' => 'insurance_loss_reason', 'name' => '喪失原因', 'type' => 'label'],
            ['key' => 'over_retired_insurance_loss_reason', 'name' => '喪失原因（70歳以上）', 'type' => 'label'],
            ['key' => 'over_70_applicable_flg', 'name' => '70歳以上被用者該当フラグ', 'type' => 'label'],
            ['key' => 'over_70_non_applicable_date', 'name' => '70歳以上被用者不該当日', 'type' => 'label'],
            ['key' => 'passed_away_date', 'name' => '死亡日', 'type' => 'label'],
            ['key' => 'external_advisor_flg', 'name' => '外部顧問フラグ', 'type' => 'label'],
            ['key' => 'occupation_type', 'name' => '職種', 'type' => 'label'],
            ['key' => 'employment_route', 'name' => '就職経路', 'type' => 'label'],
            ['key' => 'bank_name', 'name' => '銀行名称', 'type' => 'label'],
            ['key' => 'bank_name_kana', 'name' => '銀行名称（カナ）', 'type' => 'label'],
            ['key' => 'head_office_or_branch_office', 'name' => '本店・支店フラグ', 'type' => 'label'],
            ['key' => 'financial_institution_code', 'name' => '金融機関コード', 'type' => 'label'],
            ['key' => 'store_code', 'name' => '店舗コード', 'type' => 'label'],
            ['key' => 'japan_bank_flg', 'name' => 'ゆうちょ銀行フラグ', 'type' => 'label'],
            ['key' => 'japan_post_bank_code_no', 'name' => 'ゆうちょ銀行記号番号', 'type' => 'label'],
            ['key' => 'bank_account_no', 'name' => '口座番号', 'type' => 'label'],
            ['key' => 'employment_status', 'name' => '雇用形態', 'type' => 'label'],
            ['key' => 'insured_status', 'name' => '被保険者状況', 'type' => 'label'],
            ['key' => 'health_insurance_association_number', 'name' => '健保組合番号', 'type' => 'label'],
            ['key' => 'acquisition_of_distinction', 'name' => '取得区分', 'type' => 'label'],
            ['key' => 'health_insurance_acquisition_date', 'name' => '健康保険取得日', 'type' => 'label'],
            ['key' => 'health_insurance_loss_date', 'name' => '健康保険喪失日', 'type' => 'label'],
            ['key' => 'welfare_pension', 'name' => '厚生年金基金', 'type' => 'label'],
            ['key' => 'overseas_special_exception', 'name' => '海外特例', 'type' => 'label'],
            ['key' => 'overseas_special_exception_date', 'name' => '海外特例該当日', 'type' => 'label'],
            ['key' => 'overseas_special_not_exception_date', 'name' => '海外特例非該当日', 'type' => 'label'],
            ['key' => 'dispatch_contract_completion', 'name' => '派遣請負修了区分', 'type' => 'label'],
            ['key' => 'employment_not_insured_date', 'name' => '雇用保険喪失日', 'type' => 'label'],
        ]);
    }
}
