<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HealthInsuranceAssociationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_health_insurance_association')->truncate();
        DB::table('m_health_insurance_association')->insert([
            [
                'post_code'  => '0018511',
                'address_prefecture'  => '北海道',
                'address_city'  => '札幌市北区',
                'address_more_details'  => '北10条西3－2３－１ THE　PEAK　SAPPORO',
                'tel'  => '0117260352',
                'fax'  => '0117260380',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/hokkaido/',
            ],
            [
                'post_code'  => '0308552',
                'address_prefecture'  => '青森県',
                'address_city'  => '青森市',
                'address_more_details'  => '長島２－２５－３ ニッセイ青森センタービル',
                'tel'  => '0177212799',
                'fax'  => '0177212668',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/aomori/',
            ],
            [
                'post_code'  => '0208508',
                'address_prefecture'  => '岩手県',
                'address_city'  => '盛岡市',
                'address_more_details'  => '中央通１－７－２５ 朝日生命盛岡中央通ビル',
                'tel'  => '0196049009',
                'fax'  => '0196049117',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/iwate/',
            ],
            [
                'post_code'  => '9808561',
                'address_prefecture'  => '宮城県',
                'address_city'  => '仙台市青葉区',
                'address_more_details'  => '国分町３－６－１ 仙台パークビル',
                'tel'  => '0227146850',
                'fax'  => '0227146857',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/miyagi/',
            ],
            [
                'post_code'  => '0108507',
                'address_prefecture'  => '秋田県',
                'address_city'  => '秋田市',
                'address_more_details'  => '旭北錦町5-50シティビル秋田2階',
                'tel'  => '0188831800',
                'fax'  => '0188831544',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/akita/',
            ],
            [
                'post_code'  => '9908587',
                'address_prefecture'  => '山形県',
                'address_city'  => '山形市',
                'address_more_details'  => '幸町１８－２０ ＪＡ山形市本店ビル',
                'tel'  => '0236297225',
                'fax'  => '0236297217',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/yamagata/',
            ],
            [
                'post_code'  => '9608546',
                'address_prefecture'  => '福島県',
                'address_city'  => '福島市',
                'address_more_details'  => '栄町６－６ ユニックスビル',
                'tel'  => '0245233915',
                'fax'  => '0245233841',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/fukushima/',
            ],
            [
                'post_code'  => '3108502',
                'address_prefecture'  => '茨城県',
                'address_city'  => '水戸市',
                'address_more_details'  => '南町３－４－５７ 水戸セントラルビル',
                'tel'  => '0293031500',
                'fax'  => '0293032100',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/ibaraki/',
            ],
            [
                'post_code'  => '3208514',
                'address_prefecture'  => '栃木県',
                'address_city'  => '宮市',
                'address_more_details'  => '宮市泉町6-20　宇都宮DIビル7階',
                'tel'  => '0286161691',
                'fax'  => '0286161535',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/tochigi/',
            ],
            [
                'post_code'  => '3718516',
                'address_prefecture'  => '群馬県',
                'address_city'  => '前橋市',
                'address_more_details'  => '本町２－２－１２ 前橋本町スクエアビル',
                'tel'  => '0272192100',
                'fax'  => '0272192106',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/gunma/',
            ],
            [
                'post_code'  => '3308686',
                'address_prefecture'  => '埼玉県',
                'address_city'  => 'さいたま市大宮区',
                'address_more_details'  => '錦町６８２－２ 大宮情報文化センター（ＪＡＣＫ大宮）１６階',
                'tel'  => '0486585919',
                'fax'  => '0486586061',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/saitama/',
            ],
            [
                'post_code'  => '2608645',
                'address_prefecture'  => '千葉県',
                'address_city'  => '千葉市中央区',
                'address_more_details'  => '新町3番地13　日本生命千葉駅前ビル2階',
                'tel'  => '0433828311',
                'fax'  => '0433828321',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/chiba/',
            ],
            [
                'post_code'  => '1648540',
                'address_prefecture'  => '東京都',
                'address_city'  => '中野区',
                'address_more_details'  => '中野４－１０－２　中野セントラルパークサウス',
                'tel'  => '0368536111',
                'fax'  => '0368536565',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/tokyo/',
            ],
            [
                'post_code'  => '2208538',
                'address_prefecture'  => '神奈川県',
                'address_city'  => '横浜市西区',
                'address_more_details'  => 'みなとみらい4丁目6番2号 みなとみらいグランドセントラルタワー9階',
                'tel'  => '0452708431',
                'fax'  => '0452733862',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/kanagawa/',
            ],
            [
                'post_code'  => '9508513',
                'address_prefecture'  => '新潟県',
                'address_city'  => '新潟市中央区',
                'address_more_details'  => '東大通2－4－4  日生不動産東大通ビル3階',
                'tel'  => '0252420260',
                'fax'  => '0252420280',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/niigata/',
            ],
            [
                'post_code'  => '9308561',
                'address_prefecture'  => '富山県',
                'address_city'  => '富山市',
                'address_more_details'  => '奥田新町８－１ ボルファートとやま',
                'tel'  => '0764316155',
                'fax'  => '0764316158',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/toyama/',
            ],
            [
                'post_code'  => '9208767',
                'address_prefecture'  => '石川県',
                'address_city'  => '金沢市',
                'address_more_details'  => '南町４－５５ WAKITA金沢ビル',
                'tel'  => '0762647200',
                'fax'  => '0762647206',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/ishikawa/',
            ],
            [
                'post_code'  => '9108541',
                'address_prefecture'  => '福井県',
                'address_city'  => '福井市',
                'address_more_details'  => '大手３－７－１ 福井県繊協ビル 9階',
                'tel'  => '0776278301',
                'fax'  => '0776278306',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/fukui/',
            ],
            [
                'post_code'  => '4008559',
                'address_prefecture'  => '山梨県',
                'address_city'  => '甲府市',
                'address_more_details'  => '丸の内３－３２－１２ 甲府ニッセイスカイビル',
                'tel'  => '0552207750',
                'fax'  => '0552207757',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/yamanashi/',
            ],
            [
                'post_code'  => '3808583',
                'address_prefecture'  => '長野県',
                'address_city'  => '長野市',
                'address_more_details'  => '南長野西後町１５９７－１ 長野朝日八十二ビル',
                'tel'  => '0262381250',
                'fax'  => '0262381257',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/nagano/',
            ],
            [
                'post_code'  => '5008667',
                'address_prefecture'  => '岐阜県',
                'address_city'  => '岐阜市',
                'address_more_details'  => '橋本町２－８ 濃飛ニッセイビル',
                'tel'  => '0582555155',
                'fax'  => '0582555165',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/gifu/',
            ],
            [
                'post_code'  => '4208512',
                'address_prefecture'  => '静岡県',
                'address_city'  => '静岡市葵区',
                'address_more_details'  => '呉服町1－1－2 静岡呉服町スクエア',
                'tel'  => '0542752770',
                'fax'  => '0542756609',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/shizuoka/',
            ],
            [
                'post_code'  => '4506363',
                'address_prefecture'  => '愛知県',
                'address_city'  => '名古屋市中村区',
                'address_more_details'  => '名駅１－１－１ JPタワー名古屋23階',
                'tel'  => '0528561490',
                'fax'  => '0528561491',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/aichi/',
            ],
            [
                'post_code'  => '5141195',
                'address_prefecture'  => '三重県',
                'address_city'  => '津市',
                'address_more_details'  => '栄町4-255 津栄町三交ビル',
                'tel'  => '0592253311',
                'fax'  => '0592253366',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/mie/',
            ],
            [
                'post_code'  => '5208513',
                'address_prefecture'  => '滋賀県',
                'address_city'  => '大津市',
                'address_more_details'  => '梅林１－３－１０ 滋賀ビル',
                'tel'  => '0775221099',
                'fax'  => '0775221138',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/shiga/',
            ],
            [
                'post_code'  => '6008522',
                'address_prefecture'  => '京都府',
                'address_city'  => '京都市下京区',
                'address_more_details'  => '四条通麩屋町西入立売東町28-2　大和証券京都ビル2階',
                'tel'  => '0752568630',
                'fax'  => '0752568670',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/kyoto/',
            ],
            [
                'post_code'  => '5508510',
                'address_prefecture'  => '大阪府',
                'address_city'  => '大阪市西区',
                'address_more_details'  => '靱本町１－１１－７　信濃橋三井ビル',
                'tel'  => '0677114300',
                'fax'  => '0677114610',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/osaka/',
            ],
            [
                'post_code'  => '6518512',
                'address_prefecture'  => '兵庫県',
                'address_city'  => '神戸市中央区',
                'address_more_details'  => '磯上通７－１－５ 三宮プラザEAST',
                'tel'  => '0782528701',
                'fax'  => '0782528712',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/hyogo/',
            ],
            [
                'post_code'  => '6308535',
                'address_prefecture'  => '奈良県',
                'address_city'  => '奈良市',
                'address_more_details'  => '大宮町７－１－３３ 奈良センタービル',
                'tel'  => '0742303700',
                'fax'  => '0742303670',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/nara/',
            ],
            [
                'post_code'  => '6408516',
                'address_prefecture'  => '和歌山県',
                'address_city'  => '和歌山市',
                'address_more_details'  => '六番丁５ 和歌山六番丁801ビル',
                'tel'  => '0734213100',
                'fax'  => '0734213116',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/wakayama/',
            ],
            [
                'post_code'  => '6808560',
                'address_prefecture'  => '鳥取県',
                'address_city'  => '鳥取市',
                'address_more_details'  => '今町２－１１２　アクティ日ノ丸総本社ビル５階',
                'tel'  => '0857250050',
                'fax'  => '0857250060',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/tottori/',
            ],
            [
                'post_code'  => '6908531',
                'address_prefecture'  => '島根県',
                'address_city'  => '松江市',
                'address_more_details'  => '殿町383 山陰中央ビル2階',
                'tel'  => '0852595139',
                'fax'  => '0852595352',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/shimane/',
            ],
            [
                'post_code'  => '7008506',
                'address_prefecture'  => '岡山県',
                'address_city'  => '岡山市北区',
                'address_more_details'  => '本町６－３６ 第一セントラルビル',
                'tel'  => '0868035780',
                'fax'  => '0868035750',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/okayama/',
            ],
            [
                'post_code'  => '7328512',
                'address_prefecture'  => '広島県',
                'address_city'  => '広島市東区',
                'address_more_details'  => '光町１－１０－１９ 日本生命広島光町ビル',
                'tel'  => '0825681011',
                'fax'  => '0825681130',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/hiroshima/',
            ],
            [
                'post_code'  => '7548522',
                'address_prefecture'  => '山口県',
                'address_city'  => '山口市小郡',
                'address_more_details'  => '下郷３１２－２ 山本ビル第３',
                'tel'  => '0839740530',
                'fax'  => '0839740534',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/yamaguchi/',
            ],
            [
                'post_code'  => '7708541',
                'address_prefecture'  => '徳島県',
                'address_city'  => '徳島市',
                'address_more_details'  => '八百屋町2－１１ ニッセイ徳島ビル',
                'tel'  => '0886020250',
                'fax'  => '0886020717',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/tokushima/',
            ],
            [
                'post_code'  => '7608564',
                'address_prefecture'  => '香川県',
                'address_city'  => '高松市',
                'address_more_details'  => '鍛冶屋町３ 香川三友ビル',
                'tel'  => '0878110570',
                'fax'  => '0878114550',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/kagawa/',
            ],
            [
                'post_code'  => '7908546',
                'address_prefecture'  => '愛媛県',
                'address_city'  => '松山市',
                'address_more_details'  => '千舟町４－６－３ アヴァンサ千舟１階',
                'tel'  => '0899472100',
                'fax'  => '0899472133',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/ehime/',
            ],
            [
                'post_code'  => '7808501',
                'address_prefecture'  => '高知県',
                'address_city'  => '高知市',
                'address_more_details'  => '本町４－1－24 高知電気ビル新館2階',
                'tel'  => '0888206010',
                'fax'  => '0888206023',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/kochi/',
            ],
            [
                'post_code'  => '8128670',
                'address_prefecture'  => '福岡県',
                'address_city'  => '福岡市博多区',
                'address_more_details'  => '上呉服町１０－１ 博多三井ビルディング',
                'tel'  => '0922837621',
                'fax'  => '0922837629',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/fukuoka/',
            ],
            [
                'post_code'  => '8408560',
                'address_prefecture'  => '佐賀県',
                'address_city'  => '佐賀市',
                'address_more_details'  => '駅南本町６－４ 佐賀中央第一生命ビル',
                'tel'  => '0952270611',
                'fax'  => '0952270617',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/saga/',
            ],
            [
                'post_code'  => '8508537',
                'address_prefecture'  => '長崎県',
                'address_city'  => '長崎市',
                'address_more_details'  => '大黒町９－２２ 大久保大黒町ビル本館',
                'tel'  => '0958296000',
                'fax'  => '0958296010',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/nagasaki/',
            ],
            [
                'post_code'  => '8608502',
                'address_prefecture'  => '熊本県',
                'address_city'  => '熊本市中央区',
                'address_more_details'  => '辛島町5－1 日本生命熊本ビル',
                'tel'  => '0962401030',
                'fax'  => '0962418330',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/kumamoto/',
            ],
            [
                'post_code'  => '8708570',
                'address_prefecture'  => '大分県',
                'address_city'  => '大分市',
                'address_more_details'  => '金池南１－５－１ ホルトホール大分（ＭＮＣタウン２階）',
                'tel'  => '0975735630',
                'fax'  => '0975735640',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/oita/',
            ],
            [
                'post_code'  => '8808546',
                'address_prefecture'  => '宮崎県',
                'address_city'  => '宮崎市',
                'address_more_details'  => '橘通東１－７－４ 第一宮銀ビル',
                'tel'  => '0985355364',
                'fax'  => '0985355393',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/miyazaki/',
            ],
            [
                'post_code'  => '8928540',
                'address_prefecture'  => '鹿児島県',
                'address_city'  => '鹿児島市',
                'address_more_details'  => '山之口町１－１０ 鹿児島中央ビル6階',
                'tel'  => '0992191734',
                'fax'  => '0992191743',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/kagoshima/',
            ],
            [
                'post_code'  => '9008512',
                'address_prefecture'  => '沖縄県',
                'address_city'  => '那覇市',
                'address_more_details'  => '旭町１１４－４ おきでん那覇ビル',
                'tel'  => '0989512211',
                'fax'  => '0989512295',
                'url'  => 'https://www.kyoukaikenpo.or.jp/shibu/okinawa/',
            ],
        ]);
    }
}
