<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LegalAffairsBureauSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('m_legal_affairs_bureau')->truncate();
        DB::table('m_legal_affairs_bureau')->insert([
            [
                'name'   => '札幌',
                'name_kana'  => 'サッポロ',
                'post_code'  => '0600808',
                'address_prefecture'  => '北海道',
                'address_city'  => '札幌市',
                'address_more_details'  => '北区北8条西2-1-1',
                'tel'  => '0117092311',
                'url'  => 'https://houmukyoku.moj.go.jp/sapporo/',
            ],
            [
                'name'   => '函館地方',
                'name_kana'  => 'ハコダテチホウ',
                'post_code'  => '0408533',
                'address_prefecture'  => '北海道',
                'address_city'  => '函館市',
                'address_more_details'  => '新川町25-18 函館地方合同庁舎',
                'tel'  => '0138237511',
                'url'  => 'https://houmukyoku.moj.go.jp/hakodate/',
            ],
            [
                'name'   => '旭川地方',
                'name_kana'  => 'アサヒカワチホウ',
                'post_code'  => '0788502',
                'address_prefecture'  => '北海道',
                'address_city'  => '旭川市',
                'address_more_details'  => '宮前１条3-3-15 旭川合同庁舎',
                'tel'  => '0166381111',
                'url'  => 'https://houmukyoku.moj.go.jp/asahikawa/',
            ],
            [
                'name'   => '釧路地方',
                'name_kana'  => 'クシロチホウ',
                'post_code'  => '0858522',
                'address_prefecture'  => '北海道',
                'address_city'  => '釧路市',
                'address_more_details'  => '幸町10-3',
                'tel'  => '0154315000',
                'url'  => 'https://houmukyoku.moj.go.jp/kushiro/',
            ],
            [
                'name'   => '仙台',
                'name_kana'  => 'センダイ',
                'post_code'  => '9808601',
                'address_prefecture'  => '宮城県',
                'address_city'  => '仙台市',
                'address_more_details'  => '青葉区春日町7-25仙台第３法務総合庁舎',
                'tel'  => '0222255611',
                'url'  => 'https://houmukyoku.moj.go.jp/sendai/',
            ],
            [
                'name'   => '福島地方',
                'name_kana'  => 'フクシマチホウ',
                'post_code'  => '9608021',
                'address_prefecture'  => '福島県',
                'address_city'  => '福島市',
                'address_more_details'  => '霞町1-46 福島合同庁舎',
                'tel'  => '0245341111',
                'url'  => 'https://houmukyoku.moj.go.jp/fukushima/',
            ],
            [
                'name'   => '山形地方',
                'name_kana'  => 'ヤマガタチホウ',
                'post_code'  => '9900041',
                'address_prefecture'  => '山形県',
                'address_city'  => '山形市',
                'address_more_details'  => '緑町1-5-48 山形地方合同庁舎',
                'tel'  => '0236251321',
                'url'  => 'https://houmukyoku.moj.go.jp/yamagata/',
            ],
            [
                'name'   => '盛岡地方',
                'name_kana'  => 'モリオカチホウ',
                'post_code'  => '0200045',
                'address_prefecture'  => '岩手県',
                'address_city'  => '盛岡市',
                'address_more_details'  => '盛岡駅西通1-9-15 盛岡第２合同庁舎',
                'tel'  => '0196241141',
                'url'  => 'https://houmukyoku.moj.go.jp/morioka/',
            ],
            [
                'name'   => '秋田地方',
                'name_kana'  => 'アキタチホウ',
                'post_code'  => '0100951',
                'address_prefecture'  => '秋田県',
                'address_city'  => '秋田市',
                'address_more_details'  => '山王7-1-3',
                'tel'  => '0188626531',
                'url'  => 'https://houmukyoku.moj.go.jp/akita/',
            ],
            [
                'name'   => '青森地方',
                'name_kana'  => 'アオモリチホウ',
                'post_code'  => '0308511',
                'address_prefecture'  => '青森県',
                'address_city'  => '青森市',
                'address_more_details'  => '長島1-3-5 青森第二合同庁舎',
                'tel'  => '0177766231',
                'url'  => 'https://houmukyoku.moj.go.jp/aomori/',
            ],
            [
                'name'   => '東京',
                'name_kana'  => 'トウキョウ',
                'post_code'  => '1028225',
                'address_prefecture'  => '東京都',
                'address_city'  => '千代田区',
                'address_more_details'  => '九段南1-1-15 九段第２合同庁舎',
                'tel'  => '0352131234',
                'url'  => 'https://houmukyoku.moj.go.jp/tokyo/',
            ],
            [
                'name'   => '横浜地方',
                'name_kana'  => 'ヨコハマチホウ',
                'post_code'  => '2318411',
                'address_prefecture'  => '神奈川県',
                'address_city'  => '横浜市',
                'address_more_details'  => '中区北仲通5-57横浜第２合同庁舎',
                'tel'  => '0456417461',
                'url'  => 'https://houmukyoku.moj.go.jp/yokohama/',
            ],
            [
                'name'   => 'さいたま地方',
                'name_kana'  => 'サイタマチホウ',
                'post_code'  => '3388513',
                'address_prefecture'  => '埼玉県',
                'address_city'  => 'さいたま市',
                'address_more_details'  => '中央区下落合5-12-1 さいたま第２法務総合庁舎',
                'tel'  => '0488511000',
                'url'  => 'https://houmukyoku.moj.go.jp/saitama/',
            ],
            [
                'name'   => '千葉地方',
                'name_kana'  => 'チバチホウ',
                'post_code'  => '2608518',
                'address_prefecture'  => '千葉県',
                'address_city'  => '千葉市',
                'address_more_details'  => '中央区中央港1-11-3',
                'tel'  => '0433021311',
                'url'  => 'https://houmukyoku.moj.go.jp/chiba/',
            ],
            [
                'name'   => '水戸地方',
                'name_kana'  => 'ミトチホウ',
                'post_code'  => '3100061',
                'address_prefecture'  => '茨城県',
                'address_city'  => '水戸市',
                'address_more_details'  => '北見町1-1 水戸法務総合庁舎',
                'tel'  => '0292279911',
                'url'  => 'https://houmukyoku.moj.go.jp/mito/',
            ],
            [
                'name'   => '宇都宮地方',
                'name_kana'  => 'ウトミヤチホウ',
                'post_code'  => '3208515',
                'address_prefecture'  => '栃木県',
                'address_city'  => '宇都宮市',
                'address_more_details'  => '小幡2-1-11',
                'tel'  => '0286236333',
                'url'  => 'https://houmukyoku.moj.go.jp/utsunomiya/',
            ],
            [
                'name'   => '前橋地方',
                'name_kana'  => 'マエバシチホウ',
                'post_code'  => '3718535',
                'address_prefecture'  => '群馬県',
                'address_city'  => '前橋市',
                'address_more_details'  => '大手町2-3-1　前橋地方合同庁舎',
                'tel'  => '0272214466',
                'url'  => 'https://houmukyoku.moj.go.jp/maebashi/',
            ],
            [
                'name'   => '静岡地方',
                'name_kana'  => 'シズオカチホウ',
                'post_code'  => '4208650',
                'address_prefecture'  => '静岡県',
                'address_city'  => '静岡市',
                'address_more_details'  => '葵区追手町9-50 静岡地方合同庁舎',
                'tel'  => '0542543555',
                'url'  => 'https://houmukyoku.moj.go.jp/shizuoka/',
            ],
            [
                'name'   => '甲府地方',
                'name_kana'  => 'コウフチホウ',
                'post_code'  => '4008520',
                'address_prefecture'  => '山梨県',
                'address_city'  => '甲府市',
                'address_more_details'  => '丸の内1－1－18 甲府合同庁舎',
                'tel'  => '0552527151',
                'url'  => 'https://houmukyoku.moj.go.jp/kofu/',
            ],
            [
                'name'   => '長野地方',
                'name_kana'  => 'ナガノチホウ',
                'post_code'  => '3800846',
                'address_prefecture'  => '長野県',
                'address_city'  => '長野市',
                'address_more_details'  => '大字長野旭町1108',
                'tel'  => '0262356611',
                'url'  => 'https://houmukyoku.moj.go.jp/nagano/',
            ],
            [
                'name'   => '新潟地方',
                'name_kana'  => 'ニイガタチホウ',
                'post_code'  => '9518504',
                'address_prefecture'  => '新潟県',
                'address_city'  => '新潟市',
                'address_more_details'  => '西大畑町5191 新潟法務総合庁舎',
                'tel'  => '0252221561',
                'url'  => 'https://houmukyoku.moj.go.jp/niigata/',
            ],
            [
                'name'   => '名古屋',
                'name_kana'  => 'ナゴヤチホウ',
                'post_code'  => '4608513',
                'address_prefecture'  => '愛知県',
                'address_city'  => '名古屋市',
                'address_more_details'  => '中区三の丸2-2-1名古屋合同庁舎第１号館',
                'tel'  => '0529528111',
                'url'  => 'https://houmukyoku.moj.go.jp/nagoya/',
            ],
            [
                'name'   => '津地方',
                'name_kana'  => 'ツチホウ',
                'post_code'  => '5148503',
                'address_prefecture'  => '三重県',
                'address_city'  => '津市',
                'address_more_details'  => '丸之内26-8 津合同庁舎',
                'tel'  => '0592284191',
                'url'  => 'https://houmukyoku.moj.go.jp/tsu/',
            ],
            [
                'name'   => '岐阜地方',
                'name_kana'  => 'ギフチホウ',
                'post_code'  => '5008729',
                'address_prefecture'  => '岐阜県',
                'address_city'  => '岐阜市',
                'address_more_details'  => '金竜町5-13',
                'tel'  => '0582453181',
                'url'  => 'https://houmukyoku.moj.go.jp/gifu/',
            ],
            [
                'name'   => '福井地方',
                'name_kana'  => 'フクイチホウ',
                'post_code'  => '9108504',
                'address_prefecture'  => '福井県',
                'address_city'  => '福井市',
                'address_more_details'  => '春山1-1-54 福井春山合同庁舎',
                'tel'  => '0776225090',
                'url'  => 'https://houmukyoku.moj.go.jp/fukui/',
            ],
            [
                'name'   => '金沢地方',
                'name_kana'  => 'カナザワチホウ',
                'post_code'  => '9218505',
                'address_prefecture'  => '石川県',
                'address_city'  => '金沢市',
                'address_more_details'  => '新神田4-3-10 金沢新神田合同庁舎',
                'tel'  => '0762927810',
                'url'  => 'https://houmukyoku.moj.go.jp/kanazawa/',
            ],
            [
                'name'   => '富山地方',
                'name_kana'  => 'トヤマチホウ',
                'post_code'  => '9300856',
                'address_prefecture'  => '富山県',
                'address_city'  => '富山市',
                'address_more_details'  => '牛島新町11-7 富山合同庁舎',
                'tel'  => '0764410550',
                'url'  => 'https://houmukyoku.moj.go.jp/toyama/',
            ],
            [
                'name'   => '大阪',
                'name_kana'  => 'オオサカ',
                'post_code'  => '5408544',
                'address_prefecture'  => '大阪府',
                'address_city'  => '大阪市',
                'address_more_details'  => '中央区大手前三丁目1番41号大手前合同庁舎',
                'tel'  => '0669421481',
                'url'  => 'https://houmukyoku.moj.go.jp/osaka/',
            ],
            [
                'name'   => '京都地方',
                'name_kana'  => 'キョウトチホウ',
                'post_code'  => '6028577',
                'address_prefecture'  => '京都府',
                'address_city'  => '京都市',
                'address_more_details'  => '上京区荒神口通河原町東入上生洲町197',
                'tel'  => '0752310131',
                'url'  => 'https://houmukyoku.moj.go.jp/kyoto/',
            ],
            [
                'name'   => '神戸地方',
                'name_kana'  => 'コベチホウ',
                'post_code'  => '6500042',
                'address_prefecture'  => '兵庫県',
                'address_city'  => '神戸市',
                'address_more_details'  => '中央区波止場町1-1 神戸第２地方合同庁舎',
                'tel'  => '0783921821',
                'url'  => 'https://houmukyoku.moj.go.jp/kobe/',
            ],
            [
                'name'   => '奈良地方',
                'name_kana'  => 'ナラチホウ',
                'post_code'  => '6308301',
                'address_prefecture'  => '奈良県',
                'address_city'  => '奈良市',
                'address_more_details'  => '高畑町552',
                'tel'  => '0742235534',
                'url'  => 'https://houmukyoku.moj.go.jp/nara/',
            ],
            [
                'name'   => '大津地方',
                'name_kana'  => 'オオツチホウ',
                'post_code'  => '5208516',
                'address_prefecture'  => '滋賀県',
                'address_city'  => '大津市',
                'address_more_details'  => '京町3-1-1 大津びわ湖合同庁舎',
                'tel'  => '0775224671',
                'url'  => 'https://houmukyoku.moj.go.jp/otsu/',
            ],
            [
                'name'   => '和歌山地方',
                'name_kana'  => 'ワカヤマチホウ',
                'post_code'  => '6408552',
                'address_prefecture'  => '和歌山県',
                'address_city'  => '和歌山市',
                'address_more_details'  => '二番丁3 （和歌山地方合同庁舎）',
                'tel'  => '0734225131',
                'url'  => 'https://houmukyoku.moj.go.jp/wakayama/',
            ],
            [
                'name'   => '広島',
                'name_kana'  => 'ヒロシマチホウ',
                'post_code'  => '7308536',
                'address_prefecture'  => '広島県',
                'address_city'  => '広島市',
                'address_more_details'  => '中区上八丁堀6-30',
                'tel'  => '0822285201',
                'url'  => 'https://houmukyoku.moj.go.jp/hiroshima/',
            ],
            [
                'name'   => '山口地方',
                'name_kana'  => 'ヤマグチチホウ',
                'post_code'  => '7538577',
                'address_prefecture'  => '山口県',
                'address_city'  => '山口市',
                'address_more_details'  => '中河原町6-16 山口地方合同庁舎２号館',
                'tel'  => '0839222295',
                'url'  => 'https://houmukyoku.moj.go.jp/yamaguchi/',
            ],
            [
                'name'   => '岡山地方',
                'name_kana'  => 'オカヤマチホウ',
                'post_code'  => '7008616',
                'address_prefecture'  => '岡山県',
                'address_city'  => '岡山市',
                'address_more_details'  => '北区南方1-3-58',
                'tel'  => '0862245656',
                'url'  => 'https://houmukyoku.moj.go.jp/okayama/',
            ],
            [
                'name'   => '鳥取地方',
                'name_kana'  => 'トットリチホウ',
                'post_code'  => '6800011',
                'address_prefecture'  => '鳥取県',
                'address_city'  => '鳥取市',
                'address_more_details'  => '東町2-302 鳥取第２地方合同庁舎',
                'tel'  => '0857222191',
                'url'  => 'https://houmukyoku.moj.go.jp/tottori/',
            ],
            [
                'name'   => '松江地方',
                'name_kana'  => 'マツエチホウ',
                'post_code'  => '6900001',
                'address_prefecture'  => '島根県',
                'address_city'  => '松江市',
                'address_more_details'  => '東朝日町192番地3',
                'tel'  => '0852324200',
                'url'  => 'https://houmukyoku.moj.go.jp/matsue/',
            ],
            [
                'name'   => '高松',
                'name_kana'  => 'タカマツチホウ',
                'post_code'  => '7608508',
                'address_prefecture'  => '香川県',
                'address_city'  => '高松市',
                'address_more_details'  => '丸の内1-1 高松法務合同庁舎',
                'tel'  => '0878216191',
                'url'  => 'https://houmukyoku.moj.go.jp/takamatsu/',
            ],
            [
                'name'   => '徳島地方',
                'name_kana'  => 'トクシマチホウ',
                'post_code'  => '7708512',
                'address_prefecture'  => '徳島県',
                'address_city'  => '徳島市',
                'address_more_details'  => '徳島町城内6-6 徳島地方合同庁舎',
                'tel'  => '0886224171',
                'url'  => 'https://houmukyoku.moj.go.jp/tokushima/',
            ],
            [
                'name'   => '高知地方',
                'name_kana'  => 'コウチチホウ',
                'post_code'  => '7808509',
                'address_prefecture'  => '高知県',
                'address_city'  => '高知市',
                'address_more_details'  => '栄田町2-2-10高知よさこい咲都合同庁舎',
                'tel'  => '0888223331',
                'url'  => 'https://houmukyoku.moj.go.jp/kochi/',
            ],
            [
                'name'   => '松山地方',
                'name_kana'  => 'マツヤマチホウ',
                'post_code'  => '7908505',
                'address_prefecture'  => '愛媛県',
                'address_city'  => '松山市',
                'address_more_details'  => '宮田町188-6 松山地方合同庁舎',
                'tel'  => '0899320888',
                'url'  => 'https://houmukyoku.moj.go.jp/matsuyama/',
            ],
            [
                'name'   => '福岡',
                'name_kana'  => 'フクオカ',
                'post_code'  => '8108513',
                'address_prefecture'  => '福岡県',
                'address_city'  => '福岡市',
                'address_more_details'  => '中央区舞鶴3-5-25',
                'tel'  => '0927214570',
                'url'  => 'https://houmukyoku.moj.go.jp/fukuoka/',
            ],
            [
                'name'   => '佐賀地方',
                'name_kana'  => 'サガチホウ',
                'post_code'  => '8400041',
                'address_prefecture'  => '佐賀県',
                'address_city'  => '佐賀市',
                'address_more_details'  => '城内2-10-20',
                'tel'  => '0952262148',
                'url'  => 'https://houmukyoku.moj.go.jp/saga/',
            ],
            [
                'name'   => '長崎地方',
                'name_kana'  => 'ナガサキチホウ',
                'post_code'  => '8508507',
                'address_prefecture'  => '長崎県',
                'address_city'  => '長崎市',
                'address_more_details'  => '万才町8-16',
                'tel'  => '0958268127',
                'url'  => 'https://houmukyoku.moj.go.jp/nagasaki/',
            ],
            [
                'name'   => '大分地方',
                'name_kana'  => 'オオイタチホウ',
                'post_code'  => '8708513',
                'address_prefecture'  => '大分県',
                'address_city'  => '大分市',
                'address_more_details'  => '荷揚町7-5大分法務総合庁舎',
                'tel'  => '0975323161',
                'url'  => 'https://houmukyoku.moj.go.jp/oita/',
            ],
            [
                'name'   => '熊本地方',
                'name_kana'  => 'クマモトチホウ',
                'post_code'  => '8620971',
                'address_prefecture'  => '熊本県',
                'address_city'  => '熊本市',
                'address_more_details'  => '中央区大江3-1-53 熊本第２合同庁舎',
                'tel'  => '0963642145',
                'url'  => 'https://houmukyoku.moj.go.jp/kumamoto/',
            ],
            [
                'name'   => '鹿児島地方',
                'name_kana'  => 'カゴシマチホウ',
                'post_code'  => '8908518',
                'address_prefecture'  => '鹿児島県',
                'address_city'  => '鹿児島市',
                'address_more_details'  => '鴨池新町1-2',
                'tel'  => '0992590680',
                'url'  => 'https://houmukyoku.moj.go.jp/kagoshima/',
            ],
            [
                'name'   => '宮崎地方',
                'name_kana'  => 'ミヤザキチホウ',
                'post_code'  => '8808513',
                'address_prefecture'  => '宮崎県',
                'address_city'  => '宮崎市',
                'address_more_details'  => '別府町1番1号 宮崎法務総合庁舎',
                'tel'  => '0985225124',
                'url'  => 'https://houmukyoku.moj.go.jp/miyazaki/',
            ],
            [
                'name'   => '那覇地方',
                'name_kana'  => 'ナハチホウ',
                'post_code'  => '9008544',
                'address_prefecture'  => '沖縄県',
                'address_city'  => '那覇市',
                'address_more_details'  => '樋川1-15-15 那覇第１地方合同庁舎',
                'tel'  => '0988547950',
                'url'  => 'https://houmukyoku.moj.go.jp/naha/',
            ],
        ]);
    }
}
