<?php

namespace App\Http\Controllers\Ledger;

use App\Http\Controllers\Controller;
use App\Http\Requests\CareLeaveBenefitEmploymentInsuranceCareLeaveBenefitApplicationRequest;
use App\Models\Branch;
use App\Models\CurrentUser;
use App\Models\Certificate;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\EgovAPI\MixXmlEgovSigner;
use App\Permission;

class CaregiverLeaveBenefitApplicationController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware(function ($request, $next) {
            $userPermission = new Permission;
            if (!$userPermission->isSelectedCompany() || $userPermission->denyProcedure() || !$userPermission->isReadableFor(8) || !$userPermission->isWritableFor(8) || !$userPermission->isBasicDepartment()) {
                return redirect()->route('home.index');
            }
            return $next($request);
        });
    }

    public function index(Request $request)
    {
        if (!$this->isSelectedCompany()) {
            return redirect()->route('home.select');
        }

        $company = CurrentUser::currentCompany();
        $companyId = $company->id;
        $certificate = Certificate::where('company_id', $companyId)
            ->where('delete_flg', 0)
            ->first();
        if ($certificate !== null) {
            $certificate = true;
        } else {
            $certificate = false;
        }
        $currentEmployee = CurrentUser::info();
        $currentBranch = Branch::where('id', $currentEmployee->branch_id)->first();
        $convertToday = $this->convertWesternCalendarToJapaneseCalendar(Carbon::today());
        $today = [
            'era' => $convertToday['japanese_calendar_era_string'],
            'year' => $convertToday['japanese_calendar_result']->year,
            'month' => $convertToday['japanese_calendar_result']->month,
            'date' => $convertToday['japanese_calendar_result']->day,
        ];
        $egovAcount = $this->egovAcount();
        $procedureName = $this->getProcedureName($request);

        return view('ledger.caregiver_leave_benefit_application', [
            'company' => $company,
            'current_employee' => $currentEmployee,
            'current_branch' => $currentBranch,
            'today' => $today,
            'certificate' => $certificate,
            'egovAcount' => $egovAcount,
            'procedureName' => $procedureName
        ]);
    }

    public function post(CareLeaveBenefitEmploymentInsuranceCareLeaveBenefitApplicationRequest $request)
    {
        $attachment = [];

        $data = $request->all();

        foreach ($data as $key => $value) {
            if (strpos($key, 'radio_') === 0) {
                $file_key = substr($key, strlen('radio_'));
                $label_key = ($file_key === 'file_other') ? 'input_file_other' : 'label_' . $file_key;

                $attachment_type = ($value === '2') ? '添付' : '別送';

                $attached_document_name = $request->input($label_key);

                $attachment_file_name = '';
                if ($value === '2' && $request->hasFile($file_key)) {
                    $file = $request->file($file_key);
                    $attachment_file_name = $file->getClientOriginalName();
                }

                $attachment[] = [
                    'attachment_type' => $attachment_type,
                    'attached_document_name' => $attached_document_name,
                    'attachment_file_name' => $attachment_file_name,
                    'submission_info' => '1'
                ];
            }
        }

        if (!empty($attachment)) {
            $request->merge(['attachment' => $attachment]);
        }

        $radio_keys = ["radio_file_nursing_facts", "radio_file_nursing_care_recipient", "radio_file_wage_payment_status", "radio_file_closing_starts", "radio_file_other"];

        foreach ($radio_keys as $key) {
            if (!$request->has($key)) {
                $request->merge([$key => 0]);
            }
        }

        try {
            $data = [
                'employment_mynumber_card_no' => $request->input('employment_mynumber_card_no'),
                'employment_insured_no_4' => $request->input('employment_insured_no_4'),
                'employment_insured_no_6' => $request->input('employment_insured_no_6'),
                'employment_insured_no_cd' => $request->input('employment_insured_no_cd'),
                'employment_insured_date_era' => $request->input('employment_insured_date_era'),
                'employment_insured_date_year' => $request->input('employment_insured_date_year'),
                'employment_insured_date_month' => $request->input('employment_insured_date_month'),
                'employment_insured_date_day' => $request->input('employment_insured_date_day'),
                'employment_fullname' => $request->input('employment_fullname'),
                'employment_fullname_kana' => $request->input('employment_fullname_kana'),
                'insurance_office_no_4' => $request->input('insurance_office_no_4'),
                'insurance_office_no_6' => $request->input('insurance_office_no_6'),
                'insurance_office_no_cd' => $request->input('insurance_office_no_cd'),
                'employment_lastname' => $request->input('employment_lastname'),
                'employment_firstname' => $request->input('employment_firstname'),
                'caregiver_leave_start_date_era' => $request->input('caregiver_leave_start_date_era'),
                'caregiver_leave_start_date_year' => $request->input('caregiver_leave_start_date_year'),
                'caregiver_leave_start_date_month' => $request->input('caregiver_leave_start_date_month'),
                'caregiver_leave_start_date_day' => $request->input('caregiver_leave_start_date_day'),
                'dependent_mynumber_card_no' => $request->input('dependent_mynumber_card_no'),
                'dependent_lastname_kana' => $request->input('dependent_lastname_kana'),
                'dependent_firstname_kana' => $request->input('dependent_firstname_kana'),
                'dependent_sex' => $request->input('dependent_sex'),
                'dependent_relationship' => $request->input('dependent_relationship'),
                'dependent_lastname' => $request->input('dependent_lastname'),
                'dependent_firstname' => $request->input('dependent_firstname'),
                'care_target_family_birthday_era' => $request->input('care_target_family_birthday_era'),
                'care_target_family_birthday_year' => $request->input('care_target_family_birthday_year'),
                'care_target_family_birthday_month' => $request->input('care_target_family_birthday_month'),
                'care_target_family_birthday_day' => $request->input('care_target_family_birthday_day'),
                'pay_target_period_era_1' => $request->input('pay_target_period_era_1'),
                'pay_target_period_year_start_1' => $request->input('pay_target_period_year_start_1'),
                'pay_target_period_month_start_1' => $request->input('pay_target_period_month_start_1'),
                'pay_target_period_day_start_1' => $request->input('pay_target_period_day_start_1'),
                'pay_target_period_month_end_1' => $request->input('pay_target_period_month_end_1'),
                'pay_target_period_day_end_1' => $request->input('pay_target_period_day_end_1'),
                'full_time_leave_days_1' => $request->input('full_time_leave_days_1'),
                'paid_wage_amount_1' => $request->input('paid_wage_amount_1'),
                'pay_target_period_era_2' => $request->input('pay_target_period_era_2'),
                'pay_target_period_year_start_2' => $request->input('pay_target_period_year_start_2'),
                'pay_target_period_month_start_2' => $request->input('pay_target_period_month_start_2'),
                'pay_target_period_day_start_2' => $request->input('pay_target_period_day_start_2'),
                'pay_target_period_month_end_2' => $request->input('pay_target_period_month_end_2'),
                'pay_target_period_day_end_2' => $request->input('pay_target_period_day_end_2'),
                'full_time_leave_days_2' => $request->input('full_time_leave_days_2'),
                'paid_wage_amount_2' => $request->input('paid_wage_amount_2'),
                'pay_target_period_era_3' => $request->input('pay_target_period_era_3'),
                'pay_target_period_year_start_3' => $request->input('pay_target_period_year_start_3'),
                'pay_target_period_month_start_3' => $request->input('pay_target_period_month_start_3'),
                'pay_target_period_day_start_3' => $request->input('pay_target_period_day_start_3'),
                'pay_target_period_month_end_3' => $request->input('pay_target_period_month_end_3'),
                'pay_target_period_day_end_3' => $request->input('pay_target_period_day_end_3'),
                'full_time_leave_days_3' => $request->input('full_time_leave_days_3'),
                'paid_wage_amount_3' => $request->input('paid_wage_amount_3'),
                'caregiver_leave_end_date_era' => $request->input('caregiver_leave_end_date_era'),
                'caregiver_leave_end_date_year' => $request->input('caregiver_leave_end_date_year'),
                'caregiver_leave_end_date_month' => $request->input('caregiver_leave_end_date_month'),
                'caregiver_leave_end_date_day' => $request->input('caregiver_leave_end_date_day'),
                'caregiver_leave_end_reason' => $request->input('caregiver_leave_end_reason'),
                'verification_date_era' => $request->input('verification_date_era'),
                'verification_date_year' => $request->input('verification_date_year'),
                'verification_date_month' => $request->input('verification_date_month'),
                'verification_date_day' => $request->input('verification_date_day'),
                'branch' => $request->input('branch'),
                'entrepreneur_name' => $request->input('entrepreneur_name'),
                'application_date_era' => $request->input('application_date_era'),
                'application_date_year' => $request->input('application_date_year'),
                'application_date_month' => $request->input('application_date_month'),
                'application_date_day' => $request->input('application_date_day'),
                'hello_work_destination' => $request->input('hello_work_destination,_'),
                'bank_name' => $request->input('bank_name'),
                'bank_name_kana' => $request->input('bank_name_kana'),
                'bank_head_office_branch_office_type' => $request->input('bank_head_office_branch_office_type'),
                'bank_code' => $request->input('bank_code'),
                'bank_store_code' => $request->input('bank_store_code'),
                'bank_account_no' => $request->input('bank_account_no'),
                'japan_post_bank_code_no' => $request->input('japan_post_bank_code_no'),
                'japan_post_bank_account_no' => $request->input('japan_post_bank_account_no'),
                'wage_deadline_date' => $request->input('wage_deadline_date'),
                'wage_due_date_month' => $request->input('wage_due_date_month'),
                'wage_deadline_date' => $request->input('wage_deadline_date'),
                'commuting_allowance_existence' => $request->input('commuting_allowance_existence'),
                'commuting_allowance_period' => $request->input('commuting_allowance_period'),
                'commuting_allowance_period_other' => $request->input('commuting_allowance_period_other'),
                'note_main' => $request->input('note_main'),
                'creation_date_submission_agent' => $request->input('creation_date_submission_agent'),
                'labor_consultant_fullname' => $request->input('labor_consultant_fullname'),
                'labor_consultant_tel_area_code' => $request->input('labor_consultant_tel_area_code'),
                'labor_consultant_tel_city_code' => $request->input('labor_consultant_tel_city_code'),
                'labor_consultant_tel_subscriber_code' => $request->input('labor_consultant_tel_subscriber_code'),
                'leave_start_wage_monthly_certificate' => $request->input('leave_start_wage_monthly_certificate'),
                'reduced_working_hours_wage_certificate_start' => $request->input('reduced_working_hours_wage_certificate_start'),
                'branch_name' => $request->input('branch_name'),
                'branch_address' => $request->input('branch_address'),
                'branch_tel_area_code' => $request->input('branch_tel_area_code'),
                'branch_tel_city_code' => $request->input('branch_tel_city_code'),
                'branch_tel_subscriber_code' => $request->input('branch_tel_subscriber_code'),
                'post_code_3' => $request->input('post_code_3'),
                'post_code_4' => $request->input('post_code_4'),
                'employment_address' => $request->input('employment_address'),
                'employment_tel_area_code' => $request->input('employment_tel_area_code'),
                'employment_tel_city_code' => $request->input('employment_tel_city_code'),
                'employment_tel_subscriber_code' => $request->input('employment_tel_subscriber_code'),
                'entrepreneur_address' => $request->input('entrepreneur_address'),
                'calculation_month_start_1' => $request->input('calculation_month_start_1'),
                'calculation_day_start_1' => $request->input('calculation_day_start_1'),
                'calculation_month_start_1_1' => $request->input('calculation_month_start_1_1'),
                'calculation_day_start_1_1' => $request->input('calculation_day_start_1_1'),
                'calculation_month_end_1_1' => $request->input('calculation_month_end_1_1'),
                'calculation_day_end_1_1' => $request->input('calculation_day_end_1_1'),
                'calculation_month_start_1_2' => $request->input('calculation_month_start_1_2'),
                'calculation_day_start_1_2' => $request->input('calculation_day_start_1_2'),
                'calculation_month_end_1_2' => $request->input('calculation_month_end_1_2'),
                'calculation_day_end_1_2' => $request->input('calculation_day_end_1_2'),
                'calculation_month_start_1_3' => $request->input('calculation_month_start_1_3'),
                'calculation_day_start_1_3' => $request->input('calculation_day_start_1_3'),
                'calculation_month_end_1_3' => $request->input('calculation_month_end_1_3'),
                'calculation_day_end_1_3' => $request->input('calculation_day_end_1_3'),
                'calculation_month_start_1_4' => $request->input('calculation_month_start_1_4'),
                'calculation_day_start_1_4' => $request->input('calculation_day_start_1_4'),
                'calculation_month_end_1_4' => $request->input('calculation_month_end_1_4'),
                'calculation_day_end_1_4' => $request->input('calculation_day_end_1_4'),
                'calculation_month_start_1_5' => $request->input('calculation_month_start_1_5'),
                'calculation_day_start_1_5' => $request->input('calculation_day_start_1_5'),
                'calculation_month_end_1_5' => $request->input('calculation_month_end_1_5'),
                'calculation_day_end_1_5' => $request->input('calculation_day_end_1_5'),
                'calculation_month_start_1_6' => $request->input('calculation_month_start_1_6'),
                'calculation_day_start_1_6' => $request->input('calculation_day_start_1_6'),
                'calculation_month_end_1_6' => $request->input('calculation_month_end_1_6'),
                'calculation_day_end_1_6' => $request->input('calculation_day_end_1_6'),
                'calculation_month_start_1_7' => $request->input('calculation_month_start_1_7'),
                'calculation_day_start_1_7' => $request->input('calculation_day_start_1_7'),
                'calculation_month_end_1_7' => $request->input('calculation_month_end_1_7'),
                'calculation_day_end_1_7' => $request->input('calculation_day_end_1_7'),
                'calculation_month_start_1_8' => $request->input('calculation_month_start_1_8'),
                'calculation_day_start_1_8' => $request->input('calculation_day_start_1_8'),
                'calculation_month_end_1_8' => $request->input('calculation_month_end_1_8'),
                'calculation_day_end_1_8' => $request->input('calculation_day_end_1_8'),
                'calculation_month_start_1_9' => $request->input('calculation_month_start_1_9'),
                'calculation_day_start_1_9' => $request->input('calculation_day_start_1_9'),
                'calculation_month_end_1_9' => $request->input('calculation_month_end_1_9'),
                'calculation_day_end_1_9' => $request->input('calculation_day_end_1_9'),
                'calculation_month_start_1_10' => $request->input('calculation_month_start_1_10'),
                'calculation_day_start_1_10' => $request->input('calculation_day_start_1_10'),
                'calculation_month_end_1_10' => $request->input('calculation_month_end_1_10'),
                'calculation_day_end_1_10' => $request->input('calculation_day_end_1_10'),
                'calculation_month_start_1_11' => $request->input('calculation_month_start_1_11'),
                'calculation_day_start_1_11' => $request->input('calculation_day_start_1_11'),
                'calculation_month_end_1_11' => $request->input('calculation_month_end_1_11'),
                'calculation_day_end_1_11' => $request->input('calculation_day_end_1_11'),
                'calculation_month_start_1_12' => $request->input('calculation_month_start_1_12'),
                'calculation_day_start_1_12' => $request->input('calculation_day_start_1_12'),
                'calculation_month_end_1_12' => $request->input('calculation_month_end_1_12'),
                'calculation_day_end_1_12' => $request->input('calculation_day_end_1_12'),
                'calculation_month_start_1_13' => $request->input('calculation_month_start_1_13'),
                'calculation_day_start_1_13' => $request->input('calculation_day_start_1_13'),
                'calculation_month_end_1_13' => $request->input('calculation_month_end_1_13'),
                'calculation_day_end_1_13' => $request->input('calculation_day_end_1_13'),
                'calculation_month_start_1_14' => $request->input('calculation_month_start_1_14'),
                'calculation_day_start_1_14' => $request->input('calculation_day_start_1_14'),
                'calculation_month_end_1_14' => $request->input('calculation_month_end_1_14'),
                'calculation_day_end_1_14' => $request->input('calculation_day_end_1_14'),
                'calculation_month_start_1_15' => $request->input('calculation_month_start_1_15'),
                'calculation_day_start_1_15' => $request->input('calculation_day_start_1_15'),
                'calculation_month_end_1_15' => $request->input('calculation_month_end_1_15'),
                'calculation_day_end_1_15' => $request->input('calculation_day_end_1_15'),
                'calculation_basic_period_1' => $request->input('calculation_basic_period_1'),
                'calculation_basic_period_1_1' => $request->input('calculation_basic_period_1_1'),
                'calculation_basic_period_1_2' => $request->input('calculation_basic_period_1_2'),
                'calculation_basic_period_1_3' => $request->input('calculation_basic_period_1_3'),
                'calculation_basic_period_1_4' => $request->input('calculation_basic_period_1_4'),
                'calculation_basic_period_1_5' => $request->input('calculation_basic_period_1_5'),
                'calculation_basic_period_1_6' => $request->input('calculation_basic_period_1_6'),
                'calculation_basic_period_1_7' => $request->input('calculation_basic_period_1_7'),
                'calculation_basic_period_1_8' => $request->input('calculation_basic_period_1_8'),
                'calculation_basic_period_1_9' => $request->input('calculation_basic_period_1_9'),
                'calculation_basic_period_1_10' => $request->input('calculation_basic_period_1_10'),
                'calculation_basic_period_1_11' => $request->input('calculation_basic_period_1_11'),
                'calculation_basic_period_1_12' => $request->input('calculation_basic_period_1_12'),
                'calculation_basic_period_1_13' => $request->input('calculation_basic_period_1_13'),
                'calculation_basic_period_1_14' => $request->input('calculation_basic_period_1_14'),
                'calculation_basic_period_1_15' => $request->input('calculation_basic_period_1_15'),
                'payment_month_start_1' => $request->input('payment_month_start_1'),
                'payment_day_start_1' => $request->input('payment_day_start_1'),
                'payment_month_start_1_1' => $request->input('payment_month_start_1_1'),
                'payment_day_start_1_1' => $request->input('payment_day_start_1_1'),
                'payment_month_end_1_1' => $request->input('payment_month_end_1_1'),
                'payment_day_end_1_1' => $request->input('payment_day_end_1_1'),
                'payment_month_start_1_2' => $request->input('payment_month_start_1_2'),
                'payment_day_start_1_2' => $request->input('payment_day_start_1_2'),
                'payment_month_end_1_2' => $request->input('payment_month_end_1_2'),
                'payment_day_end_1_2' => $request->input('payment_day_end_1_2'),
                'payment_month_start_1_3' => $request->input('payment_month_start_1_3'),
                'payment_day_start_1_3' => $request->input('payment_day_start_1_3'),
                'payment_month_end_1_3' => $request->input('payment_month_end_1_3'),
                'payment_day_end_1_3' => $request->input('payment_day_end_1_3'),
                'payment_month_start_1_4' => $request->input('payment_month_start_1_4'),
                'payment_day_start_1_4' => $request->input('payment_day_start_1_4'),
                'payment_month_end_1_4' => $request->input('payment_month_end_1_4'),
                'payment_day_end_1_4' => $request->input('payment_day_end_1_4'),
                'payment_month_start_1_5' => $request->input('payment_month_start_1_5'),
                'payment_day_start_1_5' => $request->input('payment_day_start_1_5'),
                'payment_month_end_1_5' => $request->input('payment_month_end_1_5'),
                'payment_day_end_1_5' => $request->input('payment_day_end_1_5'),
                'payment_month_start_1_6' => $request->input('payment_month_start_1_6'),
                'payment_day_start_1_6' => $request->input('payment_day_start_1_6'),
                'payment_month_end_1_6' => $request->input('payment_month_end_1_6'),
                'payment_day_end_1_6' => $request->input('payment_day_end_1_6'),
                'payment_month_start_1_7' => $request->input('payment_month_start_1_7'),
                'payment_day_start_1_7' => $request->input('payment_day_start_1_7'),
                'payment_month_end_1_7' => $request->input('payment_month_end_1_7'),
                'payment_day_end_1_7' => $request->input('payment_day_end_1_7'),
                'payment_month_start_1_8' => $request->input('payment_month_start_1_8'),
                'payment_day_start_1_8' => $request->input('payment_day_start_1_8'),
                'payment_month_end_1_8' => $request->input('payment_month_end_1_8'),
                'payment_day_end_1_8' => $request->input('payment_day_end_1_8'),
                'payment_month_start_1_9' => $request->input('payment_month_start_1_9'),
                'payment_day_start_1_9' => $request->input('payment_day_start_1_9'),
                'payment_month_end_1_9' => $request->input('payment_month_end_1_9'),
                'payment_day_end_1_9' => $request->input('payment_day_end_1_9'),
                'payment_month_start_1_10' => $request->input('payment_month_start_1_10'),
                'payment_day_start_1_10' => $request->input('payment_day_start_1_10'),
                'payment_month_end_1_10' => $request->input('payment_month_end_1_10'),
                'payment_day_end_1_10' => $request->input('payment_day_end_1_10'),
                'payment_month_start_1_11' => $request->input('payment_month_start_1_11'),
                'payment_day_start_1_11' => $request->input('payment_day_start_1_11'),
                'payment_month_end_1_11' => $request->input('payment_month_end_1_11'),
                'payment_day_end_1_11' => $request->input('payment_day_end_1_11'),
                'payment_month_start_1_12' => $request->input('payment_month_start_1_12'),
                'payment_day_start_1_12' => $request->input('payment_day_start_1_12'),
                'payment_month_end_1_12' => $request->input('payment_month_end_1_12'),
                'payment_day_end_1_12' => $request->input('payment_day_end_1_12'),
                'payment_month_start_1_13' => $request->input('payment_month_start_1_13'),
                'payment_day_start_1_13' => $request->input('payment_day_start_1_13'),
                'payment_month_end_1_13' => $request->input('payment_month_end_1_13'),
                'payment_day_end_1_13' => $request->input('payment_day_end_1_13'),
                'payment_month_start_1_14' => $request->input('payment_month_start_1_14'),
                'payment_day_start_1_14' => $request->input('payment_day_start_1_14'),
                'payment_month_end_1_14' => $request->input('payment_month_end_1_14'),
                'payment_day_end_1_14' => $request->input('payment_day_end_1_14'),
                'payment_month_start_1_15' => $request->input('payment_month_start_1_15'),
                'payment_day_start_1_15' => $request->input('payment_day_start_1_15'),
                'payment_month_end_1_15' => $request->input('payment_month_end_1_15'),
                'payment_day_end_1_15' => $request->input('payment_day_end_1_15'),
                'payment_basic_period_1' => $request->input('payment_basic_period_1'),
                'payment_basic_period_1_1' => $request->input('payment_basic_period_1_1'),
                'payment_basic_period_1_2' => $request->input('payment_basic_period_1_2'),
                'payment_basic_period_1_3' => $request->input('payment_basic_period_1_3'),
                'payment_basic_period_1_4' => $request->input('payment_basic_period_1_4'),
                'payment_basic_period_1_5' => $request->input('payment_basic_period_1_5'),
                'payment_basic_period_1_6' => $request->input('payment_basic_period_1_6'),
                'payment_basic_period_1_7' => $request->input('payment_basic_period_1_7'),
                'payment_basic_period_1_8' => $request->input('payment_basic_period_1_8'),
                'payment_basic_period_1_9' => $request->input('payment_basic_period_1_9'),
                'payment_basic_period_1_10' => $request->input('payment_basic_period_1_10'),
                'payment_basic_period_1_11' => $request->input('payment_basic_period_1_11'),
                'payment_basic_period_1_12' => $request->input('payment_basic_period_1_12'),
                'payment_basic_period_1_13' => $request->input('payment_basic_period_1_13'),
                'payment_basic_period_1_14' => $request->input('payment_basic_period_1_14'),
                'payment_basic_period_1_15' => $request->input('payment_basic_period_1_15'),
                'wage_amountA' => $request->input('wage_amountA'),
                'wage_amountA_1_1' => $request->input('wage_amountA_1_1'),
                'wage_amountA_1_2' => $request->input('wage_amountA_1_2'),
                'wage_amountA_1_3' => $request->input('wage_amountA_1_3'),
                'wage_amountA_1_4' => $request->input('wage_amountA_1_4'),
                'wage_amountA_1_5' => $request->input('wage_amountA_1_5'),
                'wage_amountA_1_6' => $request->input('wage_amountA_1_6'),
                'wage_amountA_1_7' => $request->input('wage_amountA_1_7'),
                'wage_amountA_1_8' => $request->input('wage_amountA_1_8'),
                'wage_amountA_1_9' => $request->input('wage_amountA_1_9'),
                'wage_amountA_1_10' => $request->input('wage_amountA_1_10'),
                'wage_amountA_1_11' => $request->input('wage_amountA_1_11'),
                'wage_amountA_1_12' => $request->input('wage_amountA_1_12'),
                'wage_amountA_1_13' => $request->input('wage_amountA_1_13'),
                'wage_amountA_1_14' => $request->input('wage_amountA_1_14'),
                'wage_amountA_1_15' => $request->input('wage_amountA_1_15'),
                'wage_amountB' => $request->input('wage_amountB'),
                'wage_amountB_1_1' => $request->input('wage_amountB_1_1'),
                'wage_amountB_1_2' => $request->input('wage_amountB_1_2'),
                'wage_amountB_1_3' => $request->input('wage_amountB_1_3'),
                'wage_amountB_1_4' => $request->input('wage_amountB_1_4'),
                'wage_amountB_1_5' => $request->input('wage_amountB_1_5'),
                'wage_amountB_1_6' => $request->input('wage_amountB_1_6'),
                'wage_amountB_1_7' => $request->input('wage_amountB_1_7'),
                'wage_amountB_1_8' => $request->input('wage_amountB_1_8'),
                'wage_amountB_1_9' => $request->input('wage_amountB_1_9'),
                'wage_amountB_1_10' => $request->input('wage_amountB_1_10'),
                'wage_amountB_1_11' => $request->input('wage_amountB_1_11'),
                'wage_amountB_1_12' => $request->input('wage_amountB_1_12'),
                'wage_amountB_1_13' => $request->input('wage_amountB_1_13'),
                'wage_amountB_1_14' => $request->input('wage_amountB_1_14'),
                'wage_amountB_1_15' => $request->input('wage_amountB_1_15'),
                'wage_amount_total_1' => $request->input('wage_amount_total_1'),
                'wage_amount_total_1_1' => $request->input('wage_amount_total_1_1'),
                'wage_amount_total_1_2' => $request->input('wage_amount_total_1_2'),
                'wage_amount_total_1_3' => $request->input('wage_amount_total_1_3'),
                'wage_amount_total_1_4' => $request->input('wage_amount_total_1_4'),
                'wage_amount_total_1_5' => $request->input('wage_amount_total_1_5'),
                'wage_amount_total_1_6' => $request->input('wage_amount_total_1_6'),
                'wage_amount_total_1_7' => $request->input('wage_amount_total_1_7'),
                'wage_amount_total_1_8' => $request->input('wage_amount_total_1_8'),
                'wage_amount_total_1_9' => $request->input('wage_amount_total_1_9'),
                'wage_amount_total_1_10' => $request->input('wage_amount_total_1_10'),
                'wage_amount_total_1_11' => $request->input('wage_amount_total_1_11'),
                'wage_amount_total_1_12' => $request->input('wage_amount_total_1_12'),
                'wage_amount_total_1_13' => $request->input('wage_amount_total_1_13'),
                'wage_amount_total_1_14' => $request->input('wage_amount_total_1_14'),
                'wage_amount_total_1_15' => $request->input('wage_amount_total_1_15'),
                'note_1' => $request->input('note_1'),
                'note_1_1' => $request->input('note_1_1'),
                'note_1_2' => $request->input('note_1_2'),
                'note_1_3' => $request->input('note_1_3'),
                'note_1_4' => $request->input('note_1_4'),
                'note_1_5' => $request->input('note_1_5'),
                'note_1_6' => $request->input('note_1_6'),
                'note_1_7' => $request->input('note_1_7'),
                'note_1_8' => $request->input('note_1_8'),
                'note_1_9' => $request->input('note_1_9'),
                'note_1_10' => $request->input('note_1_10'),
                'note_1_11' => $request->input('note_1_11'),
                'note_1_12' => $request->input('note_1_12'),
                'note_1_13' => $request->input('note_1_13'),
                'note_1_14' => $request->input('note_1_14'),
                'note_1_15' => $request->input('note_1_15'),
                'wage_note_1' => $request->input('wage_note_1'),
                'employment_period_regulation' => $request->input('employment_period_regulation'),
                'employment_period_japan_era' => $request->input('employment_period_japan_era'),
                'employment_period_year' => $request->input('employment_period_year'),
                'employment_period_month' => $request->input('employment_period_month'),
                'employment_period_day' => $request->input('employment_period_day'),
                'including_leave_start_date_year' => $request->input('including_leave_start_date_year'),
                'including_leave_start_date_month' => $request->input('including_leave_start_date_month'),
                'labor_consultant_note' => $request->input('labor_consultant_note'),
                'creation_date_japan_era' => $request->input('creation_date_japan_era'),
                'creation_date_year' => $request->input('creation_date_year'),
                'creation_date_month' => $request->input('creation_date_month'),
                'creation_date_day' => $request->input('creation_date_day'),
                'calculation_month_start_2_1' => $request->input('calculation_month_start_2_1'),
                'calculation_day_start_2_1' => $request->input('calculation_day_start_2_1'),
                'calculation_month_end_2_1' => $request->input('calculation_month_end_2_1'),
                'calculation_day_end_2_1' => $request->input('calculation_day_end_2_1'),
                'calculation_month_start_2_2' => $request->input('calculation_month_start_2_2'),
                'calculation_day_start_2_2' => $request->input('calculation_day_start_2_2'),
                'calculation_month_end_2_2' => $request->input('calculation_month_end_2_2'),
                'calculation_day_end_2_2' => $request->input('calculation_day_end_2_2'),
                'calculation_month_start_2_3' => $request->input('calculation_month_start_2_3'),
                'calculation_day_start_2_3' => $request->input('calculation_day_start_2_3'),
                'calculation_month_end_2_3' => $request->input('calculation_month_end_2_3'),
                'calculation_day_end_2_3' => $request->input('calculation_day_end_2_3'),
                'calculation_month_start_2_4' => $request->input('calculation_month_start_2_4'),
                'calculation_day_start_2_4' => $request->input('calculation_day_start_2_4'),
                'calculation_month_end_2_4' => $request->input('calculation_month_end_2_4'),
                'calculation_day_end_2_4' => $request->input('calculation_day_end_2_4'),
                'calculation_month_start_2_5' => $request->input('calculation_month_start_2_5'),
                'calculation_day_start_2_5' => $request->input('calculation_day_start_2_5'),
                'calculation_month_end_2_5' => $request->input('calculation_month_end_2_5'),
                'calculation_day_end_2_5' => $request->input('calculation_day_end_2_5'),
                'calculation_month_start_2_6' => $request->input('calculation_month_start_2_6'),
                'calculation_day_start_2_6' => $request->input('calculation_day_start_2_6'),
                'calculation_month_end_2_6' => $request->input('calculation_month_end_2_6'),
                'calculation_day_end_2_6' => $request->input('calculation_day_end_2_6'),
                'calculation_month_start_2_7' => $request->input('calculation_month_start_2_7'),
                'calculation_day_start_2_7' => $request->input('calculation_day_start_2_7'),
                'calculation_month_end_2_7' => $request->input('calculation_month_end_2_7'),
                'calculation_day_end_2_7' => $request->input('calculation_day_end_2_7'),
                'calculation_month_start_2_8' => $request->input('calculation_month_start_2_8'),
                'calculation_day_start_2_8' => $request->input('calculation_day_start_2_8'),
                'calculation_month_end_2_8' => $request->input('calculation_month_end_2_8'),
                'calculation_day_end_2_8' => $request->input('calculation_day_end_2_8'),
                'calculation_month_start_2_9' => $request->input('calculation_month_start_2_9'),
                'calculation_day_start_2_9' => $request->input('calculation_day_start_2_9'),
                'calculation_month_end_2_9' => $request->input('calculation_month_end_2_9'),
                'calculation_day_end_2_9' => $request->input('calculation_day_end_2_9'),
                'calculation_month_start_2_10' => $request->input('calculation_month_start_2_10'),
                'calculation_day_start_2_10' => $request->input('calculation_day_start_2_10'),
                'calculation_month_end_2_10' => $request->input('calculation_month_end_2_10'),
                'calculation_day_end_2_10' => $request->input('calculation_day_end_2_10'),
                'calculation_month_start_2_11' => $request->input('calculation_month_start_2_11'),
                'calculation_day_start_2_11' => $request->input('calculation_day_start_2_11'),
                'calculation_month_end_2_11' => $request->input('calculation_month_end_2_11'),
                'calculation_day_end_2_11' => $request->input('calculation_day_end_2_11'),
                'calculation_month_start_2_12' => $request->input('calculation_month_start_2_12'),
                'calculation_day_start_2_12' => $request->input('calculation_day_start_2_12'),
                'calculation_month_end_2_12' => $request->input('calculation_month_end_2_12'),
                'calculation_day_end_2_12' => $request->input('calculation_day_end_2_12'),
                'calculation_month_start_2_13' => $request->input('calculation_month_start_2_13'),
                'calculation_day_start_2_13' => $request->input('calculation_day_start_2_13'),
                'calculation_month_end_2_13' => $request->input('calculation_month_end_2_13'),
                'calculation_day_end_2_13' => $request->input('calculation_day_end_2_13'),
                'calculation_month_start_2_14' => $request->input('calculation_month_start_2_14'),
                'calculation_day_start_2_14' => $request->input('calculation_day_start_2_14'),
                'calculation_month_end_2_14' => $request->input('calculation_month_end_2_14'),
                'calculation_day_end_2_14' => $request->input('calculation_day_end_2_14'),
                'calculation_month_start_2_15' => $request->input('calculation_month_start_2_15'),
                'calculation_day_start_2_15' => $request->input('calculation_day_start_2_15'),
                'calculation_month_end_2_15' => $request->input('calculation_month_end_2_15'),
                'calculation_day_end_2_15' => $request->input('calculation_day_end_2_15'),
                'calculation_basic_period_2_1' => $request->input('calculation_basic_period_2_1'),
                'calculation_basic_period_2_2' => $request->input('calculation_basic_period_2_2'),
                'calculation_basic_period_2_3' => $request->input('calculation_basic_period_2_3'),
                'calculation_basic_period_2_4' => $request->input('calculation_basic_period_2_4'),
                'calculation_basic_period_2_5' => $request->input('calculation_basic_period_2_5'),
                'calculation_basic_period_2_6' => $request->input('calculation_basic_period_2_6'),
                'calculation_basic_period_2_7' => $request->input('calculation_basic_period_2_7'),
                'calculation_basic_period_2_8' => $request->input('calculation_basic_period_2_8'),
                'calculation_basic_period_2_9' => $request->input('calculation_basic_period_2_9'),
                'calculation_basic_period_2_10' => $request->input('calculation_basic_period_2_10'),
                'calculation_basic_period_2_11' => $request->input('calculation_basic_period_2_11'),
                'calculation_basic_period_2_12' => $request->input('calculation_basic_period_2_12'),
                'calculation_basic_period_2_13' => $request->input('calculation_basic_period_2_13'),
                'calculation_basic_period_2_14' => $request->input('calculation_basic_period_2_14'),
                'calculation_basic_period_2_15' => $request->input('calculation_basic_period_2_15'),
                'payment_month_start_2_1' => $request->input('payment_month_start_2_1'),
                'payment_month_start_2_1' => $request->input('payment_month_start_2_1'),
                'payment_day_start_2_1' => $request->input('payment_day_start_2_1'),
                'payment_month_end_2_1' => $request->input('payment_month_end_2_1'),
                'payment_day_end_2_1' => $request->input('payment_day_end_2_1'),
                'payment_month_start_2_2' => $request->input('payment_month_start_2_2'),
                'payment_day_start_2_2' => $request->input('payment_day_start_2_2'),
                'payment_month_end_2_2' => $request->input('payment_month_end_2_2'),
                'payment_day_end_2_2' => $request->input('payment_day_end_2_2'),
                'payment_month_start_2_3' => $request->input('payment_month_start_2_3'),
                'payment_day_start_2_3' => $request->input('payment_day_start_2_3'),
                'payment_month_end_2_3' => $request->input('payment_month_end_2_3'),
                'payment_day_end_2_3' => $request->input('payment_day_end_2_3'),
                'payment_month_start_2_4' => $request->input('payment_month_start_2_4'),
                'payment_day_start_2_4' => $request->input('payment_day_start_2_4'),
                'payment_month_end_2_4' => $request->input('payment_month_end_2_4'),
                'payment_day_end_2_4' => $request->input('payment_day_end_2_4'),
                'payment_month_start_2_5' => $request->input('payment_month_start_2_5'),
                'payment_day_start_2_5' => $request->input('payment_day_start_2_5'),
                'payment_month_end_2_5' => $request->input('payment_month_end_2_5'),
                'payment_day_end_2_5' => $request->input('payment_day_end_2_5'),
                'payment_month_start_2_6' => $request->input('payment_month_start_2_6'),
                'payment_day_start_2_6' => $request->input('payment_day_start_2_6'),
                'payment_month_end_2_6' => $request->input('payment_month_end_2_6'),
                'payment_day_end_2_6' => $request->input('payment_day_end_2_6'),
                'payment_month_start_2_7' => $request->input('payment_month_start_2_7'),
                'payment_day_start_2_7' => $request->input('payment_day_start_2_7'),
                'payment_month_end_2_7' => $request->input('payment_month_end_2_7'),
                'payment_day_end_2_7' => $request->input('payment_day_end_2_7'),
                'payment_month_start_2_8' => $request->input('payment_month_start_2_8'),
                'payment_day_start_2_8' => $request->input('payment_day_start_2_8'),
                'payment_month_end_2_8' => $request->input('payment_month_end_2_8'),
                'payment_day_end_2_8' => $request->input('payment_day_end_2_8'),
                'payment_month_start_2_9' => $request->input('payment_month_start_2_9'),
                'payment_day_start_2_9' => $request->input('payment_day_start_2_9'),
                'payment_month_end_2_9' => $request->input('payment_month_end_2_9'),
                'payment_day_end_2_9' => $request->input('payment_day_end_2_9'),
                'payment_month_start_2_10' => $request->input('payment_month_start_2_10'),
                'payment_day_start_2_10' => $request->input('payment_day_start_2_10'),
                'payment_month_end_2_10' => $request->input('payment_month_end_2_10'),
                'payment_day_end_2_10' => $request->input('payment_day_end_2_10'),
                'payment_month_start_2_11' => $request->input('payment_month_start_2_11'),
                'payment_day_start_2_11' => $request->input('payment_day_start_2_11'),
                'payment_month_end_2_11' => $request->input('payment_month_end_2_11'),
                'payment_day_end_2_11' => $request->input('payment_day_end_2_11'),
                'payment_month_start_2_12' => $request->input('payment_month_start_2_12'),
                'payment_day_start_2_12' => $request->input('payment_day_start_2_12'),
                'payment_month_end_2_12' => $request->input('payment_month_end_2_12'),
                'payment_day_end_2_12' => $request->input('payment_day_end_2_12'),
                'payment_month_start_2_13' => $request->input('payment_month_start_2_13'),
                'payment_day_start_2_13' => $request->input('payment_day_start_2_13'),
                'payment_month_end_2_13' => $request->input('payment_month_end_2_13'),
                'payment_day_end_2_13' => $request->input('payment_day_end_2_13'),
                'payment_month_start_2_14' => $request->input('payment_month_start_2_14'),
                'payment_day_start_2_14' => $request->input('payment_day_start_2_14'),
                'payment_month_end_2_14' => $request->input('payment_month_end_2_14'),
                'payment_day_end_2_14' => $request->input('payment_day_end_2_14'),
                'payment_month_start_2_15' => $request->input('payment_month_start_2_15'),
                'payment_day_start_2_15' => $request->input('payment_day_start_2_15'),
                'payment_month_end_2_15' => $request->input('payment_month_end_2_15'),
                'payment_day_end_2_15' => $request->input('payment_day_end_2_15'),
                'payment_basic_period_2_1' => $request->input('payment_basic_period_2_1'),
                'payment_basic_period_2_2' => $request->input('payment_basic_period_2_2'),
                'payment_basic_period_2_3' => $request->input('payment_basic_period_2_3'),
                'payment_basic_period_2_4' => $request->input('payment_basic_period_2_4'),
                'payment_basic_period_2_5' => $request->input('payment_basic_period_2_5'),
                'payment_basic_period_2_6' => $request->input('payment_basic_period_2_6'),
                'payment_basic_period_2_7' => $request->input('payment_basic_period_2_7'),
                'payment_basic_period_2_8' => $request->input('payment_basic_period_2_8'),
                'payment_basic_period_2_9' => $request->input('payment_basic_period_2_9'),
                'payment_basic_period_2_10' => $request->input('payment_basic_period_2_10'),
                'payment_basic_period_2_11' => $request->input('payment_basic_period_2_11'),
                'payment_basic_period_2_12' => $request->input('payment_basic_period_2_12'),
                'payment_basic_period_2_13' => $request->input('payment_basic_period_2_13'),
                'payment_basic_period_2_14' => $request->input('payment_basic_period_2_14'),
                'payment_basic_period_2_15' => $request->input('payment_basic_period_2_15'),
                'wage_amountA_2_1' => $request->input('wage_amountA_2_1'),
                'wage_amountA_2_2' => $request->input('wage_amountA_2_2'),
                'wage_amountA_2_3' => $request->input('wage_amountA_2_3'),
                'wage_amountA_2_4' => $request->input('wage_amountA_2_4'),
                'wage_amountA_2_5' => $request->input('wage_amountA_2_5'),
                'wage_amountA_2_6' => $request->input('wage_amountA_2_6'),
                'wage_amountA_2_7' => $request->input('wage_amountA_2_7'),
                'wage_amountA_2_8' => $request->input('wage_amountA_2_8'),
                'wage_amountA_2_9' => $request->input('wage_amountA_2_9'),
                'wage_amountA_2_10' => $request->input('wage_amountA_2_10'),
                'wage_amountA_2_11' => $request->input('wage_amountA_2_11'),
                'wage_amountA_2_12' => $request->input('wage_amountA_2_12'),
                'wage_amountA_2_13' => $request->input('wage_amountA_2_13'),
                'wage_amountA_2_14' => $request->input('wage_amountA_2_14'),
                'wage_amountA_2_15' => $request->input('wage_amountA_2_15'),
                'wage_amountB_2_1' => $request->input('wage_amountB_2_1'),
                'wage_amountB_2_2' => $request->input('wage_amountB_2_2'),
                'wage_amountB_2_3' => $request->input('wage_amountB_2_3'),
                'wage_amountB_2_4' => $request->input('wage_amountB_2_4'),
                'wage_amountB_2_5' => $request->input('wage_amountB_2_5'),
                'wage_amountB_2_6' => $request->input('wage_amountB_2_6'),
                'wage_amountB_2_7' => $request->input('wage_amountB_2_7'),
                'wage_amountB_2_8' => $request->input('wage_amountB_2_8'),
                'wage_amountB_2_9' => $request->input('wage_amountB_2_9'),
                'wage_amountB_2_10' => $request->input('wage_amountB_2_10'),
                'wage_amountB_2_11' => $request->input('wage_amountB_2_11'),
                'wage_amountB_2_12' => $request->input('wage_amountB_2_12'),
                'wage_amountB_2_13' => $request->input('wage_amountB_2_13'),
                'wage_amountB_2_14' => $request->input('wage_amountB_2_14'),
                'wage_amountB_2_15' => $request->input('wage_amountB_2_15'),
                'wage_amount_total_2_1' => $request->input('wage_amount_total_2_1'),
                'wage_amount_total_2_2' => $request->input('wage_amount_total_2_2'),
                'wage_amount_total_2_3' => $request->input('wage_amount_total_2_3'),
                'wage_amount_total_2_4' => $request->input('wage_amount_total_2_4'),
                'wage_amount_total_2_5' => $request->input('wage_amount_total_2_5'),
                'wage_amount_total_2_6' => $request->input('wage_amount_total_2_6'),
                'wage_amount_total_2_7' => $request->input('wage_amount_total_2_7'),
                'wage_amount_total_2_8' => $request->input('wage_amount_total_2_8'),
                'wage_amount_total_2_9' => $request->input('wage_amount_total_2_9'),
                'wage_amount_total_2_10' => $request->input('wage_amount_total_2_10'),
                'wage_amount_total_2_11' => $request->input('wage_amount_total_2_11'),
                'wage_amount_total_2_12' => $request->input('wage_amount_total_2_12'),
                'wage_amount_total_2_13' => $request->input('wage_amount_total_2_13'),
                'wage_amount_total_2_14' => $request->input('wage_amount_total_2_14'),
                'wage_amount_total_2_15' => $request->input('wage_amount_total_2_15'),
                'note_2_1' => $request->input('note_2_1'),
                'note_2_2' => $request->input('note_2_2'),
                'note_2_3' => $request->input('note_2_3'),
                'note_2_4' => $request->input('note_2_4'),
                'note_2_5' => $request->input('note_2_5'),
                'note_2_6' => $request->input('note_2_6'),
                'note_2_7' => $request->input('note_2_7'),
                'note_2_8' => $request->input('note_2_8'),
                'note_2_9' => $request->input('note_2_9'),
                'note_2_10' => $request->input('note_2_10'),
                'note_2_11' => $request->input('note_2_11'),
                'note_2_12' => $request->input('note_2_12'),
                'note_2_13' => $request->input('note_2_13'),
                'note_2_14' => $request->input('note_2_14'),
                'note_2_15' => $request->input('note_2_15'),
                'wage_note_2' => $request->input('wage_note_2'),
                'apply_to_code' => $request->input('apply_to_code'),
                'apply_to_name' => $request->input('apply_to_name')
            ];
            $XML = new MixXmlEgovSigner($request);
            $response = $XML->run($request, $separater = True);
            if ($response[0] == false) {
                $errorMessage = $response[1];
                return redirect()->back()->withErrors($errorMessage)->withInput();
            }
            $this->putSuccess("送信に成功しました");
            return redirect()->route('ledger.index');
        } catch (ValidationException $e) {
            return redirect()->back()->withErrors($e->errors())->withInput();
        }
    }
}
