<?php

namespace App\Http\Controllers\Ledger;

use App\Http\Controllers\Controller;
use App\Http\Requests\EmploymentInsuredQualificationLossWithCertificateRequest;
use App\Models\CurrentUser;
use App\Models\Branch;
use App\Models\Country;
use App\Models\Residential_status;
use App\Models\Values_employee_insured_age_type;
use App\Models\Values_employee_employment_status;
use App\Models\Certificate;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Carbon\Carbon;
use App\EgovAPI\MixXmlEgovSigner;

class EmploymentInsuredQualificationLossController extends Controller
{
    public function index(Request $request)
    {
        if (!$this->isSelectedCompany()) {
            return redirect()->route('home.select');
        }

        $company = CurrentUser::currentCompany();
        $companyId = $company->id;
        $certificate = Certificate::where('company_id', $companyId)
            ->where('delete_flg', 0)
            ->first();
        if ($certificate !== null) {
            $certificate = true;
        } else {
            $certificate = false;
        }
        $current_employee = CurrentUser::info();
        $current_branch_id = $current_employee->branch_id;
        $current_branch = Branch::where('id', $current_branch_id)->first();

        $convertToday = $this->convertWesternCalendarToJapaneseCalendar(Carbon::today());
        $today = [
            'era' => $convertToday['japanese_calendar_era_string'],
            'year' => $convertToday['japanese_calendar_result']->year,
            'month' => $convertToday['japanese_calendar_result']->month,
            'date' => $convertToday['japanese_calendar_result']->day,
        ];

        $countries = Country::all();
        $residentials = Residential_status::all();
        $insuredAgeTypes = Values_employee_insured_age_type::all();
        $employmentStatuses = Values_employee_employment_status::all();
        $egovAcount = $this->egovAcount();
        $procedureName = $this->getProcedureName($request);

        return view('ledger.employment_insured_qualification_loss', [
            'company' => $company,
            'current_employee' => $current_employee,
            'current_branch' => $current_branch,
            'today' => $today,
            'countries' => $countries,
            'residentials' => $residentials,
            'insuredAgeTypes' => $insuredAgeTypes,
            'employmentStatuses' => $employmentStatuses,
            'certificate' => $certificate,
            'egovAcount' => $egovAcount,
            'procedureName' => $procedureName
        ]);
    }

    public function post(EmploymentInsuredQualificationLossWithCertificateRequest $request)
    {
        $attachment = [];

        $data = $request->all();

        foreach ($data as $key => $value) {
            if (strpos($key, 'radio_') === 0) {
                $file_key = substr($key, strlen('radio_'));
                $label_key = ($file_key === 'file_other') ? 'input_file_other' : 'label_' . $file_key;
                
                $attachment_type = ($value === '2') ? '添付' : '別送';

                $attached_document_name = $request->input($label_key);

                $attachment_file_name = '';
                if ($value === '2' && $request->hasFile($file_key)) {
                    $file = $request->file($file_key);
                    $attachment_file_name = $file->getClientOriginalName();
                }

                $attachment[] = [
                    'attachment_type' => $attachment_type,
                    'attached_document_name' => $attached_document_name,
                    'attachment_file_name' => $attachment_file_name,
                    'submission_info' => '1'
                ];
            }
        }

        if (!empty($attachment)) {
            $request->merge(['attachment' => $attachment]);
        }

        $radio_keys = ["radio_file_disqualification_status", "radio_file_other"];

        foreach ($radio_keys as $key) {
            if (!$request->has($key)) {
                $request->merge([$key => 0]);
            }
        }

        try {
            $data = [
                'employment_insured_no_4' => $request->input('employment_insured_no_4'),
                'employment_insured_no_6' => $request->input('employment_insured_no_6'),
                'employment_insured_no_CD' => $request->input('employment_insured_no_CD'),
                'insurance_office_no_4' => $request->input('insurance_office_no_4'),
                'insurance_office_no_6' => $request->input('insurance_office_no_6'),
                'insurance_office_no_CD' => $request->input('insurance_office_no_CD'),
                'insured_date_era' => $request->input('insured_date_era'),
                'insured_date_year' => $request->input('insured_date_year'),
                'insured_date_month' => $request->input('insured_date_month'),
                'insured_date_day' => $request->input('insured_date_day'),
                'retirement_date_era' => $request->input('retirement_date_era'),
                'retirement_date_year' => $request->input('retirement_date_year'),
                'retirement_date_month' => $request->input('retirement_date_month'),
                'retirement_date_day' => $request->input('retirement_date_day'),
                'insurance_loss_reason' => $request->input('insurance_loss_reason'),
                'agreed_hours_day_hour' => $request->input('agreed_hours_day_hour'),
                'agreed_hours_day_minute' => $request->input('agreed_hours_day_minute'),
                'new_name' => $request->input('new_name'),
                'new_name_kana' => $request->input('new_name_kana'),
                'mynumber_card_no' => $request->input('mynumber_card_no'),
                'name' => $request->input('name'),
                'name_kana' => $request->input('name_kana'),
                'sex' => $request->input('sex'),
                'birthday_era' => $request->input('birthday_era'),
                'birthday_year' => $request->input('birthday_year'),
                'birthday_month' => $request->input('birthday_month'),
                'birthday_day' => $request->input('birthday_day'),
                'insured_age_type' => $request->input('insured_age_type'),
                'hello_work_office_no' => $request->input('hello_work_office_no'),
                'company_name_abbreviation' => $request->input('company_name_abbreviation'),
                'employee_address' => $request->input('employee_address'),
                'insured_reason' => $request->input('insured_reason'),
                'name_alphabet' => $request->input('name_alphabet'),
                'residence_card_no' => $request->input('residence_card_no'),
                'stay_date_period_year' => $request->input('stay_date_period_year'),
                'stay_date_period_month' => $request->input('stay_date_period_month'),
                'stay_date_period_day' => $request->input('stay_date_period_day'),
                'employment_type' => $request->input('employment_type'),
                'country' => $request->input('country'),
                'residential_status' => $request->input('residential_status'),
                'residential_status_unknown_reason' => $request->input('residential_status_unknown_reason'),
                'notification_era' => $request->input('notification_era'),
                'notification_year' => $request->input('notification_year'),
                'notification_month' => $request->input('notification_month'),
                'notification_day' => $request->input('notification_day'),
                'headquarters_address' => $request->input('headquarters_address'),
                'employer_company_managerial_position_name' => $request->input('employer_company_managerial_position_name'),
                'headquarters_tel_area_code' => $request->input('headquarters_tel_area_code'),
                'headquarters_tel_city_code' => $request->input('headquarters_tel_city_code'),
                'headquarters_tel_subscriber_code' => $request->input('headquarters_tel_subscriber_code'),
                'hello_work_name' => $request->input('hello_work_name'),
                'labor_consultant_japan_era' => $request->input('labor_consultant_japan_era'),
                'labor_consultant_japan_era_year' => $request->input('labor_consultant_japan_era_year'),
                'labor_consultant_month' => $request->input('labor_consultant_month'),
                'labor_consultant_day' => $request->input('labor_consultant_day'),
                'labor_consultant_acting_as_agent_name' => $request->input('labor_consultant_acting_as_agent_name'),
                'labor_consultant_tel_area_code' => $request->input('labor_consultant_tel_area_code'),
                'labor_consultant_tel_city_code' => $request->input('labor_consultant_tel_city_code'),
                'labor_consultant_tel_subscriber_code' => $request->input('labor_consultant_tel_subscriber_code'),
                'other_notes' => $request->input('other_notes'),
                'branch_name' => $request->input('branch_name'),
                'branch_address' => $request->input('branch_address'),
                'branch_tel_area_code' => $request->input('branch_tel_area_code'),
                'branch_tel_city_code' => $request->input('branch_tel_city_code'),
                'branch_tel_subscriber_code' => $request->input('branch_tel_subscriber_code'),
                'employee_post_code_former' => $request->input('employee_post_code_former'),
                'employee_post_code_latter' => $request->input('employee_post_code_latter'),
                'employee_tel_area_code' => $request->input('employee_tel_area_code'),
                'employee_tel_city_code' => $request->input('employee_tel_city_code'),
                'employee_tel_subscriber_code' => $request->input('employee_tel_subscriber_code'),
                'the_day_after_retirement_date_month' => $request->input('the_day_after_retirement_date_month'),
                'the_day_after_retirement_date_day' => $request->input('the_day_after_retirement_date_day'),
                'insured_period_start_month' => $request->input('insured_period_start_month'),
                'insured_period_start_day' => $request->input('insured_period_start_day'),
                'basic_days_for_salary_payment_of_insured_period' => $request->input('basic_days_for_salary_payment_of_insured_period'),
                'salary_payment_period_start_month' => $request->input('salary_payment_period_start_month'),
                'salary_payment_period_start_day' => $request->input('salary_payment_period_start_day'),
                'basic_days_of_salary_payment_period' => $request->input('basic_days_of_salary_payment_period'),
                'salary_amount_A' => $request->input('salary_amount_A'),
                'salary_amount_B' => $request->input('salary_amount_B'),
                'salary_amount_total' => $request->input('salary_amount_total'),
                'memo' => $request->input('memo'),
                'insured_period_start_month_1' => $request->input('insured_period_start_month_1'),
                'insured_period_start_day_1' => $request->input('insured_period_start_day_1'),
                'insured_period_end_month_1' => $request->input('insured_period_end_month_1'),
                'insured_period_end_day_1' => $request->input('insured_period_end_day_1'),
                'insured_period_month_1' => $request->input('insured_period_month_1'),
                'basic_days_for_salary_payment_of_insured_period_1' => $request->input('basic_days_for_salary_payment_of_insured_period_1'),
                'salary_payment_period_start_month_1' => $request->input('salary_payment_period_start_month_1'),
                'salary_payment_period_start_day_1' => $request->input('salary_payment_period_start_day_1'),
                'salary_payment_period_end_month_1' => $request->input('salary_payment_period_end_month_1'),
                'salary_payment_period_end_day_1' => $request->input('salary_payment_period_end_day_1'),
                'basic_days_of_salary_payment_period_1' => $request->input('basic_days_of_salary_payment_period_1'),
                'salary_amount_A_1' => $request->input('salary_amount_A_1'),
                'salary_amount_B_1' => $request->input('salary_amount_B_1'),
                'salary_amount_total_1' => $request->input('salary_amount_total_1'),
                'memo_1' => $request->input('memo_1'),
                'insured_period_start_month_2' => $request->input('insured_period_start_month_2'),
                'insured_period_start_day_2' => $request->input('insured_period_start_day_2'),
                'insured_period_end_month_2' => $request->input('insured_period_end_month_2'),
                'insured_period_end_day_2' => $request->input('insured_period_end_day_2'),
                'insured_period_month_2' => $request->input('insured_period_month_2'),
                'basic_days_for_salary_payment_of_insured_period_2' => $request->input('basic_days_for_salary_payment_of_insured_period_2'),
                'salary_payment_period_start_month_2' => $request->input('salary_payment_period_start_month_2'),
                'salary_payment_period_start_day_2' => $request->input('salary_payment_period_start_day_2'),
                'salary_payment_period_end_month_2' => $request->input('salary_payment_period_end_month_2'),
                'salary_payment_period_end_day_2' => $request->input('salary_payment_period_end_day_2'),
                'basic_days_of_salary_payment_period_2' => $request->input('basic_days_of_salary_payment_period_2'),
                'salary_amount_A_2' => $request->input('salary_amount_A_2'),
                'salary_amount_B_2' => $request->input('salary_amount_B_2'),
                'salary_amount_total_2' => $request->input('salary_amount_total_2'),
                'memo_2' => $request->input('memo_2'),
                'insured_period_start_month_3' => $request->input('insured_period_start_month_3'),
                'insured_period_start_day_3' => $request->input('insured_period_start_day_3'),
                'insured_period_end_month_3' => $request->input('insured_period_end_month_3'),
                'insured_period_end_day_3' => $request->input('insured_period_end_day_3'),
                'insured_period_month_3' => $request->input('insured_period_month_3'),
                'basic_days_for_salary_payment_of_insured_period_3' => $request->input('basic_days_for_salary_payment_of_insured_period_3'),
                'salary_payment_period_start_month_3' => $request->input('salary_payment_period_start_month_3'),
                'salary_payment_period_start_day_3' => $request->input('salary_payment_period_start_day_3'),
                'salary_payment_period_end_month_3' => $request->input('salary_payment_period_end_month_3'),
                'salary_payment_period_end_day_3' => $request->input('salary_payment_period_end_day_3'),
                'basic_days_of_salary_payment_period_3' => $request->input('basic_days_of_salary_payment_period_3'),
                'salary_amount_A_3' => $request->input('salary_amount_A_3'),
                'salary_amount_B_3' => $request->input('salary_amount_B_3'),
                'salary_amount_total_3' => $request->input('salary_amount_total_3'),
                'memo_3' => $request->input('memo_3'),
                'insured_period_start_month_4' => $request->input('insured_period_start_month_4'),
                'insured_period_start_day_4' => $request->input('insured_period_start_day_4'),
                'insured_period_end_month_4' => $request->input('insured_period_end_month_4'),
                'insured_period_end_day_4' => $request->input('insured_period_end_day_4'),
                'insured_period_month_4' => $request->input('insured_period_month_4'),
                'basic_days_for_salary_payment_of_insured_period_4' => $request->input('basic_days_for_salary_payment_of_insured_period_4'),
                'salary_payment_period_start_month_4' => $request->input('salary_payment_period_start_month_4'),
                'salary_payment_period_start_day_4' => $request->input('salary_payment_period_start_day_4'),
                'salary_payment_period_end_month_4' => $request->input('salary_payment_period_end_month_4'),
                'salary_payment_period_end_day_4' => $request->input('salary_payment_period_end_day_4'),
                'basic_days_of_salary_payment_period_4' => $request->input('basic_days_of_salary_payment_period_4'),
                'salary_amount_A_4' => $request->input('salary_amount_A_4'),
                'salary_amount_B_4' => $request->input('salary_amount_B_4'),
                'salary_amount_total_4' => $request->input('salary_amount_total_4'),
                'memo_4' => $request->input('memo_4'),
                'insured_period_start_month_5' => $request->input('insured_period_start_month_5'),
                'insured_period_start_day_5' => $request->input('insured_period_start_day_5'),
                'insured_period_end_month_5' => $request->input('insured_period_end_month_5'),
                'insured_period_end_day_5' => $request->input('insured_period_end_day_5'),
                'insured_period_month_5' => $request->input('insured_period_month_5'),
                'basic_days_for_salary_payment_of_insured_period_5' => $request->input('basic_days_for_salary_payment_of_insured_period_5'),
                'salary_payment_period_start_month_5' => $request->input('salary_payment_period_start_month_5'),
                'salary_payment_period_start_day_5' => $request->input('salary_payment_period_start_day_5'),
                'salary_payment_period_end_month_5' => $request->input('salary_payment_period_end_month_5'),
                'salary_payment_period_end_day_5' => $request->input('salary_payment_period_end_day_5'),
                'basic_days_of_salary_payment_period_5' => $request->input('basic_days_of_salary_payment_period_5'),
                'salary_amount_A_5' => $request->input('salary_amount_A_5'),
                'salary_amount_B_5' => $request->input('salary_amount_B_5'),
                'salary_amount_total_5' => $request->input('salary_amount_total_5'),
                'memo_5' => $request->input('memo_5'),
                'insured_period_start_month_6' => $request->input('insured_period_start_month_6'),
                'insured_period_start_day_6' => $request->input('insured_period_start_day_6'),
                'insured_period_end_month_6' => $request->input('insured_period_end_month_6'),
                'insured_period_end_day_6' => $request->input('insured_period_end_day_6'),
                'insured_period_month_6' => $request->input('insured_period_month_6'),
                'basic_days_for_salary_payment_of_insured_period_6' => $request->input('basic_days_for_salary_payment_of_insured_period_6'),
                'salary_payment_period_start_month_6' => $request->input('salary_payment_period_start_month_6'),
                'salary_payment_period_start_day_6' => $request->input('salary_payment_period_start_day_6'),
                'salary_payment_period_end_month_6' => $request->input('salary_payment_period_end_month_6'),
                'salary_payment_period_end_day_6' => $request->input('salary_payment_period_end_day_6'),
                'basic_days_of_salary_payment_period_6' => $request->input('basic_days_of_salary_payment_period_6'),
                'salary_amount_A_6' => $request->input('salary_amount_A_6'),
                'salary_amount_B_6' => $request->input('salary_amount_B_6'),
                'salary_amount_total_6' => $request->input('salary_amount_total_6'),
                'memo_6' => $request->input('memo_6'),
                'insured_period_start_month_7' => $request->input('insured_period_start_month_7'),
                'insured_period_start_day_7' => $request->input('insured_period_start_day_7'),
                'insured_period_end_month_7' => $request->input('insured_period_end_month_7'),
                'insured_period_end_day_7' => $request->input('insured_period_end_day_7'),
                'insured_period_month_7' => $request->input('insured_period_month_7'),
                'basic_days_for_salary_payment_of_insured_period_7' => $request->input('basic_days_for_salary_payment_of_insured_period_7'),
                'salary_payment_period_start_month_7' => $request->input('salary_payment_period_start_month_7'),
                'salary_payment_period_start_day_7' => $request->input('salary_payment_period_start_day_7'),
                'salary_payment_period_end_month_7' => $request->input('salary_payment_period_end_month_7'),
                'salary_payment_period_end_day_7' => $request->input('salary_payment_period_end_day_7'),
                'basic_days_of_salary_payment_period_7' => $request->input('basic_days_of_salary_payment_period_7'),
                'salary_amount_A_7' => $request->input('salary_amount_A_7'),
                'salary_amount_B_7' => $request->input('salary_amount_B_7'),
                'salary_amount_total_7' => $request->input('salary_amount_total_7'),
                'memo_7' => $request->input('memo_7'),
                'insured_period_start_month_8' => $request->input('insured_period_start_month_8'),
                'insured_period_start_day_8' => $request->input('insured_period_start_day_8'),
                'insured_period_end_month_8' => $request->input('insured_period_end_month_8'),
                'insured_period_end_day_8' => $request->input('insured_period_end_day_8'),
                'insured_period_month_8' => $request->input('insured_period_month_8'),
                'basic_days_for_salary_payment_of_insured_period_8' => $request->input('basic_days_for_salary_payment_of_insured_period_8'),
                'salary_payment_period_start_month_8' => $request->input('salary_payment_period_start_month_8'),
                'salary_payment_period_start_day_8' => $request->input('salary_payment_period_start_day_8'),
                'salary_payment_period_end_month_8' => $request->input('salary_payment_period_end_month_8'),
                'salary_payment_period_end_day_8' => $request->input('salary_payment_period_end_day_8'),
                'basic_days_of_salary_payment_period_8' => $request->input('basic_days_of_salary_payment_period_8'),
                'salary_amount_A_8' => $request->input('salary_amount_A_8'),
                'salary_amount_B_8' => $request->input('salary_amount_B_8'),
                'salary_amount_total_8' => $request->input('salary_amount_total_8'),
                'memo_8' => $request->input('memo_8'),
                'insured_period_start_month_9' => $request->input('insured_period_start_month_9'),
                'insured_period_start_day_9' => $request->input('insured_period_start_day_9'),
                'insured_period_end_month_9' => $request->input('insured_period_end_month_9'),
                'insured_period_end_day_9' => $request->input('insured_period_end_day_9'),
                'insured_period_month_9' => $request->input('insured_period_month_9'),
                'basic_days_for_salary_payment_of_insured_period_9' => $request->input('basic_days_for_salary_payment_of_insured_period_9'),
                'salary_payment_period_start_month_9' => $request->input('salary_payment_period_start_month_9'),
                'salary_payment_period_start_day_9' => $request->input('salary_payment_period_start_day_9'),
                'salary_payment_period_end_month_9' => $request->input('salary_payment_period_end_month_9'),
                'salary_payment_period_end_day_9' => $request->input('salary_payment_period_end_day_9'),
                'basic_days_of_salary_payment_period_9' => $request->input('basic_days_of_salary_payment_period_9'),
                'salary_amount_A_9' => $request->input('salary_amount_A_9'),
                'salary_amount_B_9' => $request->input('salary_amount_B_9'),
                'salary_amount_total_9' => $request->input('salary_amount_total_9'),
                'memo_9' => $request->input('memo_9'),
                'insured_period_start_month_10' => $request->input('insured_period_start_month_10'),
                'insured_period_start_day_10' => $request->input('insured_period_start_day_10'),
                'insured_period_end_month_10' => $request->input('insured_period_end_month_10'),
                'insured_period_end_day_10' => $request->input('insured_period_end_day_10'),
                'insured_period_month_10' => $request->input('insured_period_month_10'),
                'basic_days_for_salary_payment_of_insured_period_10' => $request->input('basic_days_for_salary_payment_of_insured_period_10'),
                'salary_payment_period_start_month_10' => $request->input('salary_payment_period_start_month_10'),
                'salary_payment_period_start_day_10' => $request->input('salary_payment_period_start_day_10'),
                'salary_payment_period_end_month_10' => $request->input('salary_payment_period_end_month_10'),
                'salary_payment_period_end_day_10' => $request->input('salary_payment_period_end_day_10'),
                'basic_days_of_salary_payment_period_10' => $request->input('basic_days_of_salary_payment_period_10'),
                'salary_amount_A_10' => $request->input('salary_amount_A_10'),
                'salary_amount_B_10' => $request->input('salary_amount_B_10'),
                'salary_amount_total_10' => $request->input('salary_amount_total_10'),
                'memo_10' => $request->input('memo_10'),
                'insured_period_start_month_11' => $request->input('insured_period_start_month_11'),
                'insured_period_start_day_11' => $request->input('insured_period_start_day_11'),
                'insured_period_end_month_11' => $request->input('insured_period_end_month_11'),
                'insured_period_end_day_11' => $request->input('insured_period_end_day_11'),
                'insured_period_month_11' => $request->input('insured_period_month_11'),
                'basic_days_for_salary_payment_of_insured_period_11' => $request->input('basic_days_for_salary_payment_of_insured_period_11'),
                'salary_payment_period_start_month_11' => $request->input('salary_payment_period_start_month_11'),
                'salary_payment_period_start_day_11' => $request->input('salary_payment_period_start_day_11'),
                'salary_payment_period_end_month_11' => $request->input('salary_payment_period_end_month_11'),
                'salary_payment_period_end_day_11' => $request->input('salary_payment_period_end_day_11'),
                'basic_days_of_salary_payment_period_11' => $request->input('basic_days_of_salary_payment_period_11'),
                'salary_amount_A_11' => $request->input('salary_amount_A_11'),
                'salary_amount_B_11' => $request->input('salary_amount_B_11'),
                'salary_amount_total_11' => $request->input('salary_amount_total_11'),
                'memo_11' => $request->input('memo_11'),
                'insured_period_start_month_12' => $request->input('insured_period_start_month_12'),
                'insured_period_start_day_12' => $request->input('insured_period_start_day_12'),
                'insured_period_end_month_12' => $request->input('insured_period_end_month_12'),
                'insured_period_end_day_12' => $request->input('insured_period_end_day_12'),
                'insured_period_month_12' => $request->input('insured_period_month_12'),
                'basic_days_for_salary_payment_of_insured_period_12' => $request->input('basic_days_for_salary_payment_of_insured_period_12'),
                'salary_payment_period_start_month_12' => $request->input('salary_payment_period_start_month_12'),
                'salary_payment_period_start_day_12' => $request->input('salary_payment_period_start_day_12'),
                'salary_payment_period_end_month_12' => $request->input('salary_payment_period_end_month_12'),
                'salary_payment_period_end_day_12' => $request->input('salary_payment_period_end_day_12'),
                'basic_days_of_salary_payment_period_12' => $request->input('basic_days_of_salary_payment_period_12'),
                'salary_amount_A_12' => $request->input('salary_amount_A_12'),
                'salary_amount_B_12' => $request->input('salary_amount_B_12'),
                'salary_amount_total_12' => $request->input('salary_amount_total_12'),
                'memo_12' => $request->input('memo_12'),
                'insured_period_start_month_13' => $request->input('insured_period_start_month_13'),
                'insured_period_start_day_13' => $request->input('insured_period_start_day_13'),
                'insured_period_end_month_13' => $request->input('insured_period_end_month_13'),
                'insured_period_end_day_13' => $request->input('insured_period_end_day_13'),
                'insured_period_month_13' => $request->input('insured_period_month_13'),
                'basic_days_for_salary_payment_of_insured_period_13' => $request->input('basic_days_for_salary_payment_of_insured_period_13'),
                'salary_payment_period_start_month_13' => $request->input('salary_payment_period_start_month_13'),
                'salary_payment_period_start_day_13' => $request->input('salary_payment_period_start_day_13'),
                'salary_payment_period_end_month_13' => $request->input('salary_payment_period_end_month_13'),
                'salary_payment_period_end_day_13' => $request->input('salary_payment_period_end_day_13'),
                'basic_days_of_salary_payment_period_13' => $request->input('basic_days_of_salary_payment_period_13'),
                'salary_amount_A_13' => $request->input('salary_amount_A_13'),
                'salary_amount_B_13' => $request->input('salary_amount_B_13'),
                'salary_amount_total_13' => $request->input('salary_amount_total_13'),
                'memo_13' => $request->input('memo_13'),
                'insured_period_start_month_14' => $request->input('insured_period_start_month_14'),
                'insured_period_start_day_14' => $request->input('insured_period_start_day_14'),
                'insured_period_end_month_14' => $request->input('insured_period_end_month_14'),
                'insured_period_end_day_14' => $request->input('insured_period_end_day_14'),
                'insured_period_month_14' => $request->input('insured_period_month_14'),
                'basic_days_for_salary_payment_of_insured_period_14' => $request->input('basic_days_for_salary_payment_of_insured_period_14'),
                'salary_payment_period_start_month_14' => $request->input('salary_payment_period_start_month_14'),
                'salary_payment_period_start_day_14' => $request->input('salary_payment_period_start_day_14'),
                'salary_payment_period_end_month_14' => $request->input('salary_payment_period_end_month_14'),
                'salary_payment_period_end_day_14' => $request->input('salary_payment_period_end_day_14'),
                'basic_days_of_salary_payment_period_14' => $request->input('basic_days_of_salary_payment_period_14'),
                'salary_amount_A_14' => $request->input('salary_amount_A_14'),
                'salary_amount_B_14' => $request->input('salary_amount_B_14'),
                'salary_amount_total_14' => $request->input('salary_amount_total_14'),
                'memo_14' => $request->input('memo_14'),
                'insured_period_start_month_15' => $request->input('insured_period_start_month_15'),
                'insured_period_start_day_15' => $request->input('insured_period_start_day_15'),
                'insured_period_end_month_15' => $request->input('insured_period_end_month_15'),
                'insured_period_end_day_15' => $request->input('insured_period_end_day_15'),
                'insured_period_month_15' => $request->input('insured_period_month_15'),
                'basic_days_for_salary_payment_of_insured_period_15' => $request->input('basic_days_for_salary_payment_of_insured_period_15'),
                'salary_payment_period_start_month_15' => $request->input('salary_payment_period_start_month_15'),
                'salary_payment_period_start_day_15' => $request->input('salary_payment_period_start_day_15'),
                'salary_payment_period_end_month_15' => $request->input('salary_payment_period_end_month_15'),
                'salary_payment_period_end_day_15' => $request->input('salary_payment_period_end_day_15'),
                'basic_days_of_salary_payment_period_15' => $request->input('basic_days_of_salary_payment_period_15'),
                'salary_amount_A_15' => $request->input('salary_amount_A_15'),
                'salary_amount_B_15' => $request->input('salary_amount_B_15'),
                'salary_amount_total_15' => $request->input('salary_amount_total_15'),
                'memo_15' => $request->input('memo_15'),
                'insured_period_start_month_16' => $request->input('insured_period_start_month_16'),
                'insured_period_start_day_16' => $request->input('insured_period_start_day_16'),
                'insured_period_end_month_16' => $request->input('insured_period_end_month_16'),
                'insured_period_end_day_16' => $request->input('insured_period_end_day_16'),
                'insured_period_month_16' => $request->input('insured_period_month_16'),
                'basic_days_for_salary_payment_of_insured_period_16' => $request->input('basic_days_for_salary_payment_of_insured_period_16'),
                'salary_payment_period_start_month_16' => $request->input('salary_payment_period_start_month_16'),
                'salary_payment_period_start_day_16' => $request->input('salary_payment_period_start_day_16'),
                'salary_payment_period_end_month_16' => $request->input('salary_payment_period_end_month_16'),
                'salary_payment_period_end_day_16' => $request->input('salary_payment_period_end_day_16'),
                'basic_days_of_salary_payment_period_16' => $request->input('basic_days_of_salary_payment_period_16'),
                'salary_amount_A_16' => $request->input('salary_amount_A_16'),
                'salary_amount_B_16' => $request->input('salary_amount_B_16'),
                'salary_amount_total_16' => $request->input('salary_amount_total_16'),
                'memo_16' => $request->input('memo_16'),
                'insured_period_start_month_17' => $request->input('insured_period_start_month_17'),
                'insured_period_start_day_17' => $request->input('insured_period_start_day_17'),
                'insured_period_end_month_17' => $request->input('insured_period_end_month_17'),
                'insured_period_end_day_17' => $request->input('insured_period_end_day_17'),
                'insured_period_month_17' => $request->input('insured_period_month_17'),
                'basic_days_for_salary_payment_of_insured_period_17' => $request->input('basic_days_for_salary_payment_of_insured_period_17'),
                'salary_payment_period_start_month_17' => $request->input('salary_payment_period_start_month_17'),
                'salary_payment_period_start_day_17' => $request->input('salary_payment_period_start_day_17'),
                'salary_payment_period_end_month_17' => $request->input('salary_payment_period_end_month_17'),
                'salary_payment_period_end_day_17' => $request->input('salary_payment_period_end_day_17'),
                'basic_days_of_salary_payment_period_17' => $request->input('basic_days_of_salary_payment_period_17'),
                'salary_amount_A_17' => $request->input('salary_amount_A_17'),
                'salary_amount_B_17' => $request->input('salary_amount_B_17'),
                'salary_amount_total_17' => $request->input('salary_amount_total_17'),
                'memo_17' => $request->input('memo_17'),
                'insured_period_start_month_18' => $request->input('insured_period_start_month_18'),
                'insured_period_start_day_18' => $request->input('insured_period_start_day_18'),
                'insured_period_end_month_18' => $request->input('insured_period_end_month_18'),
                'insured_period_end_day_18' => $request->input('insured_period_end_day_18'),
                'insured_period_month_18' => $request->input('insured_period_month_18'),
                'basic_days_for_salary_payment_of_insured_period_18' => $request->input('basic_days_for_salary_payment_of_insured_period_18'),
                'salary_payment_period_start_month_18' => $request->input('salary_payment_period_start_month_18'),
                'salary_payment_period_start_day_18' => $request->input('salary_payment_period_start_day_18'),
                'salary_payment_period_end_month_18' => $request->input('salary_payment_period_end_month_18'),
                'salary_payment_period_end_day_18' => $request->input('salary_payment_period_end_day_18'),
                'basic_days_of_salary_payment_period_18' => $request->input('basic_days_of_salary_payment_period_18'),
                'salary_amount_A_18' => $request->input('salary_amount_A_18'),
                'salary_amount_B_18' => $request->input('salary_amount_B_18'),
                'salary_amount_total_18' => $request->input('salary_amount_total_18'),
                'memo_18' => $request->input('memo_18'),
                'insured_period_start_month_19' => $request->input('insured_period_start_month_19'),
                'insured_period_start_day_19' => $request->input('insured_period_start_day_19'),
                'insured_period_end_month_19' => $request->input('insured_period_end_month_19'),
                'insured_period_end_day_19' => $request->input('insured_period_end_day_19'),
                'insured_period_month_19' => $request->input('insured_period_month_19'),
                'basic_days_for_salary_payment_of_insured_period_19' => $request->input('basic_days_for_salary_payment_of_insured_period_19'),
                'salary_payment_period_start_month_19' => $request->input('salary_payment_period_start_month_19'),
                'salary_payment_period_start_day_19' => $request->input('salary_payment_period_start_day_19'),
                'salary_payment_period_end_month_19' => $request->input('salary_payment_period_end_month_19'),
                'salary_payment_period_end_day_19' => $request->input('salary_payment_period_end_day_19'),
                'basic_days_of_salary_payment_period_19' => $request->input('basic_days_of_salary_payment_period_19'),
                'salary_amount_A_19' => $request->input('salary_amount_A_19'),
                'salary_amount_B_19' => $request->input('salary_amount_B_19'),
                'salary_amount_total_19' => $request->input('salary_amount_total_19'),
                'memo_19' => $request->input('memo_19'),
                'insured_period_start_month_20' => $request->input('insured_period_start_month_20'),
                'insured_period_start_day_20' => $request->input('insured_period_start_day_20'),
                'insured_period_end_month_20' => $request->input('insured_period_end_month_20'),
                'insured_period_end_day_20' => $request->input('insured_period_end_day_20'),
                'insured_period_month_20' => $request->input('insured_period_month_20'),
                'basic_days_for_salary_payment_of_insured_period_20' => $request->input('basic_days_for_salary_payment_of_insured_period_20'),
                'salary_payment_period_start_month_20' => $request->input('salary_payment_period_start_month_20'),
                'salary_payment_period_start_day_20' => $request->input('salary_payment_period_start_day_20'),
                'salary_payment_period_end_month_20' => $request->input('salary_payment_period_end_month_20'),
                'salary_payment_period_end_day_20' => $request->input('salary_payment_period_end_day_20'),
                'basic_days_of_salary_payment_period_20' => $request->input('basic_days_of_salary_payment_period_20'),
                'salary_amount_A_20' => $request->input('salary_amount_A_20'),
                'salary_amount_B_20' => $request->input('salary_amount_B_20'),
                'salary_amount_total_20' => $request->input('salary_amount_total_20'),
                'memo_20' => $request->input('memo_20'),
                'insured_period_start_month_21' => $request->input('insured_period_start_month_21'),
                'insured_period_start_day_21' => $request->input('insured_period_start_day_21'),
                'insured_period_end_month_21' => $request->input('insured_period_end_month_21'),
                'insured_period_end_day_21' => $request->input('insured_period_end_day_21'),
                'insured_period_month_21' => $request->input('insured_period_month_21'),
                'basic_days_for_salary_payment_of_insured_period_21' => $request->input('basic_days_for_salary_payment_of_insured_period_21'),
                'salary_payment_period_start_month_21' => $request->input('salary_payment_period_start_month_21'),
                'salary_payment_period_start_day_21' => $request->input('salary_payment_period_start_day_21'),
                'salary_payment_period_end_month_21' => $request->input('salary_payment_period_end_month_21'),
                'salary_payment_period_end_day_21' => $request->input('salary_payment_period_end_day_21'),
                'basic_days_of_salary_payment_period_21' => $request->input('basic_days_of_salary_payment_period_21'),
                'salary_amount_A_21' => $request->input('salary_amount_A_21'),
                'salary_amount_B_21' => $request->input('salary_amount_B_21'),
                'salary_amount_total_21' => $request->input('salary_amount_total_21'),
                'memo_21' => $request->input('memo_21'),
                'insured_period_start_month_22' => $request->input('insured_period_start_month_22'),
                'insured_period_start_day_22' => $request->input('insured_period_start_day_22'),
                'insured_period_end_month_22' => $request->input('insured_period_end_month_22'),
                'insured_period_end_day_22' => $request->input('insured_period_end_day_22'),
                'insured_period_month_22' => $request->input('insured_period_month_22'),
                'basic_days_for_salary_payment_of_insured_period_22' => $request->input('basic_days_for_salary_payment_of_insured_period_22'),
                'salary_payment_period_start_month_22' => $request->input('salary_payment_period_start_month_22'),
                'salary_payment_period_start_day_22' => $request->input('salary_payment_period_start_day_22'),
                'salary_payment_period_end_month_22' => $request->input('salary_payment_period_end_month_22'),
                'salary_payment_period_end_day_22' => $request->input('salary_payment_period_end_day_22'),
                'basic_days_of_salary_payment_period_22' => $request->input('basic_days_of_salary_payment_period_22'),
                'salary_amount_A_22' => $request->input('salary_amount_A_22'),
                'salary_amount_B_22' => $request->input('salary_amount_B_22'),
                'salary_amount_total_22' => $request->input('salary_amount_total_22'),
                'memo_22' => $request->input('memo_22'),
                'insured_period_start_month_23' => $request->input('insured_period_start_month_23'),
                'insured_period_start_day_23' => $request->input('insured_period_start_day_23'),
                'insured_period_end_month_23' => $request->input('insured_period_end_month_23'),
                'insured_period_end_day_23' => $request->input('insured_period_end_day_23'),
                'insured_period_month_23' => $request->input('insured_period_month_23'),
                'basic_days_for_salary_payment_of_insured_period_23' => $request->input('basic_days_for_salary_payment_of_insured_period_23'),
                'salary_payment_period_start_month_23' => $request->input('salary_payment_period_start_month_23'),
                'salary_payment_period_start_day_23' => $request->input('salary_payment_period_start_day_23'),
                'salary_payment_period_end_month_23' => $request->input('salary_payment_period_end_month_23'),
                'salary_payment_period_end_day_23' => $request->input('salary_payment_period_end_day_23'),
                'basic_days_of_salary_payment_period_23' => $request->input('basic_days_of_salary_payment_period_23'),
                'salary_amount_A_23' => $request->input('salary_amount_A_23'),
                'salary_amount_B_23' => $request->input('salary_amount_B_23'),
                'salary_amount_total_23' => $request->input('salary_amount_total_23'),
                'memo_23' => $request->input('memo_23'),
                'insured_period_start_month_24' => $request->input('insured_period_start_month_24'),
                'insured_period_start_day_24' => $request->input('insured_period_start_day_24'),
                'insured_period_end_month_24' => $request->input('insured_period_end_month_24'),
                'insured_period_end_day_24' => $request->input('insured_period_end_day_24'),
                'insured_period_month_24' => $request->input('insured_period_month_24'),
                'basic_days_for_salary_payment_of_insured_period_24' => $request->input('basic_days_for_salary_payment_of_insured_period_24'),
                'salary_payment_period_start_month_24' => $request->input('salary_payment_period_start_month_24'),
                'salary_payment_period_start_day_24' => $request->input('salary_payment_period_start_day_24'),
                'salary_payment_period_end_month_24' => $request->input('salary_payment_period_end_month_24'),
                'salary_payment_period_end_day_24' => $request->input('salary_payment_period_end_day_24'),
                'basic_days_of_salary_payment_period_24' => $request->input('basic_days_of_salary_payment_period_24'),
                'salary_amount_A_24' => $request->input('salary_amount_A_24'),
                'salary_amount_B_24' => $request->input('salary_amount_B_24'),
                'salary_amount_total_24' => $request->input('salary_amount_total_24'),
                'memo_24' => $request->input('memo_24'),
                'salary_notices' => $request->input('salary_notices'),
                'salary_notices_1' => $request->input('salary_notices_1'),
                'remarks' => $request->input('remarks'),
                'remarks_1' => $request->input('remarks_1'),
                'retirement_age' => $request->input('retirement_age'),
                'retirement_reason' => $request->input('retirement_reason'),
                'contract_period_reached_limit_contract_period_once' => $request->input('contract_period_reached_limit_contract_period_once'),
                'contract_period_reached_limit_contract_period_total' => $request->input('contract_period_reached_limit_contract_period_total'),
                'contract_period_reached_limit_contract_renewal_count' => $request->input('contract_period_reached_limit_contract_renewal_count'),
                'eternal_hire_contract_period_once' => $request->input('eternal_hire_contract_period_once'),
                'eternal_hire_contract_period_total' => $request->input('eternal_hire_contract_period_total'),
                'eternal_hire_contract_period_once' => $request->input('eternal_hire_contract_period_once'),
                'except_eternal_hire_contract_period_once' => $request->input('except_eternal_hire_contract_period_once'),
                'except_eternal_hire_contract_period_total' => $request->input('except_eternal_hire_contract_period_total'),
                'except_eternal_hire_contract_period_renewal_count' => $request->input('except_eternal_hire_contract_renewal_count'),
                'retirement_recommendation_reason' => $request->input('retirement_recommendation_reason'),
                'change_office_place' => $request->input('change_office_place'),
                'employee_decision_reasons' => $request->input('employee_decision_reasons'),
                'other_reasons' => $request->input('other_reasons'),
                'memo_for_employer' => $request->input('memo_for_employer'),
                'shortened_contract_renewal_reached_limit_flg' => $request->input('shortened_contract_renewal_reached_limit_flg'),
                'contract_renewal_reached_limit_flg' => $request->input('contract_renewal_reached_limit_flg'),
                'rehire_contract_renewal_reached_limit_flg' => $request->input('rehire_contract_renewal_reached_limit_flg'),
                'contract_period_total_reached_limit_flg' => $request->input('contract_period_total_reached_limit_flg'),
                'contract_period_total_established_before_law_amendment_flg' => $request->input('contract_period_total_established_before_law_amendment_flg'),
                'eternal_hire_contract_renewal_guarantee_agreement_flg' => $request->input('eternal_hire_contract_renewal_guarantee_agreement_flg'),
                'contract_non_renewal_flg' => $request->input('contract_non_renewal_flg'),
                'employment_termination_notice_flg' => $request->input('employment_termination_notice_flg'),
                'non_renewal_clause_addition_flg' => $request->input('non_renewal_clause_addition_flg'),
                'eternal_hire_contract_renewal_request_type' => $request->input('eternal_hire_contract_renewal_request_type'),
                'contract_renewal_guarantee_agreement_flg' => $request->input('contract_renewal_guarantee_agreement_flg'),
                'no_contract_renewal_flg' => $request->input('no_contract_renewal_flg'),
                'contract_renewal_request_type' => $request->input('contract_renewal_request_type'),
                'employment_instructions_type' => $request->input('employment_instructions_type'),
                'education_training_flg' => $request->input('education_training_flg'),
                'objection_retirement_reason_flg' => $request->input('objection_retirement_reason_flg'),
                'dispatched_employee_flg' => $request->input('dispatched_employee_flg'),
                'reemployment_request_flg' => $request->input('reemployment_request_flg'),
                'retirement_reason_type' => $request->input('retirement_reason_type'),
                'apply_to_code' => $request->input('apply_to_code'),
                'apply_to_name' => $request->input('apply_to_name')
            ];
            $XML = new MixXmlEgovSigner($request);
            $response = $XML->run($request);
            if ($response[0] == false) {
                $errorMessage = $response[1];
                return redirect()->back()->withErrors($errorMessage)->withInput();
            }
            return view('admin.companies', ['send_data' => $data]);
        } catch (ValidationException $e) {
            return redirect()->back()->withErrors($e->errors())->withInput();
        }
    }
}
