<?php

namespace App\Http\Controllers\Ledger;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use App\Http\Requests\FirstParentalLeaveBenefitsForEmploymentInsuranceRequest;
use App\EgovAPI\MixXmlEgovSigner;
use App\Models\CurrentUser;
use App\Models\Certificate;
use App\Models\Branch;
use App\Permission;
use App\Models\Employee;

class FirstParentalLeaveBenefitsForEmploymentInsuranceController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware(function ($request, $next) {
            $userPermission = new Permission;
            if (!$userPermission->isSelectedCompany() || $userPermission->denyProcedure() || !$userPermission->isReadableFor(8) || !$userPermission->isWritableFor(8) || !$userPermission->isBasicDepartment()) {

                return redirect()->route('home.index');
            }
            return $next($request);
        });
    }

    public function index(Request $request)
    {
        if (!$this->isSelectedCompany()) {
            return redirect()->route('home.select');
        }

        $company = CurrentUser::currentCompany();
        $companyId = $company->id;
        $certificate = Certificate::where('company_id', $companyId)
            ->where('delete_flg', 0)
            ->first();
        if ($certificate !== null) {
            $certificate = true;
        } else {
            $certificate = false;
        }
        $current_employee = CurrentUser::info();
        $current_branch = Branch::where('id', $current_employee->branch_id)->first();

        $japanEra = '令和';
        $year = date("Y");
        $japanEraYear = $year - 2018;
        $month = ltrim(date("m"), '0');
        $day = ltrim(date("d"), '0');
        $todaySet = array(
            "japanEra" => $japanEra,
            "japanEraYear" => $japanEraYear,
            "year" => $year,
            "month" => $month,
            "day" => $day
        );
        $egovAcount = $this->egovAcount();
        $procedureName = $this->getProcedureName($request);
        $existPresident = Employee::whereHas('branch', function ($query) use ($companyId) {
            $query->where('company_id', $companyId);
        })
            ->where('employee_type', 1)
            ->where('delete_flg', 0)
            ->exists();

        return view('ledger.first_parental_leave_benefits_for_employment_insurance', [
            'company' => $company,
            'todaySet' => $todaySet,
            'certificate' => $certificate,
            'procedureName' => $procedureName,
            'current_employee' => $current_employee,
            'egovAcount' => $egovAcount,
            'current_branch' => $current_branch,
            'existPresident' => $existPresident
        ]);
    }

    public function post(FirstParentalLeaveBenefitsForEmploymentInsuranceRequest $request)
    {
        $attachment = [];

        $data = $request->all();

        foreach ($data as $key => $value) {
            if (strpos($key, 'radio_') === 0) {
                $file_key = substr($key, strlen('radio_'));
                $label_key = ($file_key === 'file_other') ? 'input_file_other' : 'label_' . $file_key;

                $attachment_type = ($value === '2') ? '添付' : '別送';

                $attached_document_name = $request->input($label_key);

                $attachment_file_name = '';
                if ($value === '2' && $request->hasFile($file_key)) {
                    $file = $request->file($file_key);
                    $attachment_file_name = $file->getClientOriginalName();
                }

                $attachment[] = [
                    'attachment_type' => $attachment_type,
                    'attached_document_name' => $attached_document_name,
                    'attachment_file_name' => $attachment_file_name,
                    'submission_info' => '1'
                ];
            }
        }

        if (!empty($attachment)) {
            $request->merge(['attachment' => $attachment]);
        }

        $radio_keys = ["radio_file_childcare", "radio_file_wage_amount", "radio_file_wage_certificate", "radio_file_confirmation_document", "radio_file_passbook", "radio_file_extension_reason", "radio_file_spouse", "radio_file_spouse_childcare_leave", "radio_file_other"];

        foreach ($radio_keys as $key) {
            if (!$request->has($key)) {
                $request->merge([$key => 0]);
            }
        }

        try {
            $data = [
                'note' => $request->input('note'),
                'ledger_type' => $request->input('ledger_type'),
                'employment_insured_no_4digit' => $request->input('employment_insured_no_4digit'),
                'employment_insured_no_6digit' => $request->input('employment_insured_no_6digit'),
                'employment_insured_no_CD' => $request->input('employment_insured_no_CD'),
                'qualifications_japan_era' => $request->input('qualifications_japan_era'),
                'qualifications_japan_era_year' => $request->input('qualifications_japan_era_year'),
                'qualifications_month' => $request->input('qualifications_month'),
                'qualifications_day' => $request->input('qualifications_day'),
                'fullname' => $request->input('fullname'),
                'fullname_kana' => $request->input('fullname_kana'),
                'employment_insurance_office_no_4digit' => $request->input('employment_insurance_office_no_4digit'),
                'employment_insurance_office_no_6digit' => $request->input('employment_insurance_office_no_6digit'),
                'employment_insurance_office_no_CD' => $request->input('employment_insurance_office_no_CD'),
                'childcare_start_date_japan_era' => $request->input('childcare_start_date_japan_era'),
                'childcare_start_date_japan_era_year' => $request->input('childcare_start_date_japan_era_year'),
                'childcare_start_date_month' => $request->input('childcare_start_date_month'),
                'childcare_start_date_day' => $request->input('childcare_start_date_day'),
                'birth_date_japan_era' => $request->input('birth_date_japan_era'),
                'birth_date_japan_era_year' => $request->input('birth_date_japan_era_year'),
                'birth_date_month' => $request->input('birth_date_month'),
                'birth_date_day' => $request->input('birth_date_day'),
                'birth_due_date_japan_era' => $request->input('birth_due_date_japan_era'),
                'birth_due_date_japan_era_year' => $request->input('birth_due_date_japan_era_year'),
                'birth_due_date_month' => $request->input('birth_due_date_month'),
                'birth_due_date_day' => $request->input('birth_due_date_day'),
                'mynumber_card_no' => $request->input('mynumber_card_no'),
                'post_code_former' => $request->input('post_code_former'),
                'post_code_latter' => $request->input('post_code_latter'),
                'tel_area_code' => $request->input('tel_area_code'),
                'tel_city_code' => $request->input('tel_city_code'),
                'tel_subscriber_code' => $request->input('tel_subscriber_code'),
                'address_prefecture_city' => $request->input('address_prefecture_city'),
                'address_ward' => $request->input('address_ward'),
                'address_apartment' => $request->input('address_apartment'),
                'payer_japan_era1' => $request->input('payer_japan_era1'),
                'payer_japan_era_year1' => $request->input('payer_japan_era_year1'),
                'payer_month1' => $request->input('payer_month1'),
                'payer_day1' => $request->input('payer_day1'),
                'payer_month_end1' => $request->input('payer_month_end1'),
                'payer_day_end1' => $request->input('payer_day_end1'),
                'workday_count1' => $request->input('workday_count1'),
                'working_hours1' => $request->input('working_hours1'),
                'wages_paid1' => $request->input('wages_paid1'),
                'payer_japan_era2' => $request->input('payer_japan_era2'),
                'payer_japan_era_year2' => $request->input('payer_japan_era_year2'),
                'payer_month2' => $request->input('payer_month2'),
                'payer_day2' => $request->input('payer_day2'),
                'payer_month_end2' => $request->input('payer_month_end2'),
                'payer_day_end2' => $request->input('payer_day_end2'),
                'workday_count2' => $request->input('workday_count2'),
                'working_hours2' => $request->input('working_hours2'),
                'wages_paid2' => $request->input('wages_paid2'),
                'payment_period_last_japan_era' => $request->input('payment_period_last_japan_era'),
                'payment_period_last_japan_era_year' => $request->input('payment_period_last_japan_era_year'),
                'payment_period_last_month' => $request->input('payment_period_last_month'),
                'payment_period_last_day' => $request->input('payment_period_last_day'),
                'payment_period_last_month_end' => $request->input('payment_period_last_month_end'),
                'payment_period_last_day_end' => $request->input('payment_period_last_day_end'),
                'workday_count3' => $request->input('workday_count3'),
                'working_hours3' => $request->input('working_hours3'),
                'wages_paid3' => $request->input('wages_paid3'),
                'return_from_resignation_date_japan_era' => $request->input('return_from_resignation_date_japan_era'),
                'return_from_resignation_date_japan_era_year' => $request->input('return_from_resignation_date_japan_era_year'),
                'return_from_resignation_date_month' => $request->input('return_from_resignation_date_month'),
                'return_from_resignation_date_day' => $request->input('return_from_resignation_date_day'),
                'payment_period_extension_reason' => $request->input('payment_period_extension_reason'),
                'payment_period_extension_reason_japan_era' => $request->input('payment_period_extension_reason_japan_era'),
                'payment_period_extension_reason_japan_era_year' => $request->input('payment_period_extension_reason_japan_era_year'),
                'payment_period_extension_reason_month' => $request->input('payment_period_extension_reason_month'),
                'payment_period_extension_reason_day' => $request->input('payment_period_extension_reason_day'),
                'payment_period_extension_reason_last_month' => $request->input('payment_period_extension_reason_last_month'),
                'payment_period_extension_reason_last_day' => $request->input('payment_period_extension_reason_last_day'),
                'partner_childcare_leave_taken' => $request->input('partner_childcare_leave_taken'),
                'partner_insured_no_4digit' => $request->input('partner_insured_no_4digit'),
                'partner_insured_no_6digit' => $request->input('partner_insured_no_6digit'),
                'partner_insured_no_CD' => $request->input('partner_insured_no_CD'),
                'today_japan_era' => $request->input('today_japan_era'),
                'today_japan_era_year' => $request->input('today_japan_era_year'),
                'today_japan_era_month' => $request->input('today_japan_era_month'),
                'today_japan_era_day' => $request->input('today_japan_era_day'),
                'headquarters_address' => $request->input('headquarters_address'),
                'headquarters_tel_treacode' => $request->input('headquarters_tel_treacode'),
                'headquarters_tel_city_code' => $request->input('headquarters_tel_city_code'),
                'headquarters_tel_subscriber_code' => $request->input('headquarters_tel_subscriber_code'),
                'employer_company_managerial_position_name' => $request->input('employer_company_managerial_position_name'),
                'destination' => $request->input('destination'),
                'financial_institution_name' => $request->input('financial_institution_name'),
                'financia_iInstitution_code' => $request->input('financia_iInstitution_code'),
                'store_code' => $request->input('store_code'),
                'passbook_account_number' => $request->input('passbook_account_number'),
                'yucho_bank_former' => $request->input('yucho_bank_former'),
                'yucho_bank_latter' => $request->input('yucho_bank_latter'),
                'wage_deadline' => $request->input('wage_deadline'),
                'wage_payment' => $request->input('wage_payment'),
                'wage_payment_day' => $request->input('wage_payment_day'),
                'commuting_allowance_period' => $request->input('commuting_allowance_period'),
                'commuting_allowance_period_other' => $request->input('commuting_allowance_period_other'),
                'labor_consultant_acting_as_agent_name' => $request->input('labor_consultant_acting_as_agent_name'),
                'labor_consultant_name' => $request->input('labor_consultant_name'),
                'labor_consultant_tel_treacode' => $request->input('labor_consultant_tel_treacode'),
                'labor_consultant_tel_city_code' => $request->input('labor_consultant_tel_city_code'),
                'labor_consultant_tel_subscriber_code' => $request->input('labor_consultant_tel_subscriber_code'),
                'financial_Institutions_name_kana' => $request->input('financial_Institutions_name_kana'),
                'childcare_leave_reacquisition_cause' => $request->input('childcare_leave_reacquisition_cause'),
                'branch_name' => $request->input('branch_name'),
                'branch_address' => $request->input('branch_address'),
                'branch_tel_treacode' => $request->input('branch_tel_treacode'),
                'special_note_on_wages1' => $request->input('special_note_on_wages1'),
                'calculation_duration_start_month1_1' => $request->input('calculation_duration_start_month1_1'),
                'calculation_duration_start_day1_1' => $request->input('calculation_duration_start_day1_1'),
                'calculation_duration_end_month1_1' => $request->input('calculation_duration_end_month1_1'),
                'calculation_duration_end_day1_1' => $request->input('calculation_duration_end_day1_1'),
                'calculation_duration_basic_days' => $request->input('calculation_duration_basic_days'),
                'branch_tel_city_code' => $request->input('branch_tel_city_code'),
                'branch_tel_subscriber_code' => $request->input('branch_tel_subscriber_code'),
                'calculation_duration_start_month1_2' => $request->input('calculation_duration_start_month1_2'),
                'calculation_duration_start_day1_2' => $request->input('calculation_duration_start_day1_2'),
                'calculation_duration_end_month1_2' => $request->input('calculation_duration_end_month1_2'),
                'calculation_duration_end_day1_2' => $request->input('calculation_duration_end_day1_2'),
                'calculation_duration_start_month1_3' => $request->input('calculation_duration_start_month1_3'),
                'calculation_duration_start_day1_3' => $request->input('calculation_duration_start_day1_3'),
                'calculation_duration_end_month1_3' => $request->input('calculation_duration_end_month1_3'),
                'calculation_duration_end_day1_3' => $request->input('calculation_duration_end_day1_3'),
                'calculation_duration_start_month1_4' => $request->input('calculation_duration_start_month1_4'),
                'calculation_duration_start_day1_4' => $request->input('calculation_duration_start_day1_4'),
                'calculation_duration_end_month1_4' => $request->input('calculation_duration_end_month1_4'),
                'calculation_duration_end_day1_4' => $request->input('calculation_duration_end_day1_4'),
                'calculation_duration_start_month1_5' => $request->input('calculation_duration_start_month1_5'),
                'calculation_duration_start_day1_5' => $request->input('calculation_duration_start_day1_5'),
                'calculation_duration_end_month1_5' => $request->input('calculation_duration_end_month1_5'),
                'calculation_duration_end_day1_5' => $request->input('calculation_duration_end_day1_5'),
                'calculation_duration_start_month1_6' => $request->input('calculation_duration_start_month1_6'),
                'calculation_duration_start_day1_6' => $request->input('calculation_duration_start_day1_6'),
                'calculation_duration_end_month1_6' => $request->input('calculation_duration_end_month1_6'),
                'calculation_duration_end_day1_6' => $request->input('calculation_duration_end_day1_6'),
                'calculation_duration_start_month1_7' => $request->input('calculation_duration_start_month1_7'),
                'calculation_duration_start_day1_7' => $request->input('calculation_duration_start_day1_7'),
                'calculation_duration_end_month1_7' => $request->input('calculation_duration_end_month1_7'),
                'calculation_duration_end_day1_7' => $request->input('calculation_duration_end_day1_7'),
                'calculation_duration_start_month1_8' => $request->input('calculation_duration_start_month1_8'),
                'calculation_duration_start_day1_8' => $request->input('calculation_duration_start_day1_8'),
                'calculation_duration_end_month1_8' => $request->input('calculation_duration_end_month1_8'),
                'calculation_duration_end_day1_8' => $request->input('calculation_duration_end_day1_8'),
                'calculation_duration_start_month1_9' => $request->input('calculation_duration_start_month1_9'),
                'calculation_duration_start_day1_9' => $request->input('calculation_duration_start_day1_9'),
                'calculation_duration_end_month1_9' => $request->input('calculation_duration_end_month1_9'),
                'calculation_duration_end_day1_9' => $request->input('calculation_duration_end_day1_9'),
                'calculation_duration_start_month1_10' => $request->input('calculation_duration_start_month1_10'),
                'calculation_duration_start_day1_10' => $request->input('calculation_duration_start_day1_10'),
                'calculation_duration_end_month1_10' => $request->input('calculation_duration_end_month1_10'),
                'calculation_duration_end_day1_10' => $request->input('calculation_duration_end_day1_10'),
                'calculation_duration_start_month1_11' => $request->input('calculation_duration_start_month1_11'),
                'calculation_duration_start_day1_11' => $request->input('calculation_duration_start_day1_11'),
                'calculation_duration_end_month1_11' => $request->input('calculation_duration_end_month1_11'),
                'calculation_duration_end_day1_11' => $request->input('calculation_duration_end_day1_11'),
                'calculation_duration_start_month1_12' => $request->input('calculation_duration_start_month1_12'),
                'calculation_duration_start_day1_12' => $request->input('calculation_duration_start_day1_12'),
                'calculation_duration_end_month1_12' => $request->input('calculation_duration_end_month1_12'),
                'calculation_duration_end_day1_12' => $request->input('calculation_duration_end_day1_12'),
                'calculation_duration_start_month1_13' => $request->input('calculation_duration_start_month1_13'),
                'calculation_duration_start_day1_13' => $request->input('calculation_duration_start_day1_13'),
                'calculation_duration_end_month1_13' => $request->input('calculation_duration_end_month1_13'),
                'calculation_duration_end_day1_13' => $request->input('calculation_duration_end_day1_13'),
                'calculation_duration_start_month1_14' => $request->input('calculation_duration_start_month1_14'),
                'calculation_duration_start_day1_14' => $request->input('calculation_duration_start_day1_14'),
                'calculation_duration_end_month1_14' => $request->input('calculation_duration_end_month1_14'),
                'calculation_duration_end_day1_14' => $request->input('calculation_duration_end_day1_14'),
                'calculation_duration_start_month1_15' => $request->input('calculation_duration_start_month1_15'),
                'calculation_duration_start_day1_15' => $request->input('calculation_duration_start_day1_15'),
                'calculation_duration_end_month1_15' => $request->input('calculation_duration_end_month1_15'),
                'calculation_duration_end_day1_15' => $request->input('calculation_duration_end_day1_15'),
                'payment_duration_start_month1_1' => $request->input('payment_duration_start_month1_1'),
                'payment_duration_start_day1_1' => $request->input('payment_duration_start_day1_1'),
                'payment_duration_end_month1_1' => $request->input('payment_duration_end_month1_1'),
                'payment_duration_end_day1_1' => $request->input('payment_duration_end_day1_1'),
                'payment_duration_start_month1_2' => $request->input('payment_duration_start_month1_2'),
                'payment_duration_start_day1_2' => $request->input('payment_duration_start_day1_2'),
                'payment_duration_end_month1_2' => $request->input('payment_duration_end_month1_2'),
                'payment_duration_end_day1_2' => $request->input('payment_duration_end_day1_2'),
                'payment_duration_start_month1_3' => $request->input('payment_duration_start_month1_3'),
                'payment_duration_start_day1_3' => $request->input('payment_duration_start_day1_3'),
                'payment_duration_end_month1_3' => $request->input('payment_duration_end_month1_3'),
                'payment_duration_end_day1_3' => $request->input('payment_duration_end_day1_3'),
                'payment_duration_start_month1_4' => $request->input('payment_duration_start_month1_4'),
                'payment_duration_start_day1_4' => $request->input('payment_duration_start_day1_4'),
                'payment_duration_end_month1_4' => $request->input('payment_duration_end_month1_4'),
                'payment_duration_end_day1_4' => $request->input('payment_duration_end_day1_4'),
                'payment_duration_start_month1_5' => $request->input('payment_duration_start_month1_5'),
                'payment_duration_start_day1_5' => $request->input('payment_duration_start_day1_5'),
                'payment_duration_end_month1_5' => $request->input('payment_duration_end_month1_5'),
                'payment_duration_end_day1_5' => $request->input('payment_duration_end_day1_5'),
                'payment_duration_start_month1_6' => $request->input('payment_duration_start_month1_6'),
                'payment_duration_start_day1_6' => $request->input('payment_duration_start_day1_6'),
                'payment_duration_end_month1_6' => $request->input('payment_duration_end_month1_6'),
                'payment_duration_end_day1_6' => $request->input('payment_duration_end_day1_6'),
                'payment_duration_start_month1_7' => $request->input('payment_duration_start_month1_7'),
                'payment_duration_start_day1_7' => $request->input('payment_duration_start_day1_7'),
                'payment_duration_end_month1_7' => $request->input('payment_duration_end_month1_7'),
                'payment_duration_end_day1_7' => $request->input('payment_duration_end_day1_7'),
                'payment_duration_start_month1_8' => $request->input('payment_duration_start_month1_8'),
                'payment_duration_start_day1_8' => $request->input('payment_duration_start_day1_8'),
                'payment_duration_end_month1_8' => $request->input('payment_duration_end_month1_8'),
                'payment_duration_end_day1_8' => $request->input('payment_duration_end_day1_8'),
                'payment_duration_start_month1_9' => $request->input('payment_duration_start_month1_9'),
                'payment_duration_start_day1_9' => $request->input('payment_duration_start_day1_9'),
                'payment_duration_end_month1_9' => $request->input('payment_duration_end_month1_9'),
                'payment_duration_end_day1_9' => $request->input('payment_duration_end_day1_9'),
                'payment_duration_start_month1_10' => $request->input('payment_duration_start_month1_10'),
                'payment_duration_start_day1_10' => $request->input('payment_duration_start_day1_10'),
                'payment_duration_end_month1_10' => $request->input('payment_duration_end_month1_10'),
                'payment_duration_end_day1_10' => $request->input('payment_duration_end_day1_10'),
                'payment_duration_start_month1_11' => $request->input('payment_duration_start_month1_11'),
                'payment_duration_start_day1_11' => $request->input('payment_duration_start_day1_11'),
                'payment_duration_end_month1_11' => $request->input('payment_duration_end_month1_11'),
                'payment_duration_end_day1_11' => $request->input('payment_duration_end_day1_11'),
                'payment_duration_start_month1_12' => $request->input('payment_duration_start_month1_12'),
                'payment_duration_start_day1_12' => $request->input('payment_duration_start_day1_12'),
                'payment_duration_end_month1_12' => $request->input('payment_duration_end_month1_12'),
                'payment_duration_end_day1_12' => $request->input('payment_duration_end_day1_12'),
                'payment_duration_start_month1_13' => $request->input('payment_duration_start_month1_13'),
                'payment_duration_start_day1_13' => $request->input('payment_duration_start_day1_13'),
                'payment_duration_end_month1_13' => $request->input('payment_duration_end_month1_13'),
                'payment_duration_end_day1_13' => $request->input('payment_duration_end_day1_13'),
                'payment_duration_start_month1_14' => $request->input('payment_duration_start_month1_14'),
                'payment_duration_start_day1_14' => $request->input('payment_duration_start_day1_14'),
                'payment_duration_end_month1_14' => $request->input('payment_duration_end_month1_14'),
                'payment_duration_end_day1_14' => $request->input('payment_duration_end_day1_14'),
                'payment_duration_start_month1_15' => $request->input('payment_duration_start_month1_15'),
                'payment_duration_start_day1_15' => $request->input('payment_duration_start_day1_15'),
                'payment_duration_end_month1_15' => $request->input('payment_duration_end_month1_15'),
                'payment_duration_end_day1_15' => $request->input('payment_duration_end_day1_15'),
                'calculation_duration_basic_days1_1' => $request->input('calculation_duration_basic_days1_1'),
                'calculation_duration_basic_days1_3' => $request->input('calculation_duration_basic_days1_3'),
                'calculation_duration_basic_days1_2' => $request->input('calculation_duration_basic_days1_2'),
                'calculation_duration_basic_days1_4' => $request->input('calculation_duration_basic_days1_4'),
                'calculation_duration_basic_days1_5' => $request->input('calculation_duration_basic_days1_5'),
                'calculation_duration_basic_days1_6' => $request->input('calculation_duration_basic_days1_6'),
                'calculation_duration_basic_days1_7' => $request->input('calculation_duration_basic_days1_7'),
                'calculation_duration_basic_days1_8' => $request->input('calculation_duration_basic_days1_8'),
                'calculation_duration_basic_days1_9' => $request->input('calculation_duration_basic_days1_9'),
                'calculation_duration_basic_days1_10' => $request->input('calculation_duration_basic_days1_10'),
                'calculation_duration_basic_days1_11' => $request->input('calculation_duration_basic_days1_11'),
                'calculation_duration_basic_days1_12' => $request->input('calculation_duration_basic_days1_12'),
                'calculation_duration_basic_days1_13' => $request->input('calculation_duration_basic_days1_13'),
                'calculation_duration_basic_days1_14' => $request->input('calculation_duration_basic_days1_14'),
                'calculation_duration_basic_days1_15' => $request->input('calculation_duration_basic_days1_15'),
                'payment_duration_basic_days1' => $request->input('payment_duration_basic_days1'),
                'payment_duration_basic_days1_1' => $request->input('payment_duration_basic_days1_1'),
                'payment_duration_basic_days1_2' => $request->input('payment_duration_basic_days1_2'),
                'payment_duration_basic_days1_3' => $request->input('payment_duration_basic_days1_3'),
                'payment_duration_basic_days1_4' => $request->input('payment_duration_basic_days1_4'),
                'payment_duration_basic_days1_5' => $request->input('payment_duration_basic_days1_5'),
                'payment_duration_basic_days1_6' => $request->input('payment_duration_basic_days1_6'),
                'payment_duration_basic_days1_7' => $request->input('payment_duration_basic_days1_7'),
                'payment_duration_basic_days1_8' => $request->input('payment_duration_basic_days1_8'),
                'payment_duration_basic_days1_9' => $request->input('payment_duration_basic_days1_9'),
                'payment_duration_basic_days1_10' => $request->input('payment_duration_basic_days1_10'),
                'payment_duration_basic_days1_11' => $request->input('payment_duration_basic_days1_11'),
                'payment_duration_basic_days1_12' => $request->input('payment_duration_basic_days1_12'),
                'payment_duration_basic_days1_13' => $request->input('payment_duration_basic_days1_13'),
                'payment_duration_basic_days1_14' => $request->input('payment_duration_basic_days1_14'),
                'payment_duration_basic_days1_15' => $request->input('payment_duration_basic_days1_15'),
                'address' => $request->input('address'),
                'labor_consultant_japan_era_year' => $request->input('labor_consultant_japan_era_year'),
                'labor_consultant_month' => $request->input('labor_consultant_month'),
                'labor_consultant_day' => $request->input('labor_consultant_day'),
                'wage_amount_A1' => $request->input('wage_amount_A1'),
                'wage_amount_B1' => $request->input('wage_amount_B1'),
                'wage_amount_A1_1' => $request->input('wage_amount_A1_1'),
                'wage_amount_B1_1' => $request->input('wage_amount_B1_1'),
                'wage_amount_B1_2' => $request->input('wage_amount_B1_2'),
                'wage_amount_A1_2' => $request->input('wage_amount_A1_2'),
                'wage_amount_B1_3' => $request->input('wage_amount_B1_3'),
                'wage_amount_A1_3' => $request->input('wage_amount_A1_3'),
                'wage_amount_A1_4' => $request->input('wage_amount_A1_4'),
                'wage_amount_B1_4' => $request->input('wage_amount_B1_4'),
                'wage_amount_A1_5' => $request->input('wage_amount_A1_5'),
                'wage_amount_B1_5' => $request->input('wage_amount_B1_5'),
                'wage_amount_B1_6' => $request->input('wage_amount_B1_6'),
                'wage_amount_A1_6' => $request->input('wage_amount_A1_6'),
                'wage_amount_B1_7' => $request->input('wage_amount_B1_7'),
                'wage_amount_A1_7' => $request->input('wage_amount_A1_7'),
                'wage_amount_B1_8' => $request->input('wage_amount_B1_8'),
                'wage_amount_A1_8' => $request->input('wage_amount_A1_8'),
                'wage_amount_B1_9' => $request->input('wage_amount_B1_9'),
                'wage_amount_A1_9' => $request->input('wage_amount_A1_9'),
                'wage_amount_A1_10' => $request->input('wage_amount_A1_10'),
                'wage_amount_B1_10' => $request->input('wage_amount_B1_10'),
                'wage_amount_A1_11' => $request->input('wage_amount_A1_11'),
                'wage_amount_B1_11' => $request->input('wage_amount_B1_11'),
                'wage_amount_B1_12' => $request->input('wage_amount_B1_12'),
                'wage_amount_A1_12' => $request->input('wage_amount_A1_12'),
                'wage_amount_B1_13' => $request->input('wage_amount_B1_13'),
                'wage_amount_A1_13' => $request->input('wage_amount_A1_13'),
                'wage_amount_B1_14' => $request->input('wage_amount_B1_14'),
                'wage_amount_A1_14' => $request->input('wage_amount_A1_14'),
                'wage_amount_B1_15' => $request->input('wage_amount_B1_15'),
                'wage_amount_A1_15' => $request->input('wage_amount_A1_15'),
                'other_notes' => $request->input('other_notes'),
                'payment_duration_start_month1' => $request->input('payment_duration_start_month1'),
                'payment_duration_start_day1' => $request->input('payment_duration_start_day1'),
                'calculation_duration_start_month1' => $request->input('calculation_duration_start_month1'),
                'calculation_duration_start_day1' => $request->input('calculation_duration_start_day1'),
                'wage_note1' => $request->input('wage_note1'),
                'wage_note1_1' => $request->input('wage_note1_1'),
                'wage_note1_2' => $request->input('wage_note1_2'),
                'wage_note1_3' => $request->input('wage_note1_3'),
                'wage_note1_4' => $request->input('wage_note1_4'),
                'wage_note1_5' => $request->input('wage_note1_5'),
                'wage_note1_6' => $request->input('wage_note1_6'),
                'wage_note1_7' => $request->input('wage_note1_7'),
                'wage_note1_8' => $request->input('wage_note1_8'),
                'wage_note1_9' => $request->input('wage_note1_9'),
                'wage_note1_10' => $request->input('wage_note1_10'),
                'wage_note1_11' => $request->input('wage_note1_11'),
                'wage_note1_12' => $request->input('wage_note1_12'),
                'wage_note1_13' => $request->input('wage_note1_13'),
                'wage_note1_14' => $request->input('wage_note1_14'),
                'wage_note1_15' => $request->input('wage_note1_15'),
                'total_wages1_1' => $request->input('total_wages1_1'),
                'total_wages1_2' => $request->input('total_wages1_2'),
                'total_wages1_3' => $request->input('total_wages1_3'),
                'total_wages1_4' => $request->input('total_wages1_4'),
                'total_wages1_5' => $request->input('total_wages1_5'),
                'total_wages1_7' => $request->input('total_wages1_7'),
                'total_wages1_6' => $request->input('total_wages1_6'),
                'total_wages1_9' => $request->input('total_wages1_9'),
                'total_wages1_8' => $request->input('total_wages1_8'),
                'total_wages1_10' => $request->input('total_wages1_10'),
                'total_wages1_11' => $request->input('total_wages1_11'),
                'total_wages1_12' => $request->input('total_wages1_12'),
                'total_wages1_13' => $request->input('total_wages1_13'),
                'total_wages1_14' => $request->input('total_wages1_14'),
                'total_wages1_15' => $request->input('total_wages1_15'),
                'total_wages1' => $request->input('total_wages1'),
                'employment_duration_set_japan_era_year' => $request->input('employment_duration_set_japan_era_year'),
                'employment_duration_set_month' => $request->input('employment_duration_set_month'),
                'employment_duration_set_day' => $request->input('employment_duration_set_day'),
                'period_with_leave_start_included_year' => $request->input('period_with_leave_start_included_year'),
                'period_with_leave_start_included_month' => $request->input('period_with_leave_start_included_month'),
                'employment_duration_set_japan_era' => $request->input('employment_duration_set_japan_era'),
                'labor_consultant_japan_era' => $request->input('labor_consultant_japan_era'),
                'special_note_on_wages2' => $request->input('special_note_on_wages2'),
                'calculation_duration_start_month2_1' => $request->input('calculation_duration_start_month2_1'),
                'calculation_duration_start_day2_1' => $request->input('calculation_duration_start_day2_1'),
                'calculation_duration_end_month2_1' => $request->input('calculation_duration_end_month2_1'),
                'calculation_duration_end_day2_1' => $request->input('calculation_duration_end_day2_1'),
                'calculation_duration_start_month2_2' => $request->input('calculation_duration_start_month2_2'),
                'calculation_duration_start_day2_2' => $request->input('calculation_duration_start_day2_2'),
                'calculation_duration_end_month2_2' => $request->input('calculation_duration_end_month2_2'),
                'calculation_duration_end_day2_2' => $request->input('calculation_duration_end_day2_2'),
                'calculation_duration_start_month2_3' => $request->input('calculation_duration_start_month2_3'),
                'calculation_duration_start_day2_3' => $request->input('calculation_duration_start_day2_3'),
                'calculation_duration_end_month2_3' => $request->input('calculation_duration_end_month2_3'),
                'calculation_duration_end_day2_3' => $request->input('calculation_duration_end_day2_3'),
                'calculation_duration_start_month2_4' => $request->input('calculation_duration_start_month2_4'),
                'calculation_duration_start_day2_4' => $request->input('calculation_duration_start_day2_4'),
                'calculation_duration_end_month2_4' => $request->input('calculation_duration_end_month2_4'),
                'calculation_duration_end_day2_4' => $request->input('calculation_duration_end_day2_4'),
                'calculation_duration_start_month2_5' => $request->input('calculation_duration_start_month2_5'),
                'calculation_duration_start_day2_5' => $request->input('calculation_duration_start_day2_5'),
                'calculation_duration_end_month2_5' => $request->input('calculation_duration_end_month2_5'),
                'calculation_duration_end_day2_5' => $request->input('calculation_duration_end_day2_5'),
                'calculation_duration_start_month2_6' => $request->input('calculation_duration_start_month2_6'),
                'calculation_duration_start_day2_6' => $request->input('calculation_duration_start_day2_6'),
                'calculation_duration_end_month2_6' => $request->input('calculation_duration_end_month2_6'),
                'calculation_duration_end_day2_6' => $request->input('calculation_duration_end_day2_6'),
                'calculation_duration_start_month2_7' => $request->input('calculation_duration_start_month2_7'),
                'calculation_duration_start_day2_7' => $request->input('calculation_duration_start_day2_7'),
                'calculation_duration_end_month2_7' => $request->input('calculation_duration_end_month2_7'),
                'calculation_duration_end_day2_7' => $request->input('calculation_duration_end_day2_7'),
                'calculation_duration_start_month2_8' => $request->input('calculation_duration_start_month2_8'),
                'calculation_duration_start_day2_8' => $request->input('calculation_duration_start_day2_8'),
                'calculation_duration_end_month2_8' => $request->input('calculation_duration_end_month2_8'),
                'calculation_duration_end_day2_8' => $request->input('calculation_duration_end_day2_8'),
                'calculation_duration_start_month2_9' => $request->input('calculation_duration_start_month2_9'),
                'calculation_duration_start_day2_9' => $request->input('calculation_duration_start_day2_9'),
                'calculation_duration_end_month2_9' => $request->input('calculation_duration_end_month2_9'),
                'calculation_duration_end_day2_9' => $request->input('calculation_duration_end_day2_9'),
                'calculation_duration_start_month2_10' => $request->input('calculation_duration_start_month2_10'),
                'calculation_duration_start_day2_10' => $request->input('calculation_duration_start_day2_10'),
                'calculation_duration_end_month2_10' => $request->input('calculation_duration_end_month2_10'),
                'calculation_duration_end_day2_10' => $request->input('calculation_duration_end_day2_10'),
                'calculation_duration_start_month2_11' => $request->input('calculation_duration_start_month2_11'),
                'calculation_duration_start_day2_11' => $request->input('calculation_duration_start_day2_11'),
                'calculation_duration_end_month2_11' => $request->input('calculation_duration_end_month2_11'),
                'calculation_duration_end_day2_11' => $request->input('calculation_duration_end_day2_11'),
                'calculation_duration_start_month2_12' => $request->input('calculation_duration_start_month2_12'),
                'calculation_duration_start_day2_12' => $request->input('calculation_duration_start_day2_12'),
                'calculation_duration_end_month2_12' => $request->input('calculation_duration_end_month2_12'),
                'calculation_duration_end_day2_12' => $request->input('calculation_duration_end_day2_12'),
                'calculation_duration_start_month2_13' => $request->input('calculation_duration_start_month2_13'),
                'calculation_duration_start_day2_13' => $request->input('calculation_duration_start_day2_13'),
                'calculation_duration_end_month2_13' => $request->input('calculation_duration_end_month2_13'),
                'calculation_duration_end_day2_13' => $request->input('calculation_duration_end_day2_13'),
                'calculation_duration_start_month2_14' => $request->input('calculation_duration_start_month2_14'),
                'calculation_duration_start_day2_14' => $request->input('calculation_duration_start_day2_14'),
                'calculation_duration_end_month2_14' => $request->input('calculation_duration_end_month2_14'),
                'calculation_duration_end_day2_14' => $request->input('calculation_duration_end_day2_14'),
                'calculation_duration_start_month2_15' => $request->input('calculation_duration_start_month2_15'),
                'calculation_duration_start_day2_15' => $request->input('calculation_duration_start_day2_15'),
                'calculation_duration_end_month2_15' => $request->input('calculation_duration_end_month2_15'),
                'calculation_duration_end_day2_15' => $request->input('calculation_duration_end_day2_15'),
                'payment_duration_start_month2_1' => $request->input('payment_duration_start_month2_1'),
                'payment_duration_start_day2_1' => $request->input('payment_duration_start_day2_1'),
                'payment_duration_end_month2_1' => $request->input('payment_duration_end_month2_1'),
                'payment_duration_end_day2_1' => $request->input('payment_duration_end_day2_1'),
                'payment_duration_start_month2_2' => $request->input('payment_duration_start_month2_2'),
                'payment_duration_start_day2_2' => $request->input('payment_duration_start_day2_2'),
                'payment_duration_end_month2_2' => $request->input('payment_duration_end_month2_2'),
                'payment_duration_end_day2_2' => $request->input('payment_duration_end_day2_2'),
                'payment_duration_start_month2_3' => $request->input('payment_duration_start_month2_3'),
                'payment_duration_start_day2_3' => $request->input('payment_duration_start_day2_3'),
                'payment_duration_end_month2_3' => $request->input('payment_duration_end_month2_3'),
                'payment_duration_end_day2_3' => $request->input('payment_duration_end_day2_3'),
                'payment_duration_start_month2_4' => $request->input('payment_duration_start_month2_4'),
                'payment_duration_start_day2_4' => $request->input('payment_duration_start_day2_4'),
                'payment_duration_end_month2_4' => $request->input('payment_duration_end_month2_4'),
                'payment_duration_end_day2_4' => $request->input('payment_duration_end_day2_4'),
                'payment_duration_start_month2_5' => $request->input('payment_duration_start_month2_5'),
                'payment_duration_start_day2_5' => $request->input('payment_duration_start_day2_5'),
                'payment_duration_end_month2_5' => $request->input('payment_duration_end_month2_5'),
                'payment_duration_end_day2_5' => $request->input('payment_duration_end_day2_5'),
                'payment_duration_start_month2_6' => $request->input('payment_duration_start_month2_6'),
                'payment_duration_start_day2_6' => $request->input('payment_duration_start_day2_6'),
                'payment_duration_end_month2_6' => $request->input('payment_duration_end_month2_6'),
                'payment_duration_end_day2_6' => $request->input('payment_duration_end_day2_6'),
                'payment_duration_start_month2_7' => $request->input('payment_duration_start_month2_7'),
                'payment_duration_start_day2_7' => $request->input('payment_duration_start_day2_7'),
                'payment_duration_end_month2_7' => $request->input('payment_duration_end_month2_7'),
                'payment_duration_end_day2_7' => $request->input('payment_duration_end_day2_7'),
                'payment_duration_start_month2_8' => $request->input('payment_duration_start_month2_8'),
                'payment_duration_start_day2_8' => $request->input('payment_duration_start_day2_8'),
                'payment_duration_end_month2_8' => $request->input('payment_duration_end_month2_8'),
                'payment_duration_end_day2_8' => $request->input('payment_duration_end_day2_8'),
                'payment_duration_start_month2_9' => $request->input('payment_duration_start_month2_9'),
                'payment_duration_start_day2_9' => $request->input('payment_duration_start_day2_9'),
                'payment_duration_end_month2_9' => $request->input('payment_duration_end_month2_9'),
                'payment_duration_end_day2_9' => $request->input('payment_duration_end_day2_9'),
                'payment_duration_start_month2_10' => $request->input('payment_duration_start_month2_10'),
                'payment_duration_start_day2_10' => $request->input('payment_duration_start_day2_10'),
                'payment_duration_end_month2_10' => $request->input('payment_duration_end_month2_10'),
                'payment_duration_end_day2_10' => $request->input('payment_duration_end_day2_10'),
                'payment_duration_start_month2_11' => $request->input('payment_duration_start_month2_11'),
                'payment_duration_start_day2_11' => $request->input('payment_duration_start_day2_11'),
                'payment_duration_end_month2_11' => $request->input('payment_duration_end_month2_11'),
                'payment_duration_end_day2_11' => $request->input('payment_duration_end_day2_11'),
                'payment_duration_start_month2_12' => $request->input('payment_duration_start_month2_12'),
                'payment_duration_start_day2_12' => $request->input('payment_duration_start_day2_12'),
                'payment_duration_end_month2_12' => $request->input('payment_duration_end_month2_12'),
                'payment_duration_end_day2_12' => $request->input('payment_duration_end_day2_12'),
                'payment_duration_start_month2_13' => $request->input('payment_duration_start_month2_13'),
                'payment_duration_start_day2_13' => $request->input('payment_duration_start_day2_13'),
                'payment_duration_end_month2_13' => $request->input('payment_duration_end_month2_13'),
                'payment_duration_end_day2_13' => $request->input('payment_duration_end_day2_13'),
                'payment_duration_start_month2_14' => $request->input('payment_duration_start_month2_14'),
                'payment_duration_start_day2_14' => $request->input('payment_duration_start_day2_14'),
                'payment_duration_end_month2_14' => $request->input('payment_duration_end_month2_14'),
                'payment_duration_end_day2_14' => $request->input('payment_duration_end_day2_14'),
                'payment_duration_start_month2_15' => $request->input('payment_duration_start_month2_15'),
                'payment_duration_start_day2_15' => $request->input('payment_duration_start_day2_15'),
                'payment_duration_end_month2_15' => $request->input('payment_duration_end_month2_15'),
                'payment_duration_end_day2_15' => $request->input('payment_duration_end_day2_15'),
                'calculation_duration_basic_days2_1' => $request->input('calculation_duration_basic_days2_1'),
                'calculation_duration_basic_days2_3' => $request->input('calculation_duration_basic_days2_3'),
                'calculation_duration_basic_days2_2' => $request->input('calculation_duration_basic_days2_2'),
                'calculation_duration_basic_days2_4' => $request->input('calculation_duration_basic_days2_4'),
                'calculation_duration_basic_days2_5' => $request->input('calculation_duration_basic_days2_5'),
                'calculation_duration_basic_days2_6' => $request->input('calculation_duration_basic_days2_6'),
                'calculation_duration_basic_days2_7' => $request->input('calculation_duration_basic_days2_7'),
                'calculation_duration_basic_days2_8' => $request->input('calculation_duration_basic_days2_8'),
                'calculation_duration_basic_days2_9' => $request->input('calculation_duration_basic_days2_9'),
                'calculation_duration_basic_days2_10' => $request->input('calculation_duration_basic_days2_10'),
                'calculation_duration_basic_days2_11' => $request->input('calculation_duration_basic_days2_11'),
                'calculation_duration_basic_days2_12' => $request->input('calculation_duration_basic_days2_12'),
                'calculation_duration_basic_days2_13' => $request->input('calculation_duration_basic_days2_13'),
                'calculation_duration_basic_days2_14' => $request->input('calculation_duration_basic_days2_14'),
                'calculation_duration_basic_days2_15' => $request->input('calculation_duration_basic_days2_15'),
                'payment_duration_basic_days2_1' => $request->input('payment_duration_basic_days2_1'),
                'payment_duration_basic_days2_2' => $request->input('payment_duration_basic_days2_2'),
                'payment_duration_basic_days2_3' => $request->input('payment_duration_basic_days2_3'),
                'payment_duration_basic_days2_4' => $request->input('payment_duration_basic_days2_4'),
                'payment_duration_basic_days2_5' => $request->input('payment_duration_basic_days2_5'),
                'payment_duration_basic_days2_6' => $request->input('payment_duration_basic_days2_6'),
                'payment_duration_basic_days2_7' => $request->input('payment_duration_basic_days2_7'),
                'payment_duration_basic_days2_8' => $request->input('payment_duration_basic_days2_8'),
                'payment_duration_basic_days2_9' => $request->input('payment_duration_basic_days2_9'),
                'payment_duration_basic_days2_10' => $request->input('payment_duration_basic_days2_10'),
                'payment_duration_basic_days2_11' => $request->input('payment_duration_basic_days2_11'),
                'payment_duration_basic_days2_12' => $request->input('payment_duration_basic_days2_12'),
                'payment_duration_basic_days2_13' => $request->input('payment_duration_basic_days2_13'),
                'payment_duration_basic_days2_14' => $request->input('payment_duration_basic_days2_14'),
                'payment_duration_basic_days2_15' => $request->input('payment_duration_basic_days2_15'),
                'wage_amount_A2_1' => $request->input('wage_amount_A2_1'),
                'wage_amount_B2_1' => $request->input('wage_amount_B2_1'),
                'wage_amount_B2_2' => $request->input('wage_amount_B2_2'),
                'wage_amount_A2_2' => $request->input('wage_amount_A2_2'),
                'wage_amount_B2_3' => $request->input('wage_amount_B2_3'),
                'wage_amount_A2_3' => $request->input('wage_amount_A2_3'),
                'wage_amount_A2_4' => $request->input('wage_amount_A2_4'),
                'wage_amount_B2_4' => $request->input('wage_amount_B2_4'),
                'wage_amount_A2_5' => $request->input('wage_amount_A2_5'),
                'wage_amount_B2_5' => $request->input('wage_amount_B2_5'),
                'wage_amount_B2_6' => $request->input('wage_amount_B2_6'),
                'wage_amount_A2_6' => $request->input('wage_amount_A2_6'),
                'wage_amount_B2_7' => $request->input('wage_amount_B2_7'),
                'wage_amount_A2_7' => $request->input('wage_amount_A2_7'),
                'wage_amount_B2_8' => $request->input('wage_amount_B2_8'),
                'wage_amount_A2_8' => $request->input('wage_amount_A2_8'),
                'wage_amount_B2_9' => $request->input('wage_amount_B2_9'),
                'wage_amount_A2_9' => $request->input('wage_amount_A2_9'),
                'wage_amount_A2_10' => $request->input('wage_amount_A2_10'),
                'wage_amount_B2_10' => $request->input('wage_amount_B2_10'),
                'wage_amount_A2_11' => $request->input('wage_amount_A2_11'),
                'wage_amount_B2_11' => $request->input('wage_amount_B2_11'),
                'wage_amount_B2_12' => $request->input('wage_amount_B2_12'),
                'wage_amount_A2_12' => $request->input('wage_amount_A2_12'),
                'wage_amount_B2_13' => $request->input('wage_amount_B2_13'),
                'wage_amount_A2_13' => $request->input('wage_amount_A2_13'),
                'wage_amount_B2_14' => $request->input('wage_amount_B2_14'),
                'wage_amount_A2_14' => $request->input('wage_amount_A2_14'),
                'wage_amount_B2_15' => $request->input('wage_amount_B2_15'),
                'wage_amount_A2_15' => $request->input('wage_amount_A2_15'),
                'wage_note2_1' => $request->input('wage_note2_1'),
                'wage_note2_2' => $request->input('wage_note2_2'),
                'wage_note2_3' => $request->input('wage_note2_3'),
                'wage_note2_4' => $request->input('wage_note2_4'),
                'wage_note2_5' => $request->input('wage_note2_5'),
                'wage_note2_6' => $request->input('wage_note2_6'),
                'wage_note2_7' => $request->input('wage_note2_7'),
                'wage_note2_8' => $request->input('wage_note2_8'),
                'wage_note2_9' => $request->input('wage_note2_9'),
                'wage_note2_10' => $request->input('wage_note2_10'),
                'wage_note2_11' => $request->input('wage_note2_11'),
                'wage_note2_12' => $request->input('wage_note2_12'),
                'wage_note2_13' => $request->input('wage_note2_13'),
                'wage_note2_14' => $request->input('wage_note2_14'),
                'wage_note2_15' => $request->input('wage_note2_15'),
                'total_wages2_1' => $request->input('total_wages2_1'),
                'total_wages2_2' => $request->input('total_wages2_2'),
                'total_wages2_3' => $request->input('total_wages2_3'),
                'total_wages2_4' => $request->input('total_wages2_4'),
                'total_wages2_5' => $request->input('total_wages2_5'),
                'total_wages2_7' => $request->input('total_wages2_7'),
                'total_wages2_6' => $request->input('total_wages2_6'),
                'total_wages2_9' => $request->input('total_wages2_9'),
                'total_wages2_8' => $request->input('total_wages2_8'),
                'total_wages2_10' => $request->input('total_wages2_10'),
                'total_wages2_11' => $request->input('total_wages2_11'),
                'total_wages2_12' => $request->input('total_wages2_12'),
                'total_wages2_13' => $request->input('total_wages2_13'),
                'total_wages2_14' => $request->input('total_wages2_14'),
                'total_wages2_15' => $request->input('total_wages2_15'),
                'headquarters_or_branch' => $request->input('headquarters_or_branch'),
                'commuting_allowance' => $request->input('commuting_allowance'),
                'employment_duration_set' => $request->input('employment_duration_set'),
                'reduced_working_hours_wage_certificate_start' => $request->input('reduced_working_hours_wage_certificate_start'),
                'leave_start_wage_monthly_certificate' => $request->input('leave_start_wage_monthly_certificate'),
                'apply_to_code' => $request->input('apply_to_code'),
                'apply_to_name' => $request->input('apply_to_name')
            ];
            $XML = new MixXmlEgovSigner($request);
            $response = $XML->run($request, $separater = True);
            if ($response[0] == false) {
                $errorMessage = $response[1];
                \Log::error(print_r($response, true));
                return redirect()->back()->withErrors($errorMessage)->withInput();
            }
            $this->putSuccess("送信に成功しました");
            if($request->input('query_parameter')) {
                return redirect()->to($request->input('query_parameter'));
            } else {
                return redirect()->route('ledger.index');
            }
        } catch (ValidationException $e) {
            return redirect()->back()->withErrors($e->errors())->withInput();
        }
    }
}
