<DIV style="position:relative; left:0px; top:0px; width:801px; height:1132px;">
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); left:358px; top:651px; width:123px; height:43px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:25px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:152px; top:651px; width:146px; height:43px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:25px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:76px; top:209px; width:77px; height:195px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:177px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:297px; top:693px; width:184px; height:43px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:25px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:641px; top:35px; width:117px; height:50px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:32px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:0px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:278px; top:377px; width:481px; height:27px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:10px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:76px; top:807px; width:222px; height:51px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:33px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:0px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:297px; top:807px; width:46px; height:15px; text-align:right; font-size:12px; font-family:'ＭＳ 明朝', serif; padding:0px 3px 0px 0px;">月</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:712px; top:209px; width:47px; height:35px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 0px 0px;"><INPUT tabindex="12" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:right; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 1px 0px 0px; width:45px; height:17px; ime-mode:inactive;" type="TEXT" id="_8E96_8BC6_8F8A_94D4_8D86x_8D90_926D_94D4_8D86_002E12" name="office_number_notification_number" value="{{ old('office_number_notification_number') }}" maxlength="5"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:617px; top:209px; width:96px; height:36px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:18px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:152px; top:209px; width:127px; height:36px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:18px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:76px; top:441px; width:606px; height:24px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:6px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:76px; top:464px; width:606px; line-height:30px; height:51px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:16px 0px 0px 0px;"><INPUT tabindex="21" style="text-align:left; box-sizing:border-box; -moz-box-sizing:border-box; line-height:1em; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; width:604px; height:32px; ime-mode:active;" id="_8ED0_89EF_95DB_8CAF_984A_96B1_8E6D_82CC_92F1_8F6F_91E3_8D73_8ED2_96BC_002E21" name="labor_consultant_name" value="{{ old('labor_consultant_name') }}"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:152px; top:243px; width:127px; height:161px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:143px 0px 0px 0px;"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:0px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:278px; top:243px; width:481px; height:27px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:10px 0px 0px 0px;"></SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:76px; top:180px; width:32px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">令和</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:160px; top:180px; width:15px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif;">年</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:223px; top:180px; width:16px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif;">月</SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:287px; top:180px; width:48px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">日提出</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:651px; top:49px; width:95px; height:19px; text-align:center; font-size:17px; font-family:'ＭＳ ゴシック', sans-serif; display:block; text-align:justify; text-justify:distribute-all-lines;">電子申請用</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:160px; top:310px; width:110px; height:16px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">事業所名称</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:156px; top:326px; width:118px; height:16px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">(船舶所有者氏名)</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:160px; top:344px; width:110px; height:16px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">事業主氏名</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:156px; top:360px; width:114px; height:16px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">(代表者氏名)</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:160px; top:383px; width:110px; height:16px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">電　　　話</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:283px; top:250px; width:16px; height:13px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif;">〒</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:352px; top:250px; width:13px; height:13px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif;">－</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:385px; top:383px; width:16px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif;">（</SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:462px; top:383px; width:32px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">局）</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:578px; top:383px; width:16px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif;">番</SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:160px; top:272px; width:110px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">事業所所在地</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:156px; top:288px; width:118px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">(船舶所有者住所)</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:385px; top:106px; width:170px; height:18px; text-align:center; font-size:17px; font-family:'ＭＳ ゴシック', sans-serif; display:block; text-align:justify; text-justify:distribute-all-lines;">賞与不支給報告書</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:160px; top:220px; width:110px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">&#x2460;事業所整理記号</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:621px; top:212px; width:85px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">&#x2461;事業所番号</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:632px; top:228px; width:76px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">(告知番号)</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:257px; top:89px; width:109px; height:16px; text-align:center; font-size:14px; font-family:'ＭＳ ゴシック', sans-serif; display:block; text-align:justify; text-justify:distribute-all-lines;">健康保険</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:257px; top:108px; width:109px; height:16px; text-align:center; font-size:14px; font-family:'ＭＳ ゴシック', sans-serif; display:block; text-align:justify; text-justify:distribute-all-lines;">船員保険</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:257px; top:128px; width:109px; height:16px; text-align:center; font-size:14px; font-family:'ＭＳ ゴシック', sans-serif; display:block; text-align:justify; text-justify:distribute-all-lines;">厚生年金保険</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:358px; top:708px; width:76px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">不支給</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:83px; top:826px; width:206px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">&#x2467;変更後の賞与支払予定月</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:152px; top:445px; width:419px; height:16px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:1px 0px 0px 0px; display:block; text-align:justify; text-justify:distribute-all-lines;">&#x2463;社会保険労務士記載欄</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:156px; top:666px; width:137px; height:15px; text-align:center; font-size:12px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">&#x2465;賞与支払(予定)年月</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:400px; top:666px; width:18px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif;">年</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:459px; top:666px; width:19px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif;">月</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:0px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:0px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:278px; top:270px; width:481px; line-height:38px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif;"><INPUT tabindex="15" style="text-align:left; box-sizing:border-box; -moz-box-sizing:border-box; line-height:1em; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; width:479px; height:36px; ime-mode:active;" id="_8E96_8BC6_8F8A_8F8A_8DDD_926Ex_9144_9495_8F8A_974C_8ED2_8F5A_8F8A_002E15" name="business_location_ship_owner_address" value="{{ old('business_location_ship_owner_address') }}"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:0px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:0px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:278px; top:307px; width:481px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif;"><INPUT tabindex="16" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:left; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:479px; height:36px; ime-mode:active;" type="TEXT" id="_8E96_8BC6_8F8A_96BC_8FCCx_9144_9495_8F8A_974C_8ED2_8E81_96BC_002E16" name="business_name_name_of_ship_owner" value="{{ old('business_name_name_of_ship_owner') }}" maxlength="25"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:0px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:0px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:278px; top:344px; width:481px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif;"><INPUT tabindex="17" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:left; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:479px; height:36px; ime-mode:active;" type="TEXT" id="_8E96_8BC6_8EE5_8E81_96BCx_91E3_955C_8ED2_8E81_96BC_002E17" name="business_owner_name_representative_name" value="{{ old('business_owner_name_representative_name') }}" maxlength="25"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:0px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:297px; top:822px; width:46px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 2px 0px;"><INPUT tabindex="27" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:44px; height:17px; ime-mode:inactive;" type="TEXT" id="_95CF_8D58_8CE3_82CC_8FDC_975E_8E78_95A5_975C_92E8_8C8E1_002E27" name="changed_bonus_payment_schedule_month1" value="{{ old('changed_bonus_payment_schedule_month1') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:0px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:342px; top:822px; width:47px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 2px 0px;"><INPUT tabindex="28" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:45px; height:17px; ime-mode:inactive;" type="TEXT" id="_95CF_8D58_8CE3_82CC_8FDC_975E_8E78_95A5_975C_92E8_8C8E2_002E28" name="changed_bonus_payment_schedule_month2" value="{{ old('changed_bonus_payment_schedule_month2') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:0px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:388px; top:822px; width:47px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 2px 0px;"><INPUT tabindex="29" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:45px; height:17px; ime-mode:inactive;" type="TEXT" id="_95CF_8D58_8CE3_82CC_8FDC_975E_8E78_95A5_975C_92E8_8C8E3_002E29" name="changed_bonus_payment_schedule_month3" value="{{ old('changed_bonus_payment_schedule_month3') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:0px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:434px; top:822px; width:47px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 2px 0px;"><INPUT tabindex="30" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:45px; height:17px; ime-mode:inactive;" type="TEXT" id="_95CF_8D58_8CE3_82CC_8FDC_975E_8E78_95A5_975C_92E8_8C8E4_002E30" name="changed_bonus_payment_schedule_month4" value="{{ old('changed_bonus_payment_schedule_month4') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:303px; top:245px; width:44px; height:23px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:2px 0px 0px 0px;"><INPUT tabindex="13" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:44px; height:17px; ime-mode:inactive;" type="TEXT" id="_8E96_8BC6_8F8A_8F8A_8DDD_926Ex_9758_95D6_94D4_8D86x_9065_94D4_8D86_002E13" name="post_code_former" value="{{ old('post_code_former') }}" maxlength="3"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:371px; top:245px; width:58px; height:23px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:2px 0px 0px 0px;"><INPUT tabindex="14" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:58px; height:17px; ime-mode:inactive;" type="TEXT" id="_8E96_8BC6_8F8A_8F8A_8DDD_926Ex_9758_95D6_94D4_8D86x_8E71_94D4_8D86_002E14" name="post_code_latter" value="{{ old('post_code_latter') }}" maxlength="4"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:311px; top:381px; width:72px; height:22px; font-size:13px; font-family:'ＭＳ 明朝', serif;"><INPUT tabindex="18" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:72px; height:22px; ime-mode:inactive;" type="TEXT" id="_9364_9862_94D4_8D86x_8E73_8A4F_8BC7_94D4_002E18" name="branch_tel_area_code" value="{{ old('branch_tel_area_code') }}" maxlength="5"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:403px; top:381px; width:58px; height:22px; font-size:13px; font-family:'ＭＳ 明朝', serif;"><INPUT tabindex="19" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:58px; height:22px; ime-mode:inactive;" type="TEXT" id="_9364_9862_94D4_8D86x_8BC7_94D4_002E19" name="branch_tel_city_code" value="{{ old('branch_tel_city_code') }}" maxlength="4"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:499px; top:381px; width:72px; height:22px; font-size:13px; font-family:'ＭＳ 明朝', serif;"><INPUT tabindex="20" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:72px; height:22px; ime-mode:inactive;" type="TEXT" id="_9364_9862_94D4_8D86x_94D4_8D86_002E20" name="branch_tel_subscriber_code" value="{{ old('branch_tel_subscriber_code') }}" maxlength="5"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:115px; top:171px; width:41px; height:27px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:4px 0px 0px 0px;"><INPUT tabindex="4" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:41px; height:17px; ime-mode:inactive;" type="TEXT" id="_944E_002E4" name="today_japan_era_year" value="{{ old('today_japan_era_year') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:178px; top:171px; width:42px; height:27px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:4px 0px 0px 0px;"><INPUT tabindex="5" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:42px; height:17px; ime-mode:inactive;" type="TEXT" id="_8C8E_002E5" name="today_japan_era_month" value="{{ old('today_japan_era_month') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:243px; top:171px; width:41px; height:27px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:4px 0px 0px 0px;"><INPUT tabindex="6" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:41px; height:17px; ime-mode:inactive;" type="TEXT" id="_93FA_002E6" name="today_japan_era_day" value="{{ old('today_japan_era_day') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:361px; top:655px; width:39px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:9px 0px 0px 0px;"><INPUT tabindex="24" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:39px; height:17px; ime-mode:inactive;" type="TEXT" id="_944E_002E24" name="scheduled_year_of_bonus_payment" value="{{ old('scheduled_year_of_bonus_payment') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:422px; top:655px; width:39px; height:36px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:9px 0px 0px 0px;"><INPUT tabindex="25" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:center; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:39px; height:17px; ime-mode:inactive;" type="TEXT" id="_8C8E_002E25" name="scheduled_month_of_bonus_payment" value="{{ old('scheduled_month_of_bonus_payment') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; display:none; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:678px; top:3px; width:115px; height:28px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:10px 0px 0px 0px;">A-330452-001_1</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; display:none; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:693px; top:1074px; width:108px; height:58px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:40px 0px 0px 0px;">0</SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:91px; top:304px; width:49px; height:16px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:1px 0px 0px 0px; display:block; text-align:justify; text-justify:distribute-all-lines;">記入欄</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:91px; top:285px; width:49px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">提出者</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); left:80px; top:466px; width:57px; height:15px; text-align:center; font-size:10px; font-family:'ＭＳ 明朝', serif; padding:1px 0px 0px 0px; display:block; text-align:justify; text-justify:distribute-all-lines;">氏名等</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:76px; top:552px; width:647px; height:15px; text-align:left; font-size:13px; font-family:'ＭＳ 明朝', serif;">・この報告書は、賞与支払予定月に賞与の支給がなかった場合に提出してください。</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:76px; top:575px; width:647px; height:16px; text-align:left; font-size:13px; font-family:'ＭＳ 明朝', serif;">　　（賞与支払予定月に報告書の提出がない場合、後日、提出勧奨のお知らせが送付されます。）</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:369px; top:209px; width:62px; height:35px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 0px 0px;"><INPUT tabindex="9" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:left; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:60px; height:17px; ime-mode:active;" type="TEXT" id="_8E96_8BC6_8F8A_90AE_979D_8B4C_8D86x_8E96_8BC6_8F8A_8B4C_8D86_002E9" name="office_reference_symbol_office_symbol" value="{{ old('office_reference_symbol_office_symbol') }}" maxlength="4"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:308px; top:209px; width:62px; height:35px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 0px 0px;"><INPUT tabindex="8" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:left; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:60px; height:17px; ime-mode:active;" type="TEXT" id="_8E96_8BC6_8F8A_90AE_979D_8B4C_8D86x_8C53_8E73_8BE6_8B4C_8D86_002E8" name="office_arrangement_code_county_city_ward_code" value="{{ old('office_arrangement_code_county_city_ward_code') }}" maxlength="4"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:278px; top:209px; width:31px; height:35px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 0px 0px;"><INPUT tabindex="7" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:left; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:29px; height:17px; ime-mode:inactive;" type="TEXT" id="_8E96_8BC6_8F8A_90AE_979D_8B4C_8D86x_9373_93B9_957B_8CA7_8352_815B_8368_002E7" name="business_establishment_code_prefecture_code" value="{{ old('business_establishment_code_prefecture_code') }}" maxlength="2"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:76px; top:609px; width:77px; height:127px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:109px 0px 0px 0px;"></SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:104px; top:626px; width:19px; height:107px; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines; writing-mode:tb-rl;">賞与支払情報</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:152px; top:693px; width:146px; height:43px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:25px 0px 0px 0px;"></SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:156px; top:708px; width:137px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">&#x2466;支給の状況</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:76px; top:773px; width:647px; height:16px; text-align:left; font-size:13px; font-family:'ＭＳ 明朝', serif;">・従前の賞与支払予定月を変更する場合は以下も記入してください。</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:0px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:388px; top:807px; width:47px; height:15px; text-align:right; font-size:12px; font-family:'ＭＳ 明朝', serif; padding:0px 3px 0px 0px;">月</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:0px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:342px; top:807px; width:47px; height:15px; text-align:right; font-size:12px; font-family:'ＭＳ 明朝', serif; padding:0px 3px 0px 0px;">月</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:0px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:434px; top:807px; width:47px; height:15px; text-align:right; font-size:12px; font-family:'ＭＳ 明朝', serif; padding:0px 3px 0px 0px;">月</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:525px; top:209px; width:47px; height:35px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 0px 0px;"><INPUT tabindex="10" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:left; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:45px; height:17px; ime-mode:active;" type="TEXT" id="_9144_9495_8F8A_974C_8ED2_90AE_979D_8B4C_8D86x_9144_95DB_8E96_96B1_8F8A_97AA_8FCC_96BC_002E10" name="ship_owner_reference_code_ship_insurance_office_abbreviation_name" value="{{ old('ship_owner_reference_code_ship_insurance_office_abbreviation_name') }}" maxlength="3"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:571px; top:209px; width:47px; height:35px; font-size:13px; font-family:'ＭＳ 明朝', serif; padding:7px 0px 0px 0px;"><INPUT tabindex="11" style="box-sizing:border-box; -moz-box-sizing:border-box; text-align:left; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 0px; width:45px; height:17px; ime-mode:active;" type="TEXT" id="_9144_9495_8F8A_974C_8ED2_90AE_979D_8B4C_8D86x_8B4C_8D86_002E11" name="ship_owner_arrangement_symbol_symbol" value="{{ old('ship_owner_arrangement_symbol_symbol') }}" maxlength="3"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:430px; top:209px; width:96px; height:35px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:17px 0px 0px 0px;"></SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:434px; top:212px; width:86px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">&#x2460;船舶所有者</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:449px; top:228px; width:71px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">整理記号</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:45px; top:342px; width:16px; height:291px; font-size:10px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines; writing-mode:tb-rl;">◎入力方法等については、記載要領をご覧ください。</SPAN></PRE>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:22px; top:342px; width:16px; height:230px; font-size:10px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines; writing-mode:tb-rl;">◎必ず電子署名を付与して申請願います。</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 0); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:297px; top:609px; width:184px; line-height:42px; height:43px; font-size:13px; font-family:'ＭＳ 明朝', serif;"><INPUT tabindex="22" style="text-align:left; box-sizing:border-box; -moz-box-sizing:border-box; line-height:1em; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; width:182px; height:40px; ime-mode:active;" id="_8FDC_975E_82CC_96BC_8FCC_002E22" name="bonus_name" value="{{ old('bonus_name') }}"></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:1px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:152px; top:609px; width:146px; height:43px; text-align:left; font-size:14px; font-family:'ＭＳ 明朝', serif; padding:25px 0px 0px 0px;"></SPAN>
    <PRE><SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:156px; top:624px; width:137px; height:15px; text-align:center; font-size:13px; font-family:'ＭＳ 明朝', serif; display:block; text-align:justify; text-justify:distribute-all-lines;">&#x2464;賞与の名称</SPAN></PRE>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); border-top:1px solid rgb(0, 0, 0); border-right:0px solid rgb(0, 0, 0); border-bottom:1px solid rgb(0, 0, 0); border-left:1px solid rgb(0, 0, 0); left:297px; top:651px; width:61px; height:43px; font-size:13px; padding:11px 0px 0px 3px;"><SELECT size="1" tabindex="23" style="box-sizing:border-box; -moz-box-sizing:border-box; line-height:1em; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); font-size:13px; font-family:'ＭＳ 明朝', serif; width:57px;" id="_8CB3_8D86_002E23" name="era_name">
    <OPTION value="9" selected="selected">令&nbsp;和</OPTION>
    </SELECT></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); left:331px; top:705px; width:15px; line-height:17px; height:17px; text-align:left; font-size:17px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 30px; white-space:nowrap;"><INPUT checked="checked" tabindex="26" value="1" style="position:absolute; top:3px; left:0px; box-sizing:border-box; -moz-box-sizing:border-box; width:11px; height:11px;" type="RADIO" id="_8E78_8B8B_82CC_8FF3_8BB5_002E26" name="payment_status"><SPAN style="font-size:14px; height:14px; vertical-align:middle;">&nbsp;</SPAN></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); background-color:rgb(255, 255, 255); left:160px; top:251px; width:85px; height:16px; text-align:left; font-size:13px; font-family:'ＭＳ 明朝', serif;">&#x2462;</SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); left:232px; top:124px; width:19px; line-height:21px; height:21px; text-align:left; font-size:21px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 30px; white-space:nowrap;"><INPUT tabindex="3" value="1" style="position:absolute; top:2px; left:0px; box-sizing:border-box; -moz-box-sizing:border-box; width:16px; height:16px;" type="CHECKBOX" id="_9557_91E8x_8CFA_90B6_944E_8BE0_95DB_8CAF_82CC_95CA_002E3" name="title_types_of_welfare_pension_insurance" <?php echo old('title_types_of_welfare_pension_insurance') == '1' ? 'checked' : ''; ?>><SPAN style="font-size:14px; height:14px; vertical-align:middle;">&nbsp;</SPAN></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); left:232px; top:104px; width:19px; line-height:21px; height:21px; text-align:left; font-size:21px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 30px; white-space:nowrap;"><INPUT tabindex="2" value="1" style="position:absolute; top:2px; left:0px; box-sizing:border-box; -moz-box-sizing:border-box; width:16px; height:16px;" type="CHECKBOX" id="_9557_91E8x_9144_88F5_95DB_8CAF_82CC_95CA_002E2" name="title_different_types_of_seafarers_insurance" <?php echo old('title_different_types_of_seafarers_insurance') == '1' ? 'checked' : ''; ?>><SPAN style="font-size:14px; height:14px; vertical-align:middle;">&nbsp;</SPAN></SPAN>
    <SPAN style="position:absolute; box-sizing:border-box; -moz-box-sizing:border-box; overflow:hidden; color:rgb(0, 0, 0); left:232px; top:83px; width:19px; line-height:21px; height:22px; text-align:left; font-size:22px; font-family:'ＭＳ 明朝', serif; padding:0px 0px 0px 30px; white-space:nowrap;"><INPUT tabindex="1" value="1" style="position:absolute; top:3px; left:0px; box-sizing:border-box; -moz-box-sizing:border-box; width:16px; height:16px;" type="CHECKBOX" id="_9557_91E8x_8C92_8D4E_95DB_8CAF_82CC_95CA_002E1" name="title_different_types_of_health_insurance" <?php echo old('title_different_types_of_health_insurance') == '1' ? 'checked' : ''; ?>><SPAN style="font-size:14px; height:14px; vertical-align:middle;">&nbsp;</SPAN></SPAN>
</DIV>
                            
