<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CaregiverLeaveBenefitApplicationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public static function rules(): array
    {
        return [
            'employment_mynumber_card_no' => 'nullable|string|regex:/^[0-9]{12}$/u',
            'employment_insured_no_4' => 'nullable|string|regex:/^[0-9]{4}$/u',
            'employment_insured_no_6' => 'nullable|string|regex:/^[0-9]{6}$/u',
            'employment_insured_no_cd' => 'nullable|string|regex:/^[0-9]{1}$/u',
            'employment_insured_date_era' => 'nullable|string|max:2',
            'employment_insured_date_year' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'employment_insured_date_month' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'employment_insured_date_day' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'employment_fullname' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴー一-龥]+[　][ぁ-んァ-ヴー一-龥]+\z/u',
            'employment_fullname_kana' => 'nullable|string|max:255|regex:/^[ァ-ヴー]+[　][ァ-ヴー]+\z/u',
            'insurance_office_no_4' => 'nullable|string|regex:/^[0-9]{4}$/u',
            'insurance_office_no_6' => 'nullable|string|regex:/^[0-9]{6}$/u',
            'insurance_office_no_cd' => 'nullable|string|regex:/^[0-9]{1}$/u',
            'employment_lastname' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴー一-龥]/u',
            'employment_firstname' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴー一-龥]/u',
            'caregiver_leave_start_date_era' => 'nullable|string|max:2',
            'caregiver_leave_start_date_year' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'caregiver_leave_start_date_month' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'caregiver_leave_start_date_day' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'dependent_mynumber_card_no' => 'nullable|string|regex:/^[0-9]{12}$/u',
            'dependent_lastname_kana' => 'nullable|string|max:255|regex:/^[ァ-ヴー]+[　][ァ-ヴー]+\z/u',
            'dependent_firstname_kana' => 'nullable|string|max:255|regex:/^[ァ-ヴー]+[　][ァ-ヴー]+\z/u',
            'dependent_sex' => 'nullable|int|max:2',
            'dependent_relationship' => 'nullable|int|max:7',
            'dependent_lastname' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴー一-龥]+[　][ぁ-んァ-ヴー一-龥]+\z/u',
            'dependent_firstname' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴー一-龥]+[　][ぁ-んァ-ヴー一-龥]+\z/u',
            'care_target_family_birthday_era' => 'nullable|string|max:2',
            'care_target_family_birthday_year' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'care_target_family_birthday_month' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'care_target_family_birthday_day' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_era_1' => 'nullable|string|max:2',
            'pay_target_period_year_start_1' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_month_start_1' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_day_start_1' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_month_end_1' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_day_end_1' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'full_time_leave_days_1' => 'nullable|int|between:1,99|regex:/^[0-9]{1,7}$/u',
            'paid_wage_amount_1' => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            'pay_target_period_era_2' => 'nullable|string|max:2',
            'pay_target_period_year_start_2' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_month_start_2' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_day_start_2' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_month_end_2' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_day_end_2' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'full_time_leave_days_2' => 'nullable|int|between:1,99|regex:/^[0-9]{1,7}$/u',
            'paid_wage_amount_2' => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            'pay_target_period_era_3' => 'nullable|string|max:2',
            'pay_target_period_year_start_3' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_month_start_3' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_day_start_3' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_month_end_3' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'pay_target_period_day_end_3' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'full_time_leave_days_3' => 'nullable|int|between:1,99|regex:/^[0-9]{1,7}$/u',
            'paid_wage_amount_3' => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            'caregiver_leave_end_date_era' => 'nullable|string|max:2',
            'caregiver_leave_end_date_year' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'caregiver_leave_end_date_month' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'caregiver_leave_end_date_day' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'caregiver_leave_end_reason' => 'nullable|string|max:255',
            'verification_date_era' => 'nullable|string|max:2',
            'verification_date_year' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'verification_date_month' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'verification_date_day' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'branch_address' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴ０-９ー一-龥　]+\z/',
            'entrepreneur_name' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴー一-龥]+[　][ぁ-んァ-ヴー一-龥]+\z/u',
            'application_date_era' => 'nullable|string|max:2',
            'application_date_year' => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            'application_date_month' => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            'application_date_day' => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            'hello_work_destination' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴー一-龥]/u',
            'bank_name' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴー一-龥]/u',
            'bank_name_kana' => 'nullable|string|max:255|regex:/^[ァ-ヴー]/u',
            'bank_head_office_branch_office_type' => 'nullable|string',
            'bank_code' => 'nullable|int|max:4',
            'bank_store_code' => 'nullable|int|max:3',
            'bank_account_no' => 'nullable|int|max:13',
            'japan_post_bank_code_no' => 'nullable|int|max:5',
            'japan_post_bank_account_no' => 'nullable|int|max:8',
            'wage_deadline_date' => 'nullable|int|between:1,99|regex:/^[0-9]{1,7}$/u',
            'wage_due_date_month' => 'nullable|string',
            'wage_deadline_date' => 'nullable|int|between:1,99|regex:/^[0-9]{1,7}$/u',
            'commuting_allowance_existence' => 'nullable|string',
            'commuting_allowance_period' => 'nullable|string',
            'commuting_allowance_period_other' => 'nullable|string|max:255',
            'note_main' => 'nullable|string|max:255',
            'creation_date_submission_agent_2' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴ０-９ー一-龥　]+\z/u',
            'labor_consultant_fullname_2' => 'nullable|string|max:255|regex:/^[ぁ-んァ-ヴ０-９ー一-龥　]+\z/u',
        ];
    }

    public function messages()
    {
        return [
            // 例
            // 'employment_insured_no_4digit.string' => 'メッセージのカスタマイズしたい場合はこちらを使用',
        ];
    }

    public function attributes()
    {
        return [
            'employment_mynumber_card_no' => '介護休業被保険者の個人番号',
            'employment_insured_no_4' => '被保険者番号4桁',
            'employment_insured_no_6' => '被保険者番号6桁',
            'employment_insured_no_cd' => '被保険者番号1桁',
            'employment_insured_date_era' => '資格取得年月日/年号',
            'employment_insured_date_year' => '資格取得年月日/年',
            'employment_insured_date_month' => '資格取得年月日/月',
            'employment_insured_date_day' => '資格取得年月日/日',
            'employment_fullname' => '被保険者氏名',
            'employment_fullname_kana' => 'フリガナ（カタカナ）',
            'insurance_office_no_4' => '事業所番号4桁',
            'insurance_office_no_6' => '事業所番号6桁',
            'insurance_office_no_cd' => '事業所番号1桁',
            'employment_lastname' => '姓（漢字）',
            'employment_firstname' => '名（漢字）',
            'caregiver_leave_start_date_era' => '介護休業開始年月日/年号',
            'caregiver_leave_start_date_year' => '介護休業開始年月日/年',
            'caregiver_leave_start_date_month' => '介護休業開始年月日/月',
            'caregiver_leave_start_date_day' => '介護休業開始年月日/日',
            'dependent_mynumber_card_no' => '介護対象家族の個人番号',
            'dependent_lastname_kana' => '介護対象家族の姓（カタカナ）',
            'dependent_firstname_kana' => '介護対象家族の名（カタカナ）',
            'dependent_sex' => '介護対象家族の性別',
            'dependent_relationship' => '介護対象家族の続柄',
            'dependent_lastname' => '介護対象家族の姓（カタカナ）',
            'dependent_firstname' => '介護対象家族の名（カタカナ）',
            'care_target_family_birthday_era' => '介護対象家族の生年月日/年号',
            'care_target_family_birthday_year' => '介護対象家族の生年月日/年',
            'care_target_family_birthday_month' => '介護対象家族の生年月日/月',
            'care_target_family_birthday_day' => '介護対象家族の生年月日/日',
            'pay_target_period_era_1' => '支給対象期間その１（初日－末日）/初日_年号',
            'pay_target_period_year_start_1' => '支給対象期間その１（初日－末日）/初日_年',
            'pay_target_period_month_start_1' => '支給対象期間その１（初日－末日）/初日_月',
            'pay_target_period_day_start_1' => '支給対象期間その１（初日－末日）/初日_日',
            'pay_target_period_month_end_1' => '支給対象期間その１（初日－末日）/末日_月',
            'pay_target_period_day_end_1' => '支給対象期間その１（初日－末日）/末日_日',
            'full_time_leave_days_1' => '全日休業日数その１',
            'paid_wage_amount_1' => '支払われた賃金額その１',
            'pay_target_period_era_2' => '支給対象期間その２（初日－末日）/初日_年号',
            'pay_target_period_year_start_2' => '支給対象期間その２（初日－末日）/初日_年',
            'pay_target_period_month_start_2' => '支給対象期間その２（初日－末日）/初日_月',
            'pay_target_period_day_start_2' => '支給対象期間その２（初日－末日）/初日_日',
            'pay_target_period_month_end_2' => '支給対象期間その２（初日－末日）/末日_月',
            'pay_target_period_day_end_2' => '支給対象期間その２（初日－末日）/末日_日',
            'full_time_leave_days_2' => '全日休業日数その２',
            'paid_wage_amount_2' => '支払われた賃金額/その２',
            'pay_target_period_era_3' => '支給対象期間その３（初日－末日）/初日_年号',
            'pay_target_period_year_start_3' => '支給対象期間その３（初日－末日）/初日_年',
            'pay_target_period_month_start_3' => '支給対象期間その３（初日－末日）/初日_月',
            'pay_target_period_day_start_3' => '支給対象期間その３（初日－末日）/初日_日',
            'pay_target_period_month_end_3' => '支給対象期間その３（初日－末日）/末日_月',
            'pay_target_period_day_end_3' => '支給対象期間その３（初日－末日）/末日_日',
            'full_time_leave_days_3' => '全日休業日数その３',
            'paid_wage_amount_3' => '支払われた賃金額/その３',
            'caregiver_leave_end_date_era' => '介護休業終了年月日/年号',
            'caregiver_leave_end_date_year' => '介護休業終了年月日/年',
            'caregiver_leave_end_date_month' => '介護休業終了年月日/月',
            'caregiver_leave_end_date_day' => '介護休業終了年月日/日',
            'caregiver_leave_end_reason' => '終了事由',
            'verification_date_era' => '証明年月日/年号',
            'verification_date_year' => '証明年月日/年',
            'verification_date_month' => '証明年月日/月',
            'verification_date_day' => '証明年月日/日',
            'branch_address' => '事業所名（所在地・電話番号）',
            'entrepreneur_name' => '事業主氏名',
            'application_date_era' => '申請年月日/年号',
            'application_date_year' => '申請年月日/年',
            'application_date_month' => '申請年月日/月',
            'application_date_day' => '申請年月日/日',
            'hello_work_destination' => '公共職業安定所名',
            'bank_name' => '銀行名称',
            'bank_name_kana' => '銀行名称/（カタカナ）',
            'bank_head_office_branch_office_type' => '本店支店区分',
            'bank_code' => '金融機関コード',
            'bank_store_code' => '店舗コード',
            'bank_account_no' => '銀行等(ゆうちょ以外)/口座番号',
            'japan_post_bank_code_no' => 'ゆうちょ銀行/記号',
            'japan_post_bank_account_no' => 'ゆうちょ銀行/番号',
            'wage_deadline_date' => '賃金締切日',
            'wage_due_date_month' => '賃金支払日/当翌月',
            'wage_deadline_date' => '賃金支払日/日',
            'commuting_allowance_existence' => '通勤手当/有無',
            'commuting_allowance_period' => '通勤手当/期間',
            'commuting_allowance_period_other' => '通勤手当/期間/その他',
            'note_main' => '備考',
            'creation_date_submission_agent_2' => '社会保険労務士記載欄/作成年月日･提出代行者･事務代理者の表示',
            'labor_consultant_fullname_2' => '社会保険労務士記載欄/氏名',
        ];
    }
}
