<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EmploymentInsuredRetirementCertificateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    public function validationData()
    {
        $data = $this->all();

        if (isset($data['name'])) {
            $data['name'] = mb_convert_kana($data['name'], 'S');
        }
        if (isset($data['name_kana'])) {
            $data['name_kana'] = mb_convert_kana($data['name_kana'], 'S');
        }
        if (isset($data['branch_name'])) {
            $data['branch_name'] = mb_convert_kana($data['branch_name'], 'AS');
            $data['branch_name'] = str_replace(['-', '－', '―'], '‐', $data['branch_name']);
        }
        if (isset($data['company_name'])) {
            $data['company_name'] = mb_convert_kana($data['company_name'], 'AS');
            $data['company_name'] = str_replace(['-', '－', '―'], '‐', $data['company_name']);
        }
        if (isset($data['headquarters_address'])) {
            $data['headquarters_address'] = mb_convert_kana($data['headquarters_address'], 'AS');
            $data['headquarters_address'] = str_replace(['-', '－', '―'], '‐', $data['headquarters_address']);
        }
        if (isset($data['employee_address'])) {
            $data['employee_address'] = mb_convert_kana($data['employee_address'], 'AS');
            $data['employee_address'] = str_replace(['-', '－', '―'], '‐', $data['employee_address']);
        }
        if (isset($data['branch_address'])) {
            $data['branch_address'] = mb_convert_kana($data['branch_address'], 'AS');
            $data['branch_address'] = str_replace(['-', '－', '―'], '‐', $data['branch_address']);
        }
        if (isset($data['labor_consultant_acting_as_agent_name'])) {
            $data['labor_consultant_acting_as_agent_name'] = mb_convert_kana($data['labor_consultant_acting_as_agent_name'], 'S');
        }
        if (isset($data['labor_consultant_name'])) {
            $data['labor_consultant_name'] = mb_convert_kana($data['labor_consultant_name'], 'S');
        }


        return $data;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */

    public static function rules(): array
    {
        return [
            "insurance_office_no_4" => 'string|regex:/^[0-9]{4}$/u',
            "insurance_office_no_6" => 'string|regex:/^[0-9]{6}$/u',
            "insurance_office_no_CD" => 'string|regex:/^[0-9]{1}$/u',
            "employment_insured_no_4" => 'string|regex:/^[0-9]{4}$/u',
            "employment_insured_no_6" => 'string|regex:/^[0-9]{6}$/u',
            "employment_insured_no_CD" => 'string|regex:/^[0-9]{1}$/u',
            "name" => 'string|max:255|regex:/^[ぁ-んァ-ヴー一-龥々Ａ-Ｚ]+[　][ぁ-んァ-ヴー一-龥々Ａ-Ｚ]+$/u',
            "name_kana" => 'string|max:255|regex:/^[ァ-ヴー]+[　][ァ-ヴー]+$/u',
            "retirement_date_era" => 'string|max:2',
            "retirement_date_year" => 'int|between:1,99|regex:/^[0-9]{1,2}$/u',
            "retirement_date_month" => 'int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "retirement_date_day" => 'int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "branch_name" => 'string|max:255|regex:/\A[ぁ-んァ-ヴー一-龥々０-９ａ-ｚＡ-Ｚ　＆’，‐．・]+\z/u',
            "branch_address" => 'string|max:255|regex:/\A[ぁ-んァ-ヴー一-龥々０-９Ａ-Ｚ　‐]+\z/u',
            "branch_tel_area_code" => 'string|regex:/^[0-9]{1,5}$/u',
            "branch_tel_city_code" => 'string|regex:/^[0-9]{1,5}$/u',
            "branch_tel_subscriber_code" => 'string|regex:/^[0-9]{1,5}$/u',
            "employee_post_code_former" => 'string|regex:/^[0-9]{3}$/u',
            "employee_post_code_latter" => 'string|regex:/^[0-9]{4}$/u',
            "employee_address" => 'string|max:255|regex:/\A[ぁ-んァ-ヴー一-龥々０-９Ａ-Ｚ　‐]+\z/u',
            "employee_tel_area_code" => 'string|regex:/^[0-9]{1,5}$/u',
            "employee_tel_city_code" => 'string|regex:/^[0-9]{1,5}$/u',
            "employee_tel_subscriber_code" => 'string|regex:/^[0-9]{1,5}$/u',
            "company_name" => 'string|max:255|regex:/\A[ぁ-んァ-ヴー一-龥々０-９ａ-ｚＡ-Ｚ　＆’，‐．・]+\z/u',
            "headquarters_address" => 'string|max:255|regex:/\A[ぁ-んァ-ヴー一-龥々０-９Ａ-Ｚ　‐]+\z/u',
            "employer_company_managerial_position_name" => 'string|max:255|regex:/\A[ぁ-んァ-ヴー一-龥々　]+\z/u',
            "the_day_after_retirement_date_month" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "the_day_after_retirement_date_day" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_month" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month" => 'int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day" => 'int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period" => 'int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo" => 'nullable|string|max:255',
            "insured_period_start_month_1" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_1" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_1" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_1" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_1" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_1" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_1" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_1" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_1" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_1" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_1" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_1" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_1" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_1" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_1" => 'nullable|string|max:255',
            "insured_period_start_month_2" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_2" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_2" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_2" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_2" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_2" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_2" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_2" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_2" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_2" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_2" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_2" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_2" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_2" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_2" => 'nullable|string|max:255',
            "insured_period_start_month_3" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_3" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_3" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_3" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_3" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_3" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_3" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_3" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_3" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_3" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_3" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_3" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_3" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_3" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_3" => 'nullable|string|max:255',
            "insured_period_start_month_4" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_4" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_4" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_4" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_4" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_4" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_4" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_4" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_4" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_4" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_4" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_4" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_4" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_4" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_4" => 'nullable|string|max:255',
            "insured_period_start_month_5" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_5" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_5" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_5" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_5" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_5" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_5" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_5" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_5" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_5" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_5" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_5" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_5" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_5" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_5" => 'nullable|string|max:255',
            "insured_period_start_month_6" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_6" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_6" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_6" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_6" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_6" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_6" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_6" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_6" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_6" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_6" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_6" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_6" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_6" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_6" => 'nullable|string|max:255',
            "insured_period_start_month_7" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_7" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_7" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_7" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_7" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_7" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_7" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_7" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_7" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_7" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_7" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_7" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_7" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_7" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_7" => 'nullable|string|max:255',
            "insured_period_start_month_8" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_8" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_8" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_8" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_8" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_8" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_8" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_8" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_8" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_8" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_8" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_8" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_8" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_8" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_8" => 'nullable|string|max:255',
            "insured_period_start_month_9" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_9" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_9" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_9" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_9" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_9" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_9" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_9" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_9" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_9" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_9" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_9" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_9" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_9" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_9" => 'nullable|string|max:255',
            "insured_period_start_month_10" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_10" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_10" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_10" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_10" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_10" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_10" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_10" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_10" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_10" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_10" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_10" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_10" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_10" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_10" => 'nullable|string|max:255',
            "insured_period_start_month_11" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_11" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_11" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_11" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_11" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_11" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_11" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_11" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_11" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_11" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_11" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_11" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_11" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_11" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_11" => 'nullable|string|max:255',
            "insured_period_start_month_12" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_12" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_12" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_12" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_12" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_12" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_12" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_12" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_12" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_12" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_12" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_12" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_12" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_12" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_12" => 'nullable|string|max:255',
            "insured_period_start_month_13" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_13" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_13" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_13" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_13" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_13" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_13" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_13" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_13" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_13" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_13" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_13" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_13" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_13" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_13" => 'nullable|string|max:255',
            "insured_period_start_month_14" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_14" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_14" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_14" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_14" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_14" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_14" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_14" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_14" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_14" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_14" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_14" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_14" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_14" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_14" => 'nullable|string|max:255',
            "insured_period_start_month_15" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_15" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_15" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_15" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_15" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_15" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_15" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_15" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_15" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_15" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_15" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_15" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_15" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_15" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_15" => 'nullable|string|max:255',
            "insured_period_start_month_16" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_16" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_16" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_16" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_16" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_16" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_16" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_16" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_16" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_16" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_16" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_16" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_16" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_16" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_16" => 'nullable|string|max:255',
            "insured_period_start_month_17" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_17" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_17" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_17" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_17" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_17" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_17" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_17" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_17" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_17" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_17" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_17" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_17" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_17" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_17" => 'nullable|string|max:255',
            "insured_period_start_month_18" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_18" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_18" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_18" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_18" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_18" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_18" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_18" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_18" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_18" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_18" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_18" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_18" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_18" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_18" => 'nullable|string|max:255',
            "insured_period_start_month_19" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_19" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_19" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_19" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_19" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_19" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_19" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_19" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_19" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_19" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_19" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_19" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_19" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_19" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_19" => 'nullable|string|max:255',
            "insured_period_start_month_20" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_20" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_20" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_20" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_20" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_20" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_20" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_20" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_20" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_20" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_20" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_20" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_20" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_20" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_20" => 'nullable|string|max:255',
            "insured_period_start_month_21" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_21" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_21" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_21" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_21" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_21" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_21" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_21" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_21" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_21" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_21" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_21" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_21" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_21" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_21" => 'nullable|string|max:255',
            "insured_period_start_month_22" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_22" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_22" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_22" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_22" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_22" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_22" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_22" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_22" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_22" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_22" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_22" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_22" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_22" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_22" => 'nullable|string|max:255',
            "insured_period_start_month_23" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_23" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_23" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_23" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_23" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_23" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_23" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_23" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_23" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_23" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_23" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_23" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_23" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_23" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_23" => 'nullable|string|max:255',
            "insured_period_start_month_24" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_start_day_24" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_month_24" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "insured_period_end_day_24" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "insured_period_month_1_24" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "basic_days_for_salary_payment_of_insured_period_24" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_month_24" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_start_day_24" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_month_24" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "salary_payment_period_end_day_24" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "basic_days_of_salary_payment_period_24" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "salary_amount_A_24" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_B_24" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "salary_amount_total_24" => 'nullable|int|between:1,9999999|regex:/^[0-9]{1,7}$/u',
            "memo_24" => 'nullable|string|max:255',
            "salary_notices" => 'nullable|string|max:255',
            "salary_notices_1" => 'nullable|string|max:255',
            "remarks" => 'nullable|string|max:255',
            "remarks_1" => 'nullable|string|max:255',
            "labor_consultant_japan_era" => 'nullable|string|max:2',
            "labor_consultant_japan_era_year" => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            "labor_consultant_month" => 'nullable|int|between:1,12|regex:/^[0-9]{1,2}$/u',
            "labor_consultant_day" => 'nullable|int|between:1,31|regex:/^[0-9]{1,2}$/u',
            "labor_consultant_acting_as_agent_name" => 'nullable|string|max:255|regex:/\A[ぁ-んァ-ヴー一-龥々０-９Ａ-Ｚ　]+\z/u',
            "labor_consultant_name" => 'nullable|string|max:255|regex:/\A[ぁ-んァ-ヴー一-龥々０-９Ａ-Ｚ　]+\z/u',
            "labor_consultant_tel_area_code" => 'nullable|string|regex:/^[0-9]{1,5}$/u',
            "labor_consultant_tel_city_code" => 'nullable|string|regex:/^[0-9]{1,5}$/u',
            "labor_consultant_tel_subscriber_code" => 'nullable|string|regex:/^[0-9]{1,5}$/u',
            "contract_period_reached_limit_contract_period_once" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "contract_period_reached_limit_contract_period_total" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "contract_period_reached_limit_contract_renewal_count" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "eternal_hire_contract_period_once" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "eternal_hire_contract_period_total" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "eternal_hire_contract_renewal_count" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "except_eternal_hire_contract_period_once" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "except_eternal_hire_contract_period_total" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "except_eternal_hire_contract_renewal_count" => 'nullable|int|between:1,999|regex:/^[0-9]{1,3}$/u',
            "retirement_age" => 'nullable|int|between:1,99|regex:/^[0-9]{1,2}$/u',
            "shortened_contract_renewal_reached_limit_flg" => 'nullable|string|in:する,しない',
            "contract_renewal_reached_limit_flg" => 'nullable|string|in:する,しない',
            "rehire_contract_renewal_reached_limit_flg" => 'nullable|string|in:ある,ない',
            "contract_period_total_reached_limit_flg" => 'nullable|string|in:ある,ない',
            "contract_period_total_established_before_law_amendment_flg" => 'nullable|string|in:いた,いなかった',
            "eternal_hire_contract_renewal_guarantee_agreement_flg" => 'nullable|string|in:有,無',
            "contract_non_renewal_flg" => 'nullable|string|in:有,無',
            "employment_termination_notice_flg" => 'nullable|string|in:有,無',
            "non_renewal_clause_addition_flg" => 'nullable|string|in:ある,ない',
            "eternal_hire_contract_renewal_request_type" => 'nullable|string|in:希望する申出有,希望しない申出有,申出無',
            "contract_renewal_guarantee_agreement_flg" => 'nullable|string|in:有,無',
            "no_contract_renewal_flg" => 'nullable|string|in:有,無',
            "contract_renewal_request_type" => 'nullable|string|in:希望する申出有,希望しない申出有,申出無',
            "employment_instructions_type" => 'nullable|string|in:労働者が適用基準に派遣就業の指示を拒否したことによる場合,事業主が派遣就業の指示を行わなかったことによる場合',
            "education_training_flg" => 'nullable|string|in:有,無',
            "objection_retirement_reason_flg" => 'nullable|string|in:有,無',
            "dispatched_employee_flg" => 'nullable|string|in:常時雇用される労働者,常時雇用される労働者以外',
            "reemployment_request_flg" => 'nullable|string|in:有,無',
            "retirement_reason_type" => 'nullable|string|in:就業規則に定める事由に該当したため,労使協定に定めた基準に該当しなかったため,その他',
            "retirement_reason" => 'nullable|string|max:255',
            "retirement_recommendation_reason" => 'nullable|string|max:255',
            "change_office_place" => 'nullable|string|max:255',
            "employee_decision_reasons" => 'nullable|string|max:255',
            "other_reasons" => 'nullable|string|max:255',
            "memo_for_employer" => 'nullable|string|max:255',
            'apply_to_code' => 'required|string',
            'apply_to_name' => 'required|string'
        ];
    }
}
